### ISSUE TITLE
Compositor crashing

### ISSUE THREAD

**Issue by cubiclestorm** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#1]
I constantly have issues with SteamVR compositor crashing on me, error -203, when I do a click and drag playspace move. When I click to turn the compositor back on my steam menu won't come up anymore. 

After restarting steamVR my playspace will be stuck where I crashed at and I have to do Room scale setup again.

This happens in SteamVR even with no games running

I'm using an Oculus. I have also found the the error happens most when steam uses the Oculus guardian boundaries, so I run SteamVR room setup to use the Steam boundaries instead. It's more stable but will crash reliably.

[AdvancedSettings.log](https://github.com/icewind1991/OpenVR-AdvancedSettings/files/1886655/AdvancedSettings.log)

**Comment by Kungrum** [comment]
I'm having the same issue but on Vive. It seems to crash more often when game fps is low while dragging a playspace move.

**Comment by ykeara** [comment]
Issue was fixed/mitigated by removing some logging. should have been around https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/commit/734581f495e4cd736e8b7d8b33501f1f6c752f10
