### ISSUE TITLE
Call for Testers, feedback on form.

### ISSUE THREAD

**Issue by ykeara** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#104]
Quick Write-up for Presumably Reddit, thoughts, comments and concerns.

# Advanced Settings Needs Testers~!

## Who Are we Looking for?
* 1 or 2 **WMR** Users
* 1 or 2 **Rift** Users
* 1 or 2 **Pimax** Users
* 1 or 2 **Vive/Vive Pro** Users
* anyone that has an odd/non-standard set-up. Nolo, cardboard ETC.
**Note:** You can fill multiple roles.

## What do we want/Responsibilites
* Test Builds before "releases"
* Provide feedback on Builds, including but not limited to: bugs, layout, behavior.
* Answer and write issues out on github, and more informally via discord.
* Keep your eyes and ears open for new features, bugs, suggestions and more that other users may encounter.

## What do you get?
* love and affection.
* Credit as a tester.

## The Talk.

We are looking for a few people to help us test builds adequatly so we can provide high quality builds free (well mostly) of bugs, and annoyances.
We want a small group of people that can dedicate a few hours a month 1-4 (but we won't complain if you want to spend more) to test on-going development builds.
We want you to document the bug, how it happened, how to make it happen, and write up a bug report via github, and bring us any suggestions users might have.
Honestly, it may sound scary, but we don't bite. We could just use some extra eyes, different specced systems, and some sanity checks for when we get way too invested in a terrible idea.

## Interested? Questions?

Reply Here or send me a DM via reddit.

### Q & A
**What is Advanced Settings?**
It is an open-source SteamVR/OpenVR overlay utility that provides a plethora of features, such as warnings when near chaperone, disable-ing chaperone, PTT, ETC.

**Where can I get it?**
[Releases](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/releases)
[GitHub Project](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings)

**I don't Know How to Code.**
not a problem! we don't actually expect our testers to be programmers. Basic understanding of programming may help, but honestly as long as you are reasonably tech savy (i.e. you don't freak out if something breaks, because it will).

**I have my own patch/version of ADV settings**
come talk to us, we would love to include your changes (so long as they are not too far from the "settings part"). Or just submit a PR directly via github, and we will review it.

**Who Made/makes ADV-Settings?**- [Matzman666](https://github.com/matzman666/OpenVR-AdvancedSettings) Is the original creator, but Is currently too busy to work on it, and is happy that we are continuing to help develop and further open-source VR projects. Now it's a small group (4 of us) (username223, kung, icewind, and I [ykeara]) working on it, but there are a handful of others as well, check out [github contribs](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/graphs/contributors) for the full list.

**Comment by indeu** [comment]
I'm interested in. but I'm not normal VR environment. 

The PSVR with iVRy driver and Nolo CV1 tracker and controllers(latest firmware). 
I checked today's developing version works fine for me.

Thanks.

**Comment by ykeara** [comment]
Post Is live, closing for now.
