### ISSUE TITLE
Move SteamVR actions into separate action sets

### ISSUE THREAD

**Issue by username223** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#111]
This provides improved cohesion because actions are grouped with other, relevant actions instead of just being listed A-Z in one big pile.

**Comment by ykeara** [comment]
Look at #109 for suggestions,

But In general I was thinking

Movement: basic
Misc. PTT/gravity?
movement Advanced (overrides and toggle x/y etc.)
Accessibility: snap turn/toggle height etc.
Music.

Not really 100% sure but just an idea to play around with.
