### ISSUE TITLE
3.0.0 preliminary release draft

### ISSUE THREAD

**Issue by ykeara** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#127]
DRAFT FINAL RELEASE 3/26/19
Title: Advanced Settings 3.0.0 SteamVr Input, and overhauled motion.

# **IMPORTANT**

 * Changing bindings in overlays **requires SteamVR 1.3.1 or later** so you will have to use **Beta SteamVR** until this change gets pushed to live if you want to change from the default bindings.
 * This version of Adanced Settings Uses the SteamVR Input System If you are not familiar with it please look at one of our guides:
   * [New Features Video Guide](https://www.youtube.com/watch?v=2ZHdjOfnqOU&feature=youtu.be) by Kung
   * [Written Guide](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/blob/master/docs/SteamVRInputGuide.md) by Ykeara
 * This version of Advanced Settings is a breaking change, you will be required to generate new saves/preferences with it.
 * We consider the Re-Vive tab deprecated, and will be removing it in the next major release. If we are insane for doing this message us please.

## Where do I get it?

* Download for latest release will always be [Here](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/releases)
* You can visit our project page on github at [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings)

## HeadLines of Change!

* SteamVR input System fully implmented, Bind your keys in whatever set-up you want, support for theoretically any and all controllers!
* Major overhaul to our motion controls
  * [Space Turn](https://i.imgur.com/JgbiCUE.gifv)
  * [Gravity](https://i.imgur.com/ctK5pE7.gifv)
  * [Snap Turn](https://i.imgur.com/L7dRfoU.gifv)
  * and more....

## What Is SteamVR Input?

The SteamVr input, is a method that allows us to expose "actions" to users to allow them to key-bind them how they see fit on a controller.

What is an action?

* simply put something you do.
  * jump
  * shoot
  * interact
  * etc.

I'm lazy I don't want to set my own keybinds.

* we include some default keybindings
* you can share/copy other people's keybindings if they save them to the workshop

Why did we implment it?
* Old input methods are deprecated
* Many features in upcoming controller requires it.
* complete control to the user.
* less code on our end!

**Still Confused?**
Read/watch the guide's linked above

And for the Dev's out there, feel free to inspect us if you are having issues getting things working in your projects.

### Features
* Implemented space-turn (grab to rotate space) enabling manual redirected walking. - [Kung](https://github.com/Kung-vr)
* Implemented gravity and momentum for space-drag. - [Kung](https://github.com/Kung-vr)
* Created “Motion” tab with configuration options for: Space Turn/Drag, Snap Turn, Gravity, Height Toggle and Comfort Options. - [Kung](https://github.com/Kung-vr)
* Added “Apply Space Settings Offsets as Center” feature to the Space Fix tab. - [Kung](https://github.com/Kung-vr)
* Added Alt+Enter keyboard combination to Utilities tab. - [username223](https://github.com/username223)
* The Steam Desktop Overlay width slider setting will now be remembered. - [username223](https://github.com/username223)
* Added Knuckles support for floor fixing feature. - [Ykeara](https://github.com/ykeara)
* Added Disable Chaperone button. - [Ykeara](https://github.com/ykeara)

### Bindings
* The SteamVR bindings system is the new way for applications to handle inputs. Arbitrary controllers are supported. A guide can be found [here](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/blob/master/docs/SteamVRInputGuide.md)
* Added Space Turn/Drag controller bindings. - [Kung](https://github.com/Kung-vr)
* Added Gravity Reverse/Gravity Toggle controller bindings. - [Kung](https://github.com/Kung-vr)
* Added Snap Turn Left/Right controller bindings. - [Kung](https://github.com/Kung-vr)
* Added X/Y/Z Axis Lock Toggle controller bindings. - [Kung](https://github.com/Kung-vr)
* Added Reset Offsets controller binding. - [Kung](https://github.com/Kung-vr)
* Added Height Toggle controller binding. - [Kung](https://github.com/Kung-vr)
* Added Play/Stop/Previous/Next music controller bindings (Windows only). - [username223](https://github.com/username223)
* Added Push To Talk controller binding. - [username223](https://github.com/username223)

### Removed
* Removed Accessiblity tab. Features have been moved to other tabs.
* Proximity sensor integration with chaperone warnings. Should return in the future.
* Proximity sensor Mute for microphone. Should return in the future.

### Fixes
* Fixed OVRAS crashing when exiting SteamVR. - [username223](https://github.com/username223)
* Reset offsets function now restores a chaperone bounds and universe center backup rather than apply the reverse of current offsets. This removes the possibility of drift from the reset function. - [Kung](https://github.com/Kung-vr)
* Space-drag and the new space-turn now perform with vsync, improving smoothness. - [Kung](https://github.com/Kung-vr)
* Fixed crash related to Vive Wireless and audio devices. - [bdonlan](https://github.com/bdonlan)
* Fixed bug where chaperone bounds were not read correctly, disabling chaperone warnings. - [Ykeara](https://github.com/ykeara)

### Windows
* Changed logging and settings directory. Previously was `%APPDATA%\matzman666\`, is now `%APPDATA%\AdvancedSettings-Team\`. - [username223](https://github.com/username223)
* Added icons to installer and binary on Windows. Icons by [Kung](https://github.com/Kung-vr). - [username223](https://github.com/username223)

### Linux
* Improved Linux usability. - [username223](https://github.com/username223)
* Added Linux build scripts. The `build_scripts/linux/build_linux.sh` script will build with `g++-7` by default and put the binary in `build/bin/linux/AdvancedSettings/`. - [username223](https://github.com/username223)
* Moved location of required Linux files. Resource files are required to be in the binary directory. Logging and settings will be in `~/.local/share/AdvancedSettings-Team/OpenVRAdvancedSettings/`. - [username223](https://github.com/username223)
* Several Linux features are still missing. The issue is tracked on Github [here](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/issues/43).

### Deprecation Warning
* The Re-Vive tab will be removed in the next major version due to compatibility and maintenance concerns. If you are using this feature reach out to us.

## Found a Bug? Suggestion?

Please either open an issue on the github repo [here](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/issues) or contact Us directly. you can ofc leave suggestions on this topic as well.

## On the Horizon.

As always we love to hear suggestions from you guys on what should be in it. Especially things related to accessibility, Quality of Life, and Ease of Use. We have continued plans, but always post your suggestions not everything happens but you help shape it.

## Q & A

**Q:** Installer is flagged as a virus from x.
 **A:** This should be due to NSIS (the packager we use to create the installer). You can use the standalone (.7z) or you can compile/inspect the code yourself, the code is open-source on github.

**Q:** Why did you switch to the New Input method?
 **A:** Not only are the old methods deprecated, this gives you complete control over your keybinds, while simplifying the amount of code we have to write.

**Q:** I can't seem to get the inputs to work.
 **A:** This version uses the New Binding system from Steam, I would Suggest reading/watching one of our guides

**Q:** How Do I set up my keybinds?
 **A:** Either inside of Vr click "steam"-> Controller Binding -> Advanced Settings OR go to http://127.0.0.1:8998/dashboard/controllerbinding.html while SteamVR is running.

**Q:** Advanced Settings isn't showing up as an application in binding interface?
 **A:** Please make sure you are on SteamVR Beta as we require steamVR 1.3.1 for it to work properly.

**Comment by Kung-vr** [comment]
Only change I request, instead of calling it "Video Tutorial" could you call it "New Features Video Guide"? I know it's slightly longer, but the video wasn't designed as just a tutorial for the input system, in fact that was left for later in the video because it's the longest/slowest part. So if it's labeled as a tutorial for that people will think "get to the point, get to the point" when it's not the only point.

Otherwise, looks great!

**Comment by ykeara** [comment]
gotcha and done... just gonna leave this open until I pose to see If anyone else has any changes.

**Comment by ykeara** [comment]
TODO Change Space Turn/Gravity/Snap Turn to Gifs w/ links

**Comment by Kung-vr** [comment]
^ Gifs added

**Comment by Monster1234** [comment]
Hi there, can you make it so that PlaySpace rotation is persistent? Steam VR automatically chooses my direction but I need to have it in one particular direction. So Im using PlaySpace rotation but its temporary.

**Comment by Kung-vr** [comment]
The best solution to this I think is to point your controller in a different direction when the room setup asks you to point at your PC and pull the trigger. (It assumes your wires go behind you to the pc so when you're doing this you're selecting which direction is "back").

If you really want to do this with advanced settings, you can set your rotation, then manually type in zero for the offsets that appear (because you swing the world center around you head's position), then go to the space fix tab and click “Apply Space Settings Offsets as Center” this will redefine your basis zero position, rotation and all. You can then go into the chaperone tab and save that setup as a profile if you need to get it back later.

(Side note, it's easier for us to find issues if they're posted as their own issues rather than comments to different issues)

**Comment by Monster1234** [comment]
Thanks a lot! Btw I setup the room again but its not selecting the "back" direction for me. Anyways, I found that while setting the room, I can change the room direction in advanced mode.
