### ISSUE TITLE
Smooth Turning, and Smooth Locomotion

### ISSUE THREAD

**Issue by ykeara** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#131]
I would like to implement smooth turning as companion for snap turn, but in addition we could set-up traditional joystick locomotion fairly easily.... I am a bit worried about scope of project Though. But Interesting enough that I might consider breaking it off in its own app.

**Comment by Kung-vr** [comment]
Would be trivial to do... but would really start to encroach on the "cheating" concerns that are already showing. Fine controls with arbitrary speed might not be so good.

**Comment by ykeara** [comment]
Closed For now....
