### ISSUE TITLE
Add user defined bindings for keyboard key presses

### ISSUE THREAD

**Issue by username223** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#138]
As requested [here](https://old.reddit.com/r/Vive/comments/b5s0no/advanced_settings_300_steamvr_input_and/ejg0xjy/).

There should be one or more bindings that correspond to a key press or key sequence that is easily user definable.

**Comment by ykeara** [comment]
Perhaps there is an easy way to capture a keypress via QT, and then store that value?

**Comment by jdawgzim** [comment]
This would allow me to control **Discord** separately from VR game!  Yes pleaaaaazzzzeee!

**Comment by guiglass** [comment]
I would live to be able to rotate the playspace via keybaord. It would be so useful.

**Comment by username223** [comment]
@guiglass So press a key on the keyboard and it acts like the already existing VR keybinds?

What is the use case for this?

**Comment by username223** [comment]
After doing some thinking I have come up with the below spec. It functions almost identically to the current "Keyboard Input" parser, except shift support is different.

It will allow end users who don't need modifier key support to just use single letters or letter sequences very simply, while still allowing people who need modifier keys to do so relatively simply.

It is also not constrained arbitrary restrictions except around keyboard locales.

The actual spec is mostly so I don't have to make everything up as I'm implementing it. There's basically no need to read everything, just look at the examples section and you'll get the gist.
___
## Specification considerations for sending keys to OS

The currently implemented parser, the same one used in the "Keyboard Input" button on the Utilities page, can handle a sequence of characters with shift key support. It does not support the ctrl, alt or super modifier keys.

The current spec sends a key press and release before sending the next key. The shift key is held down if two or more keys in a row are capitals.

The replacement spec should be easy to use for non-technical end users, while not being too limited for more technical end-users.

Key down (pressed) is defined as `KEY+` and key up (released) is defined as `KEY-`. Pressing and releasing the `a` key would be `a+, a-`.

A hard requirement is being able to trigger the numpad asterisk key (NUM_\*+, NUM_\*-) and a Ctrl + H sequence (Ctrl+, H+, H-, Ctrl-).

Ideally the same algorithm would handle both sequential non-modifier characters and a single modifier enabled key.

The VR keyboard does not have a numpad, which means it's necessary to have specific string values for numpad keys and then parse the string with that in mind.

Supporting all localizations is most likely going to be a nightmare outside of the scope of this project. Only QWERTY support should be expected. 

## Suggested spec

### Definitions

A modifier key is either Alt, Ctrl, Super, AltGr or Shift. Only the left variants of modifiers with several versions are supported.

A literal key is either a-z, 0-9, Backspace, Enter, Space, Tab, Esc, insert, delete, end, page down, page up, NUM_/, NUM_*, NUM_-, NUM_+, CAPS, F1-F12, PRNTSCRN, PAUSE/BREAK, SCROLL LOCK, SPACE or the arrow keys.

A modifier symbol is a single representative symbol of a modifier key.

A literal symbol is a single representative lowercase character or an uppercase character sequence for a literal key.

A token is either a modifier symbol, literal symbol, symbol sequence or space character.


### Modifier symbols

| Modifier | Symbol |
|---|---|
| Ctrl | `^` |
| Alt | `*` |
| Shift | `>` |
| AltGr | `/` |
| Super (Windows) | `#` |

### Literal symbols

| Key | Symbol |
|---|---|
| A to Z | The letter in lowercase. `a`, `b`, `c`, ... |
| Number Row 0-9 | The number. `0`, `1`, `2`, ... |
| Function keys F1-F12 | Capital F followed by number. `F1`, `F2`, `F3`, ... |
| Backspace | `BACKSPACE` |
| Space | `SPACE` |
| Tab | `TAB` |
| Escape | `ESC` |
| Insert | `INS` |
| Delete | `DEL` |
| End | `END` |
| Page Down | `PGDN` |
| Page Up | `PGUP` |
| Caps Lock | `CAPS` |
| Print Screen | `PRNSCRN` |
| Pause/Break | `PAUSE` |
| Scroll Lock | `SCRLOCK` |
| Left Arrow | `LEFTARROW` |
| Right Arrow | `RIGHTARROW` |
| Up Arrow | `UPARROW` |
| Down Arrow | `DOWNARROW` |
| Keypad Slash | `KPSLASH` |
| Keypad Asterisk | `KPSTAR` |
| Keypad Minus | `KPMINUS` |
| Keypad Plus | `KPPLUS` |


### Misc symbols
| Action | Symbol |
|---|---|
| Release Held Keys | ` ` (literal space or end of string) |

### Operation

Strings are parsed from left to right. There is no support for right to left scripts.

The entire string is parsed before any keys are sent. If an invalid sequence is encountered all valid tokens are sent as keys, but the invalid output is discarded and parsing will not continue. A log message may be displayed.

When a modifier token is encountered the modifier is held down until either a space token or the end of the string is encountered.

When a literal token is encountered the literal key is pressed and then released with no other actions in between.

When a space token or end of string is encountered all currently held modifier keys are released in the order they were pressed.

### Misc

There is no way to release modifier keys other than a space or end of string. Additional modifier symbols when that modifier is already pressed does nothing.

Two or more spaces in succession has the same effect as a single space.

There is no limit on the length of the string.

If a specific key is not supported on a platform, triggering that key is a no-op. A log message may be displayed.

Whether A on AZERTY keyboards triggers A or Q is undefined.

Anything to do with unsupported keyboard locales is undefined.

### Examples

| Sequence | String | Key Representation |
|---|---|---|
| Ctrl + H | `^h` | Ctrl+, h+, h-, Ctrl- |
| Ctrl + H + H | `^hh` | Ctrl+, h+, h-, h+, h-, Ctrl- |
| Ctrl + H twice | `^h ^h` | Ctrl+, h+, h-, Ctrl-, Ctrl+, h+, h-, Ctrl- |
| Ctrl + Alt + Delete | `^*DEL` | Ctrl+, Alt+, DEL+, DEL-, Ctrl-, Alt- |
| Alt + Enter | `*ENTER` | Alt+, ENTER+, ENTER-, Alt- |
| H + E + L + P | `help` | h+, h-, e+, e-, l+, l-, p+, p- |
| E + N + D | `end` | e+, e-, n+, n-, d+, d- |
| END Button | `END` | END+, END- |
| Alt + Shift + ENTER | `*>ENTER` | Alt+, Shift+, ENTER+, ENTER-, Alt-, Shift- |
| Alt + Tab + G + G + ENTER + Alt + Tab | `*TAB gg ENTER *TAB` | Alt+, Tab+, Tab-, Alt-, g+, g-, g+, g-, ENTER+, ENTER-, Alt+, Tab+, Tab-, Alt- |

**Comment by jdawgzim** [comment]
So to be clear this is pressing a button on my VR controller that is then sending keyboard presses to the operating system?

**Comment by ykeara** [comment]
Looks good to me as a spec. Can't imagine people not being okay w/ this level of functionality... and if they need more complex interaction I am not sure we should facilitate it.

Now should we overwrite existing keyboard macros, and just replace.... (probably dynamically read from file to change display message in QML would be best as well.) This way we could distribute with A file/files to contain the Existing keyboard binds, but people that want something specific can adjust accordingly

A unique side benefit is this might allow me to pro-grammatically disable re-projection, though I am not sure the UX would be ideal.

**Comment by username223** [comment]
@jdawgzim Yes, that is correct. Initially I'm just going to be implementing the actual parser/tokenizer and then afterwards implement the VR keybind -> OS key without an in-VR interface. Manually editing the .ini file will be necessary, but it's not going to be insanely complicated. I'm a little swamped with other stuff at the moment which is why I'm not just implementing everything in one swoop.

@ykeara I think UX wise the current front end is fine. Having explicitly labeled buttons for common operations is probably a good idea. It will be critical to be able to test keybinds out instantly, to figure out what works for that specific users keyboard layout. Initially I plan on just having it read the settings file because the QML is IMO a bigger pain in the ass than the parser/tokenizer + OpenVR bindings.

I plan on having 3 different VR bindings with user definable strings. This number was arbitrarily chosen in order to avoid bloating the bindings manifest, if people desperately need more we can look at increasing it.

**Comment by jdawgzim** [comment]
Wow, I've been wanting something like this since OpenVR Input Emulator was broken by changes to SteamVR.  Being able to press a VR controller button and activating an external macro program will open a whole new world of possibilities!  Oh, and being able to keep Discord and in-game chat separate with a push to mute/talk buttons will be awesome too.  Thank you!

**Comment by pearce31** [comment]
I and a friend are wanting to be able to map vr controller buttons to keyboard like input emulator had. I did not mean map keyboard keys to vr controller. This is what I meant when I said about keyboard on reddit. Looks like this will soon be possible. Thank you! This is great!

**Comment by marcob2178** [comment]
Hello. Yes please . Could the developer work on adding (as said by @pearce31) the possibility to map vr controller buttons to keyboard, like input emulator had? (press keyboard key and it emulates vr controller button)

Thanks!

**Comment by username223** [comment]
@pearce31 
@marcob2178 
That's pretty far outside the scope of this project. 
Your best bet is to get input emulator working again, although I don't think it has any active maintainers.

**Comment by username223** [comment]
This feature is now in the master branch as per PR #205.

It will be in the next release (3.2.0).

**Comment by marcob2178** [comment]
Sorry  for my ignorance. 
Does it mean that the new release will allow us to use keystrokes like wasd in steamvr through openvr advanced settings ?

**Comment by ykeara** [comment]
you essentially have 3 options.... and you can set those options to send most possible combinations. i.e. you could send wasd or you could send just w or you could send ctrl+s, its not really designed as a keyboard replacement but it will allow you send commands if you need to.

Also to clarify. 3.2.0 is not being released yet (and you can always assume we are a minimum of 1 week out if we don't know due to testing).... simply put its our system x.y.z z are minor changes i.e. bug fixes. y are major changes/new features.... i.e. this and x is a breaking change i.e. legacy input-> action system.

We also have a tendency to batch things together so theya re a little more exciting... and we don't have to test/support things crazy like.

**Comment by marcob2178** [comment]
Thank you so much! Looking forward to it!

I came up with a Wwasd solution for any game by making DIY shoes based on icubex sensors (for Ww) and captosensors (for asd, to be hopefully soon replaced completely by icubex sensors for asd also) , that work in any non vr game, but that would work in vr too, only if you guys would be able to allow us to enable wasd input in steamvr

https://m.youtube.com/watch?v=MTWDe0JmgG8

**Comment by username223** [comment]
@marcob2178 On the current master branch (not as an official release yet) you can use the SteamVR bindings to send key sequences to the OS. There are currently 3 different binds available (meaning you can have 3 different sequences bound to 3 different buttons).

Only key presses and releases are supported, meaning that it is not possible to hold a VR button to hold down a keyboard key. This is not a planned feature.

So you could bind the B button on the Knuckles to press and release the W key. You could also bind it to Ctrl+Shift+M (Ctrl down, shift down, m down, m up, ctrl up, shift up) if you wanted.

>Olso, if wasd is enabled in steamvr, who has got gloves like captogloves, would be able to use the gloves to have inputs in the game using fingers

You are at the mercy of the default SteamVR bindings as to what exactly triggers the actions, I'm not sure if finger specific gestures are available.

Hopefully this answers your questions.

**Comment by marcob2178** [comment]
@username223 hi! 
The idea would be that I intermittently click the w or a or d or s buttons, and the In game character would move in all 4 directions. This is for the locomotion part

For the glove part, captoglove software allow to assign finger bending to key strokes. So the point would be have a certain key strokes bind to vive controllers 's buttons.

Would both be possible?

What version should I download to test both the features above?

Thanks!

**Comment by username223** [comment]
@marcob2178 
If you download [this](https://ci.appveyor.com/api/buildjobs/req3tpbjdeftq050/artifacts/installer%2FAdvancedSettings-3.1.0-dev%2Ba228cf0d-Installer.exe), VR bindings to keyboard keys is enabled. Download and install like you normally would.

There is a user guide [here](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/blob/master/docs/keyboard_input_guide.md). You might need to run Advanced Settings once in order for the config file to look like the one in the guide.

It's probably easier if you just download and then figure out if what you need to do works than having me guess whether or not it works. :)
