### ISSUE TITLE
Floor Fix causes to slide chaperone when pressing ''Undo'' (3.0.0)

### ISSUE THREAD

**Issue by DjBasA** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#140]
With version 3.0.0, when i press ''Fix Floor'' it fixes the floor correctly (i think), but when i press ''Undo'' to redo the fix to make sure it is properly aligned (I like to double check sometimes) the floor does go back to the height it was before, but it would also slide the center of the playspace slightly forward and slide the chaperone (and playspace) to (for me) the right, everytime i click ''Undo'' after first clicking ''Fix Floor'' it gets worse. (To the point that the chaperone was floating outside of me room through the window (i do vr in the attic), the ''center'' of my playspace was in my bed around that time (my bed is at the side of the playspace SteamVR wants you to face when playing Beat Saber (for example)).

I have gone back to OpenVR Advanced Settings v2.5 for now, since it doesn't have that problem until it's fixed. (i know thats a really old version, but the feature that matters to me the most (Floor Fix) atleast works in it.

**Comment by ykeara** [comment]
3.0.1 is out now should fix this issue... if your chaperone is unresponsive to the changes you may need to manually delete it and re set it up..... (C:\Program Files (x86)\Steam\config delete the .vrchap file in here.)


Closing Issue in ~24-48 hours if no issue/response.

**Comment by DjBasA** [comment]
i have already resetup my chaperone using roomsetup after this happened with 3.0.0, actually got a slightly better fitting chaperone for my room out of it too. (previous chaperone was slightly over my bed and desk, enough to notice, but wasn't so bothered by it, now the chaperone is (or seems to be) exactly the space available in my room.

i have a backup of the .vrchap file in my documents folder, just incase i have to ''restore'' it. (if the file doesn't fix after it has been screwed with again using 3.0.1's floor fix, i just run roomsetup again, which would be a shame cause of the pretty much perfect chaperone i have now, but oh well.

won't be able to test now, but will see if i can find some time tomorrow to test it.

**Comment by DjBasA** [comment]
doesn't seem to be happening anymore on 3.0.1.

**Comment by Kung-vr** [comment]
If you have a perfect room setup, you can also save it as a profile in the chaperone tab. Even if you run the Steamvr room setup again, you'll be able to restore your "perfect" chaperone tab profile room setup later. Using chaperone profiles to revert room setup is also the best way to "undo" a floor fix for now until the button is restored.

**Comment by ykeara** [comment]
Closing issue as it appears resolved
