### ISSUE TITLE
Space-turn teleports my chaperone 100 meters away now.. Proximity warnings stop working

### ISSUE THREAD

**Issue by Kentypoo** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#141]
I was using space turn in doom 3 BFG mod and was working great! then started playing "combat tested" and after a while the the map started moving on it's own slightly. trying to fix this I caused my chaperone to move like 100 meters away from me. I had to re-setup my room. Now every time I try to space turn my chaperone teleports 100 meters away. Also the Proximity warnings stopped working. at first they worked correctly until I used space turn. Now they don't activate at all.

**Comment by ykeara** [comment]
3.0.1 just got released it "should" resolve these issues

note:

I would suggest upgrading to this build, and if your chaperone is Bugged to delete it by going to 

C:\Program Files (x86)\Steam\config (or where your steam is installed) and deleting the "chaperone_info.vrchap" file this is the chaperone save, and will force you to re-run room set-up.... in some cases room-setup won't correctly fix the issue.


Leaving the issue open for a bit for visibility before closing it.

**Comment by ykeara** [comment]
Closing as Issue should have been resolved.
