### ISSUE TITLE
New version 'Motion' affects in game recenter keybind

### ISSUE THREAD

**Issue by g-coded** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#145]
I tried playing Project Cars 2 and my 'recenter view' keybind wasn't working.  I decided to try disabling the Motion Space Drag thinking maybe it wasn't allowing my playspace to change(wasn't using it at the time, however this didn't work.  I uninstalled OVRAS and the in game recenter worked fine, reinstalled OVRAS(in case it was a keybind/setting) and the in game was again broken.

**Comment by ykeara** [comment]
Hmm was this on 3.0.0 or 3.0.1? And was the re-center view keybind via project cars or elsewhere?

**Comment by g-coded** [comment]
3.0.1. This was using the in game(PC2) recenter view.

**Comment by ykeara** [comment]
Notified kung, he might know what the issue is, and I know he is planning on doing some re-works to how the chaperone is handled with motion.... which could be part of the issue.

**Comment by Kung-vr** [comment]
1. Can you confirm that [this](https://www.reddit.com/r/Vive/comments/4jcz2t/project_cars_for_vive_resetting_seated_position/) isn't your issue?
2. If that's not the issue, is there something that makes you think it's specifically the motion features of OVRAS 3.0 in particular causing this problem? You mentioned that enabling/disabling drag had no effect and that you weren't using it. Do you see it update center but then cancel that motion?
3. Have you tried rebinding the PC2 recenter key and the OVRAS bindings as well? If so what combinations did you use?
4. Can you check whether this issue happens with [OVRAS 2.8.0](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/releases/tag/v2.8.0) installed instead?

**Comment by g-coded** [comment]
1. Never had any issues using recenter view, I have a keybind to a button on my wheel and use it **all the time**
2. This issue wasn't present in the previous version of OVRAS I had(not sure which, had Recenter option with Fix Floor tab).  I'm not sure what it is in 3.0.1 that is causing this, but it is definitely OVRAS 3.  I first tried disabling the 'Motion', but didn't use the function within PC2.  I did notice when I tried it(SteamVR Home) my chaperone seemed 'off', I used the 'Recenter Space' and everything seems normal.
3. Yep, I initially thought my wheel inputs weren't working(this happens if you have custom keybinds enabled in Steam(non vr), so I tried rebinding to a keyboard input which updated the key in PC2 but did nothing.  I did try rebinding the Motion to a grip hold, but then switched back to default/uninstalled/reinstalled/uninstalled(can't play with it installed).
4. I will test 2.8, and report back

**Comment by ykeara** [comment]
Another possible thing Is to redo your chaperone by deleting the chaperone_info.vrchap in (C:\Program Files (x86)\Steam\config [by default])  and re-setting it up w/ room setup..... just a guess from my end... but possibly related.

**Comment by Kung-vr** [comment]
on point 1., just to confirm, you tried using the change camera key and cycled camera modes to confirm you weren't stuck in hud camera mode?

**Comment by Kung-vr** [comment]
Also on point 3., can you confirm if it's just the recenter bind on your wheel that stopped working? Or did all the binds stop working? OVRAS 3.0 uses the new steamvr input system which is similar to steam's flat mode custom binding system. Not many games/apps have native support yet for the new steamvr input system, so it's possible there's an incompatibility there with PC2. If that's the case you might have to stick with OVRAS 2.8 until PC2 can fix bindings incompatibility. (Would be able to tell if this is the issue if the binds stopped working altogether like when you use steam(non vr) custom binds)

**Comment by 2m** [comment]
I am running Samsung Odyssey+ and also noticed the same problem - reset HUD does not work anymore in iRacing and Assetto Corsa. Downgrading back to 2.8.0 fixes this.

Its only the recenter key that stopped working for me. I was able to cycle cameras just fine.

**Comment by g-coded** [comment]
> Also on point 3., can you confirm if it's just the recenter bind on your wheel that stopped working? Or did all the binds stop working? 
I did use the 'start' button on my wheel while using 3.0.1(which worked), I didn't try anything else as I was actually trying to play at the time.  However that being said, any issues with Steam(VR) input configs wouldn't affect the keyboard binding also not working.  
As I mentioned earlier, Steam's custom input(non vr) does 'break' the wheel input if you enable the controller type(XInput) even without creating a profile.  I am going to try a couple other games that have a 'recenter view' function(Dirt Rally/Subnautica) and see if there are issues there as well.

**Comment by ykeara** [comment]
Via reddit similiar issue via big-screen.

```Hey I ran into a new bug after the update. I think Advanced settings is messing up the seated orientation. When in Bigscreen it was placing me to be about a foot behind and below and rotated at a 30 degree angle of where I should be and no amount of resetting my orientation changed that. After I deleted Advanced Settings the problem was fixed. I didn't really extensively test more seated games or experiences, but I have a feeling a similar problem would occur with other seated games.```

**Comment by Kung-vr** [comment]
Do these games actually switch SteamVR into seated mode rather than just move the game origin? The motion settings don't support a universe calibrated in seated mode. But it should disable the options. Ok... this might be some progress. Seems I might need to make more extensive checks for a late switch into seated mode.

**Comment by Kung-vr** [comment]
One thing that would help is, if you go to the offsets page when the recenter isn't working, does it say standing universe? or what kind of universe does it say listed there (near the top)?

**Comment by g-coded** [comment]
I just tried using inputs on the wheel, and all inputs behave normally.

>Do these games actually switch SteamVR into seated mode rather than just move the game origin? The motion settings don't support a universe calibrated in seated mode.

Launching PC2 changes to seated mode.

**Comment by Kung-vr** [comment]
Ok, that explains pretty much everything... That's enough to get working on a fix. Thanks for the continued testing!

**Comment by g-coded** [comment]
Thanks Kung.  At first I thought I was the only one with the issue, will test the fix when it is ready.

**Comment by dgleyzer** [comment]
I can confirm the same thing happening to me with Odyssey+, my recenter key wasn't working. I also experienced seated apps appearing below the floor, even after using the floor fix.

**Comment by jdawgzim** [comment]
Same thing happens in Elite Dangerous and the Elite VR Cockpit mod.  F12 and the mod can't reset HMD view.  Also the chaperone wouldn't disappear which Elite Dangerous usually hides.  When I uninstalled OpenVR-Advanced-Settings my ability to reset the view returned and the chaperone would auto-hide..

**Comment by neoaptt** [comment]
I can confirm on Elite Dangerous that the HMD reset does not work unless i go into task manager and kill AdvancedSettings.exe application. Then it immediately works. It may be that the input emulator is overriding whatever API ED uses to reset the HMD. The older version without motion settings works just fine.

**Comment by DarkVamprism** [comment]
I'm not sure if this helps anyone but I have the setting enabled that shows me where the center of my room is(the square with the arrow) and when I use the space drag then it stays in place and doesn't follow me\chaperone at all.

**Comment by Kung-vr** [comment]
[Test build for anyone who would like try the new seated support.](https://ci.appveyor.com/project/icewind1991/openvr-advancedsettings/builds/23782191/job/mtnjtm1dh5j60ry1/artifacts) This implements recenter into our existing offsets feature. When you recenter your head's position and angle in the room will be applied to the offsets tab's offsets, centering you in the seated experience. From there you are still able to use all motion (drag/turn/gravity/etc...) features.

**Comment by ykeara** [comment]
PR 150 should address

**Comment by dantman** [comment]
> When you recenter your head's position and angle in the room will be applied to the offsets tab's offsets, centering you in the seated experience. From there you are still able to use all motion (drag/turn/gravity/etc...) features.

This worries me. I've recently found the seated position reset and playspace in standing mode to be unreliable. I have an overlay that works relative to the seated origin but can be started from home which has a standing origin. And while in standing mode the seated position reset does not always reliably reset to where it should be. Additionally my playspace rectangle moves to places it shouldn't be and I find offsets in OVAS when I don't want an offset standing playspace.

I thought this was a bug in my own code. Until I went to the trouble to place an overlay at 0,0,0 in the seated tracking space, confirming that my offset code is perfect and it's actually the seated origin that ends up in the wrong place when I tell SteamVR to reset it.

I'm going to have to uninstall OVAS, go to the trouble of resetting my playspace again, and testing SteamVR's native behaviour to confirm this is in fact OVAS messing up the SteamVR tracking spaces.

**Edit:** It seems this has been fixed in a newer version. Not the version that fixed this bug, but a more recent version.

**Comment by ykeara** [comment]
The bug got spread out and multiple attempts were attempted at putting it down........ at the end we had so many edge cases it was getting crazy.... turns out it was a bug on valve's end.... all the motion issues should be addressed as of 4.0.1.

**Comment by 2m** [comment]
I can confirm that the problems I was facing when recentering in iRacing are now fixed since 4.0.1.
