### ISSUE TITLE
[Request] Offset profiles

### ISSUE THREAD

**Issue by djesko1** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#149]
It would be handy to be able to set profiles of the playspace offset so that you can rotate and position quickly. Would also benefit MR streaming to get different camera angles quickly.

**Comment by ykeara** [comment]
Possibly It would be trivial at this stage, but we do need to finish addressing the movement bugs first.

**Comment by ykeara** [comment]
Just for clarification what exactly are you wanting? something similiar to the chaperone/audio/steamVR profiles? or a setting via action/keybind?

**Comment by djesko1** [comment]
The profiles would just set the playspace position and rotation. Having to slide or edit the values each time takes too long say of you are doing MR live and want to show different angles.

**Comment by ykeara** [comment]
It's planned now... will still be a while for implementation.

**Comment by djesko1** [comment]
That's great. Looking forward to it once it's ready. Will then start some nice streams.
