### ISSUE TITLE
Moving Play Space, is working?

### ISSUE THREAD

**Issue by Tux0Topo** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#15]
Hi!! In the Play Space Page, i can see coordinates and rotation. When using rotation, it does nothing :(
And using Virtual Move Shortcut, changes the coordinates, on the window, but none of them translates to any movement in the virtual world. In the original Advanced-Setting, the coordinate and rotation changing used to work, but beeing a while since try it again.
I´m on SteamVR Beta, with a Windows Mixed Reality headset, and Windows 10 build 1809.

Happy new year!!

**Comment by icewind1991** [comment]
moving at least is still working for me

**Comment by ykeara** [comment]
@Tux0Topo is your tracking space "roomscale" or "standing-only"

Change it to room-scale and try again if you are in standing only.

Possible bug with standing only (not sure if its by design or bug)

**Comment by ykeara** [comment]
Issue Outdated for 3.0.0, and no response to replicate issue. If issue still persists (after 3.0.0) please re-open an issue.
