### ISSUE TITLE
certain ui elements aren't scaled correctly

### ISSUE THREAD

**Issue by AtleSt** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#151]
for me the ui isn't looking like it should, i haven't seen this anywhere else and i don't know how to fix it
![20190411_215517_MixedReality](https://user-images.githubusercontent.com/41252329/55988750-fd905f80-5ca4-11e9-9186-e6f82b29a43f.jpg)

**Comment by AtleSt** [comment]
also some settings are out of reach because of this bug

**Comment by ykeara** [comment]
That is 100% a new one.

What HMD are you using?
What OS?
Do you have any accessibility features on that change text size etc?

Also Try to completely uninstall (run un-installer + delete the folder in program files).

Also might try a different version and see if issue persists.

**Comment by AtleSt** [comment]
i found the problem, its windows 10 text and application scaling.
i usually have it at 150% so that i can actually use my 4k display, when i put it back to 100% the problem got fixed but now everything is tiny on my display.
ill see if i find a way around this issue

**Comment by AtleSt** [comment]
i fixed it by overriding high dpi scaling on steamvr executables
thanks for the help

**Comment by ykeara** [comment]
closing
