### ISSUE TITLE
Unable to map Motion settings via Steam Input

### ISSUE THREAD

**Issue by bubbabushido** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#155]
I've read the new documentation, but I am unable to map Motion settings via Steam Input. There are simply no options which correspond to the commands listed in the Motion section.

I really need this functionality, I am disabled and trying to use the height toggle as a push to crouch feature.

Please help me.

I am on a Samsung Odyssey+, running version 3.0.1, I am not opted in to any betas.

**Comment by ykeara** [comment]
It should just be height toggle in the binding UI, post a screenshot of you still have an issue.

**Comment by bubbabushido** [comment]
There is no height toggle option in the binding UI, I am unable to capture screenshots of the Steam Input UI. I press the mapped buttons, the image displays on my screen, but they are not saved to my system in any of the temp or steam userdata folders.

**Comment by bubbabushido** [comment]
I am shown prompts for all kinds of button/value entries, but height toggle is not one of the options.

There are no options related to Advanced Settings at all.

**Comment by ykeara** [comment]
Make sure you are on the advanced settings application it will be at the bottom of the list you can go to http://127.0.0.1:8998/dashboard/controllerbinding.html instead of doing it inside of VR for ease of use. Stream VR needs to be running to access it.

**Comment by bubbabushido** [comment]
I was trying to map the setting on the game i was currently playing. I have now changed the setting in the advanced settings binding menu and it works perfectly. Thank you for your help. Thank you for the program.
