### ISSUE TITLE
(Pre-release) 3.1.0 RC1

### ISSUE THREAD

**Issue by Kung-vr** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#158]
Anyone who would like to test the pre-release of Advanced Settings 3.1.0 can find a [download link here.](https://ci.appveyor.com/project/icewind1991/openvr-advancedsettings/builds/23909093/job/bte24i6smhin966b/artifacts)

If you discover any problem, *please open a separate issue describing your problem.*

If everything works, we want to know that too. Please reply to this post with your HMD type and if possible describe what you tested as working. We are especially **interested in test results from WMR/Rift/Pimax** users.

If you want to go the extra mile and do some targeted testing we are interested in results from:
```Seated position resets in seated games
- Re-running room-setup
- Chaperone Warnings (following movement)
- brightness Feature (save state between/sessions and working with different HMD's)
- desktop feature (making sure it works/saves appropriately)
- The Enrichment Center once again reminds you that
   prolonged exposure to VR is not part of this test.
```

Current 3.1.0 patch notes are below:
___

**New Features:**

- Brightness Adjustment: Finely control your brightness now! (Found in new "Video" tab) - [Ykeara](https://github.com/ykeara)
- Desktop Adjustment: Shift Desktop View Left/Right/Up/Down/Closer/Further, and save that state (easier to use desktop overlay). - [username223](https://github.com/username223)
- New "Seated Recenter" button now visible in Offsets tab when in seated mode applications. - [Kung](https://github.com/Kung-vr)
- Add Ctrl-C and Ctrl-V keyboard shortcuts to the Utilities tab. - [Kung](https://github.com/Kung-vr)
- “Allow External App Chaperone Edits” checkbox (in settings tab) applies adjustments to the chaperone from external sources (only when offsets are zeroed). - [Kung](https://github.com/Kung-vr)

**Bug Fixes:**

- Fixed an issue that prevented new room setup from applying. - [Kung](https://github.com/Kung-vr)
- Add motion support for seated universe mode. - [Kung](https://github.com/Kung-vr)
- Fixed an issue where chaperone warnings (haptics etc..) didn’t respect offsets. - [Kung](https://github.com/Kung-vr)
- Fixed case where error reporting would cause crashing on startup. - [username223](https://github.com/username223)
- Fixed an Issue causing WMR/Rift to snap back to reset position when using motion. (3.0.1) - [Kung](https://github.com/Kung-vr)
- Disabled Space Fix tab's "Undo" Feature (pending integration into new motion system) (3.0.1) - [Kung](https://github.com/Kung-vr)
- Disabled Chaperone Height Slider (pending integration into new motion system) (3.0.1) - [Kung](https://github.com/Kung-vr)
- Fix offset for knuckles/wands not being applied on floor fix. (3.0.1) - [Ykeara](https://github.com/ykeara)

**Miscellaneous:**
 - Updated OpenVR libraries to version 1.3.22.

**Comment by ykeara** [comment]
3.1.0 release so closed
