### ISSUE TITLE
Pimax not showing reprojected frames / dropped frames

### ISSUE THREAD

**Issue by leppermessiah1** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#159]
I seem to remember this used to work with Pimax in a past release, but now I just get zeros for those, even when I'm definitely getting reprojected/dropped frames.

**Comment by ykeara** [comment]
My guess Is its on pimax's end, but I will contact them and see If I can't figure out some stuff.

**Comment by ykeara** [comment]
Also what version of PiTool are you using?

**Comment by leppermessiah1** [comment]
I was on PiTool .91 and I just updated to 1.0.1.121. I had the same issue on both.

**Comment by ykeara** [comment]
kk I will get back to this as soon as pimax gets back to me.

**Comment by ykeara** [comment]
I am going to close out this issue as It just appears to be on the Pimax end, their driver (essentially pi-tool) just does not appear to be properly populating it. and there is not really a work-around we can do  from the OpenVR end. (besides llogging everything ourselves which would be an un-acceptable performance hit.)
