### ISSUE TITLE
Reset headset not working after install in multiple games

### ISSUE THREAD

**Issue by gisenYagyu** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#162]
After installing this, I am unable to reset my headset centre position in games that have this feature.
Tried in DCS world, Project Cars, Project cars 2. 
Uninstall and works, install again and doesnt work.

**Comment by ykeara** [comment]
Known Issues its being resolved in 3.1.0 you can try the Release Canidate version here: https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/issues/158

Other than that you might have to wait a few days we are waiting  for some final testing before we do the release.

**Comment by ykeara** [comment]
Assuming Resolved closing.
