### ISSUE TITLE
Games won't launch with Advanced Settings installed

### ISSUE THREAD

**Issue by Jackal1810** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#169]
It's pretty easy to reproduce, I've been able to do this on a clean format as well. I've installed Advanced Settings to the same drive, separate drive and doing the same for Steam. No matter what I do after the first system restart it prevents me from launching any game.  

The only thing I can launch without issue is SteamVR / Home. All games after that refuse to open until I close SteamVR. 

Once I remove Advanced Settings it works without issues.

**Comment by ykeara** [comment]
HMD? OS?

Also if you can get us your log file at %appdata%/AdvancedSettings-Team (on windows)

And also the log file for your vrserver... this is in your steam install directory (default: C:\Program Files (x86)\Steam\logs\vrserver.txt)

**Comment by ykeara** [comment]
Closing Issue Presumably resolved no response.
