### ISSUE TITLE
(Playspace resets after motion on Oculus Rift #133) is back

### ISSUE THREAD

**Issue by cubiclestorm** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#171]
please see previous issue "Playspace resets after motion on Oculus Rift"
It has returned with ver. 3.1

**Comment by Kung-vr** [comment]
What's your HMD, OS, Steamvr version? Also can you paste a logfile pastebin please? Logfile is at C:\Users\Username\AppData\Roaming\AdvancedSettings-Team\AdvancedSettings.log on windows.

**Comment by cubiclestorm** [comment]
HMD: Oculus Rift
OS: Win 10 pro
SteamVR: 1.3.23

Log:
[INFO] 2019-04-20 20:17:44: Application started (Version v3.0.1)
[INFO] 2019-04-20 20:17:44: Log File: C:/Users/XXXX/AppData/Roaming/AdvancedSettings-Team/AdvancedSettings.log
[INFO] 2019-04-20 20:17:44: Command line arguments processed.
[INFO] 2019-04-20 20:17:44: OpenVR initialized successfully.
[INFO] 2019-04-20 20:17:44: Settings File: C:/Users/XXXX/AppData/Roaming/AdvancedSettings-Team/OpenVRAdvancedSettings.ini
[INFO] 2019-04-20 20:17:44: VR Runtime Path: C:/Program Files (x86)/Steam/steamapps/common/SteamVR
[INFO] 2019-04-20 20:17:46: Found overlay "valve.steam.desktop".
[INFO] 2019-04-20 20:17:47: Creating battery overlay for device 6
[INFO] 2019-04-20 20:17:47: Created battery overlay for device 6
[WARNING] 2019-04-20 20:17:52: Attempting to Reloading Chaperone Data
[INFO] 2019-04-20 20:18:53: Received quit request.
[INFO] 2019-04-20 20:18:53: All systems exited.
[INFO] 2019-04-20 20:19:18: Application started (Version v3.0.1)
[INFO] 2019-04-20 20:19:18: Log File: C:/Users/XXXX/AppData/Roaming/AdvancedSettings-Team/AdvancedSettings.log
[INFO] 2019-04-20 20:19:18: Forcing removal of applications manifest.
[INFO] 2019-04-20 20:19:18: Command line arguments processed.
[INFO] 2019-04-20 20:19:18: OpenVR initialized successfully.
[INFO] 2019-04-20 20:19:18: Manifest removed.
[INFO] 2019-04-20 20:19:20: Application started (Version v3.1.0)
[INFO] 2019-04-20 20:19:20: Log File: C:/Users/XXXX/AppData/Roaming/AdvancedSettings-Team/AdvancedSettings.log
[INFO] 2019-04-20 20:19:20: Forcing install of applications manifest.
[INFO] 2019-04-20 20:19:20: Command line arguments processed.
[INFO] 2019-04-20 20:19:20: OpenVR initialized successfully.
[INFO] 2019-04-20 20:19:20: Manifest reinstalled.
[INFO] 2019-04-20 20:20:00: Application started (Version v3.1.0)
[INFO] 2019-04-20 20:20:00: Log File: C:/Users/XXXX/AppData/Roaming/AdvancedSettings-Team/AdvancedSettings.log
[INFO] 2019-04-20 20:20:00: Command line arguments processed.
[INFO] 2019-04-20 20:20:00: OpenVR initialized successfully.
[INFO] 2019-04-20 20:20:00: Settings File: C:/Users/XXXX/AppData/Roaming/AdvancedSettings-Team/OpenVRAdvancedSettings.ini
[INFO] 2019-04-20 20:20:00: C:/Users/XXXX/AppData/Roaming/AdvancedSettings-Team/OpenVRAdvancedSettings.ini
[INFO] 2019-04-20 20:20:00: VR Runtime Path: C:/Program Files (x86)/Steam/steamapps/common/SteamVR
[INFO] 2019-04-20 20:20:01: SUCCESS: Chaperone Data Updated and Offsets zeroed out
[INFO] 2019-04-20 20:20:02: Creating battery overlay for device 6
[INFO] 2019-04-20 20:20:02: Created battery overlay for device 6
[INFO] 2019-04-20 20:20:53: Received quit request.
[INFO] 2019-04-20 20:20:53: All systems exited.

**Comment by Kung-vr** [comment]
Thanks! Could you give [this build](https://ci.appveyor.com/project/icewind1991/openvr-advancedsettings/builds/23998008/job/61fgwyd3b6bq7kje/artifacts) a try, and enable the "Old-Style Motion" option in the settings tab?

**Comment by pearce31** [comment]
Can confirm I have same issue
WMR
Win 10 latest updates
1.3.23

Log:
https://www.dropbox.com/s/hb3sa925aj5q4pz/AdvancedSettings.log?dl=0

I gave the version you just posted a try and when I enable the old option in settings nothing happens when I press buttons no response. Upon unchecking the old option it responds again. But main issue remains

**Comment by cubiclestorm** [comment]
> Thanks! Could you give [this build](https://ci.appveyor.com/project/icewind1991/openvr-advancedsettings/builds/23998436/job/pdsb8qa6fo7mc1v6/artifacts) a try, and enable the "Old-Style Motion" option in the settings tab?

same issue

[INFO] 2019-04-21 18:59:06: Application started (Version 3.1.0-dev+129a9a0c)
[INFO] 2019-04-21 18:59:06: Log File: C:/Users/XXXX/AppData/Roaming/AdvancedSettings-Team/AdvancedSettings.log
[INFO] 2019-04-21 18:59:06: Command line arguments processed.
[INFO] 2019-04-21 18:59:06: OpenVR initialized successfully.
[INFO] 2019-04-21 18:59:06: Settings File: C:/Users/XXXX/AppData/Roaming/AdvancedSettings-Team/OpenVRAdvancedSettings.ini
[INFO] 2019-04-21 18:59:06: C:/Users/XXXX/AppData/Roaming/AdvancedSettings-Team/OpenVRAdvancedSettings.ini
[INFO] 2019-04-21 18:59:06: VR Runtime Path: C:/Program Files (x86)/Steam/steamapps/common/SteamVR
[INFO] 2019-04-21 18:59:07: CHANGED SETTINGS: Left Hand Space-Turn Bind Enable Set: 0
[INFO] 2019-04-21 18:59:07: CHANGED SETTINGS: Allow External Edits Set: 0
[INFO] 2019-04-21 18:59:07: CHANGED SETTINGS: Old-Style Motion Set: 0
[INFO] 2019-04-21 18:59:08: SUCCESS: Chaperone Data Updated and Offsets zeroed out
[INFO] 2019-04-21 18:59:08: LOADED SETTINGS: Right Hand Space-Drag Bind Enabled
[INFO] 2019-04-21 18:59:08: LOADED SETTINGS: Left Hand Space-Drag Bind Enabled
[INFO] 2019-04-21 18:59:08: LOADED SETTINGS: Right Hand Space-Turn Bind Enabled
[INFO] 2019-04-21 18:59:08: Creating battery overlay for device 6
[INFO] 2019-04-21 18:59:08: Created battery overlay for device 6
[INFO] 2019-04-21 18:59:39: CHANGED SETTINGS: Old-Style Motion Set: 1
[INFO] 2019-04-21 18:59:58: Received quit request.
[INFO] 2019-04-21 18:59:58: All systems exited.
[INFO] 2019-04-21 19:00:11: Application started (Version 3.1.0-dev+129a9a0c)
[INFO] 2019-04-21 19:00:11: Log File: C:/Users/XXXX/AppData/Roaming/AdvancedSettings-Team/AdvancedSettings.log
[INFO] 2019-04-21 19:00:11: Command line arguments processed.
[INFO] 2019-04-21 19:00:11: OpenVR initialized successfully.
[INFO] 2019-04-21 19:00:11: Settings File: C:/Users/XXXX/AppData/Roaming/AdvancedSettings-Team/OpenVRAdvancedSettings.ini
[INFO] 2019-04-21 19:00:11: C:/Users/XXXX/AppData/Roaming/AdvancedSettings-Team/OpenVRAdvancedSettings.ini
[INFO] 2019-04-21 19:00:11: VR Runtime Path: C:/Program Files (x86)/Steam/steamapps/common/SteamVR
[INFO] 2019-04-21 19:00:12: CHANGED SETTINGS: Left Hand Space-Turn Bind Enable Set: 0
[INFO] 2019-04-21 19:00:12: CHANGED SETTINGS: Allow External Edits Set: 0
[INFO] 2019-04-21 19:00:12: SUCCESS: Chaperone Data Updated and Offsets zeroed out
[INFO] 2019-04-21 19:00:12: LOADED SETTINGS: Right Hand Space-Drag Bind Enabled
[INFO] 2019-04-21 19:00:12: LOADED SETTINGS: Left Hand Space-Drag Bind Enabled
[INFO] 2019-04-21 19:00:12: LOADED SETTINGS: Right Hand Space-Turn Bind Enabled
[INFO] 2019-04-21 19:00:12: LOADED SETTINGS: Old-Style Motion Enabled
[INFO] 2019-04-21 19:00:12: Creating battery overlay for device 6
[INFO] 2019-04-21 19:00:12: Created battery overlay for device 6
[INFO] 2019-04-21 19:00:13: Creating battery overlay for device 8
[INFO] 2019-04-21 19:00:13: Created battery overlay for device 8
[INFO] 2019-04-21 19:00:21: Updating battery overlay for device 8 to 4(0.72)163208757285
[INFO] 2019-04-21 19:00:33: Received quit request.
[INFO] 2019-04-21 19:00:33: All systems exited.
[INFO] 2019-04-21 19:00:49: Application started (Version 3.1.0-dev+129a9a0c)
[INFO] 2019-04-21 19:00:49: Log File: C:/Users/XXXX/AppData/Roaming/AdvancedSettings-Team/AdvancedSettings.log
[INFO] 2019-04-21 19:00:49: Forcing removal of applications manifest.
[INFO] 2019-04-21 19:00:49: Command line arguments processed.
[INFO] 2019-04-21 19:00:49: OpenVR initialized successfully.
[INFO] 2019-04-21 19:00:49: Manifest removed.
[INFO] 2019-04-21 19:00:51: Application started (Version v3.0.1)
[INFO] 2019-04-21 19:00:51: Log File: C:/Users/XXXX/AppData/Roaming/AdvancedSettings-Team/AdvancedSettings.log
[INFO] 2019-04-21 19:00:51: Forcing install of applications manifest.
[INFO] 2019-04-21 19:00:51: Command line arguments processed.
[INFO] 2019-04-21 19:00:51: OpenVR initialized successfully.
[INFO] 2019-04-21 19:00:51: Manifest reinstalled.

**Comment by ykeara** [comment]
@cubiclestorm @pearce31 To clarify are you having issues using the offsets page or motion controls? Just tested myself on essentially 3.1.0 and drag space and such worked flawlessley, but manually setting offsets did NOT work. or specifically only the y offset did not work.... the others appeared to take just fine.

**Comment by pearce31** [comment]
Motion controls

**Comment by ykeara** [comment]
Do you have any other overlay programs like Input Emulator? space/cal installed?

**Comment by pearce31** [comment]
I reinstalled steam and was messing around with input emulator, play space mover and driver4vr. But I cant remember if that was before I reinstalled steam or after. But I did not have input emulator installed the same time as advanced settings I remember deleting it before I installed advanced settings and I cant remember if I had driver4vr installed at same time.

**Comment by ykeara** [comment]
hmm I would check if `activateMultipleDrivers: true` is set in the vr settings file (steam\config\steamvr.vrsettings)

**Comment by ykeara** [comment]
OKAY current work-around:

1. Run WMR set-up for "all experiences"
2. Make sure bounds is set to on Before launching SteamVR (you can set it to off once steamVR has launched)
3. things should just work.


@cubiclestorm in regards to rift.

I am not familiar with the set-up but I assume its something very similiar i.e. make sure you set-up your rift for moving experiences not just sitting/standing.... or at least try it.

**Comment by cubiclestorm** [comment]
I'm always setup that way

**Comment by ykeara** [comment]
@cubiclestorm 
Is your playspace at least 1.5m x 2m? does the issue still persist? and did 2.8.0 use to work?

You can also try newest dev build https://ci.appveyor.com/project/icewind1991/openvr-advancedsettings/builds/24262788/job/9w6k8tk25nd9489e/artifacts here and we have a button in settings to enable legacy motion or something along those lines please try that if not.

**Comment by cubiclestorm** [comment]
> @cubiclestorm
> Is your playspace at least 1.5m x 2m? does the issue still persist? and did 2.8.0 use to work?
> 
> You can also try newest dev build https://ci.appveyor.com/project/icewind1991/openvr-advancedsettings/builds/24262788/job/9w6k8tk25nd9489e/artifacts here and we have a button in settings to enable legacy motion or something along those lines please try that if not.

still the same bug. this bug first showed up in ver 3 and was fixed in 3.0.1 an returned in this latest version. My playspace is 2.8m x 2.8m

**Comment by cubiclestorm** [comment]
issue resolved after latest steamvr update
