### ISSUE TITLE
space drag

### ISSUE THREAD

**Issue by YorxVR** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#172]
cant move up and down, only rotate

**Comment by Kung-vr** [comment]
HMD, OS, Steamvr version, and logfile pastebin please. Logfile is at C:\Users\Username\AppData\Roaming\AdvancedSettings-Team\AdvancedSettings.log on windows.

**Comment by Kung-vr** [comment]
On second thought, this could be a bindings issue maybe, since rotation still works. The default bind for space drag is a double click on the menu button (on vive). This is assuming that hand's drag ability has been enabled via the checkbox in the motion tab.

**Comment by YorxVR** [comment]
> On second thought, this could be a bindings issue maybe, since rotation still works. The default bind for space drag is a double click on the menu button (on vive). This is assuming that hand's drag ability has been enabled via the checkbox in the motion tab.

you were correct, thanks. i thought i tried that, im coming from ver 2.7 so i didn't know the bind changed.
