### ISSUE TITLE
Chaperone tab, "Attempting to Reloading Chaperone Data" spam, and graceful handling.

### ISSUE THREAD

**Issue by ykeara** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#178]
Need to look into this a bit more, but upon seeing the logs of WMR users it appears as if some calls are being unnecessarily repeatedly called.

will look into fixing calls OR disabling for non-LH systems.

**Comment by Kung-vr** [comment]
I think the only way for up/down movement to "lose tracking" as per #170 is from constant calling of seated recenter, maybe even per-frame calling...

**Comment by ykeara** [comment]
made this issue in regards to the "reloading chaperone bounds" calls..... several of the WMR logs have it spammed for several minutes at its ~5 second interval.... Need to investigate this but I assume that its just an api issue, and I should disallow WMR/RIFT from accessing that part of code. so not really the up-down stuff but the log calls for chaperone warnings.

**Comment by ykeara** [comment]
Actually it appears the "Attempting to Reloading Chaperone Data" is affected by something to do with motion even on Vive..... at any rate log and function need to get cleaned up there. needs to change I don't know what exact solution is without doing some playing....

**Comment by ykeara** [comment]
Going to investigate as an Issue of seated WMR experience.....

**Comment by ykeara** [comment]
Possibly Addressed in #298 waiting for more data.

**Comment by ykeara** [comment]
Still appears to be an issue at least w/ non LH based headsets.

**Comment by ykeara** [comment]
I'm un-able to replicate with native HMD's so this issue might be related to external chaperone imports.

**Comment by ykeara** [comment]
Should Be removed a while ago closing
