### ISSUE TITLE
Create Center marker overlay? so it will move w/ player when using motion key-binds.

### ISSUE THREAD

**Issue by JoeMBlair** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#180]
Whenever I use space move or space turn the center marker doesn't move with the chaperone bounds. So the more I move the further away it gets.

**Comment by ykeara** [comment]
hmm Its probably time to recreate this tbh

**Comment by JoeMBlair** [comment]
Also jus realise it affects the play space bounds if that's enabled.

**Comment by ykeara** [comment]
Yea we won't be touching the play area bounds. but Do plan to get this added at some point
