### ISSUE TITLE
Show chaperone while using space turn. 

### ISSUE THREAD

**Issue by JoeMBlair** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#183]
I think a good enhancement would to have an option to bring up the chaperone or play space bounds while space turn is activated. So it's easier to re-orientate yourself moving around.

**Comment by ykeara** [comment]
Like the Idea, fairly simple to do.... will look into and talk about it... only real issue against it is space considerations in UI.

**Comment by ykeara** [comment]
Planned for implementation.
