### ISSUE TITLE
[Suggestion] Allow Vive wand system buttons to be rebindable as well.

### ISSUE THREAD

**Issue by Viperlotus** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#188]
Hello, everyone.  I've been using this version of Advanced Settings and I really like it so far.  However, there is one thing I really want to be able to do with it that I can't yet; rebind one of the system buttons (at the bottom) of either of my Vive wands to toggle my microphone on and off.

First, I should specify that this is already technically possible to do by editing the bindings for VR Compositor.  I've already tried doing things that way, but the problem with that method is that there is no icon or any other indicator when my microphone is open, so I'm afraid of losing track of when my mic is open or closed.  However, Advanced Settings doesn't even let me select a system button as an option to be rebound.

Please add this functionality to the program.  It would resolve my voice communication issues with VR almost perfectly if you do.

**Comment by ykeara** [comment]
We don't really  control which buttons can/cannot be bound (that is done by steam) BUT via newest beta 1.4.5 looks like the issue has been resolved (https://i.imgur.com/cTL4IG7.png)

And ofc you can set it to toggle rather than just press to keep open/closed (enable/disable) your mic.
