### ISSUE TITLE
Chaperone Fades from Desired Visibility while active.

### ISSUE THREAD

**Issue by Kentypoo** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#189]
I use to love this feature but I love 3.1 better. I use to wish it would remember I checked the box to force show my chaperone because every time I started vr I had to go into the advanced settings and recheck this box. Now checking the box works for a few seconds then it dims. the bounds are still forced but not 100% opaque after a few seconds. I force the floor bounds with the normal settings and turn the visible distance all the way up in the advanced settings but I like to run in my space and if I can't see my chaperone good I am more tentative. the chaperone isn't on 100 percent  even when I am right next to it anymore..

**Comment by ykeara** [comment]
mmk I'll look into the save states I know that its kinda split because of profiles.... I will probably change it so all Settings "save" (unless it doesn't make sense) and save them as well... so it needs to be looked at.

And yea I will look at the "forced on" it should be based on the settings its opacity and such... so something weird is happening I will end up looking into it.

**Comment by Kentypoo** [comment]
thanks for looking into it! I am still loving that space turn redirected walking. I wish all games were compatible with it. I posted on Pavlov the other day that I wanted support for it. thanks again.

**Comment by ykeara** [comment]
It should be compatible with all games, will have to play w/ pavlov to see why it doesn't like it... but it might be an anti-cheating measure will have to mess with that too.

**Comment by ykeara** [comment]
In regards to the chaperone fading, It appears this is the behavior of Steam/OpenVR I opened an issue https://github.com/ValveSoftware/openvr/issues/1110

**Comment by ykeara** [comment]
Yea unfortunately there is a timeout now.... after 2-5 seconds of the chaperone being active it starts to lose opacity by some amount...  This appears to be design.

**Comment by Kentypoo** [comment]
i see. I was going to say it seems like a Steam update that did it..  thanks for looking into it.. I don't like that change from Steam... I run in my garage and this steam update makes it harder to do that. Steam needs to make the chaperone change colors to contrast the colors in your game so you can see your chaperone better.  They need to make it visible sooner as well, thank goodness we have Advanced settings from you guys. Space turn works in all games , but I can break games by using redirected walking and then dying and re-spawning correctly is often broke. this can normally be fixed by the recenter space button in advanced settings. but sometimes this causes me to be below the map or above it.  I don't think you can do anything about games not supporting it 100 percent.  thanks again..

**Comment by ykeara** [comment]
yea when you use the re-directed walking etc.  the game pretty much thinks you just have a REALLY big playspace.... so it can do some strange things.. and yea not much we can do... Yea The behavior imo should be something opened to API so hopefully they add us keys... going to leave Issue open for a bit in hopes something gets added on their end though may end closing it as nothing we can really do...

I will try one thing See If I can't make a call to turn on/off force chaperone on the same frame... and see the behavior that generates if that doesn't work though I will probably just close issue. as nothing else can be done really until valve does something.

**Comment by JoeMBlair** [comment]
It's not related to the issue but instead of using recenter space, you should go to the offset tab and just reset that, you shouldn't have issues spawning under the map then.

**Comment by ykeara** [comment]
Currently It appears to be  desired SteamVR behavior... would love the option, but for now stuck w/

**Comment by ykeara** [comment]
based on some other issues w/ per frame calls to api it is very unlikely that a work-around would be Stable from a performance perspective, going to close issue out until Valve re-adds (or changes) behavior of Chaperone.
