### ISSUE TITLE
Color Correction overlay for Video Tab

### ISSUE THREAD

**Issue by deinlandel** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#190]
Your new brightness setting is awesome. As I understand, it uses overlay to darken the image. It would be great to have a similar instrument, but with custom colored overlay. To fix excessively warm or cold colors, for example.

**Comment by ykeara** [comment]
Yep that has been the plan a White overlay w/ RGB color slider, It just didn't make it in for 3.1.0 and I have been closing bugs fixing some other issues since then.
