### ISSUE TITLE
Add motion cancellation

### ISSUE THREAD

**Issue by iamisti** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#191]
Please add motion cancellation feature! Very very important and more and more people needs it!

Basically the same as: https://github.com/matzman666/OpenVR-InputEmulator 'motion cancellation' section.

**Comment by iamisti** [comment]
anyone? :D

**Comment by ykeara** [comment]
In general motion cancellation is not really do-able for this project... I have been thinking about it but its really outside scope of this project as only feasible way is to really do with our set-up.

**Comment by ykeara** [comment]
Relevant Forum thread https://www.xsimulator.net/community/threads/open-vr-coder-needed-please-help.13226/

and input emulator is currently the better project. for this. Closing out comment.
