### ISSUE TITLE
Clarify Enable Motion Smoothing

### ISSUE THREAD

**Issue by e00E** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#193]
The current description of this setting in the readme is

> Enable Motion Smoothing: Enables Motion Smoothing, and disables asynchronous reprojection.

However, on my machine SteamVR Settings tell me
> Motion Smoothing Unavailable

> Motion Smoothing is not supported on this gpu or drivers are out of date.

Does this mean that the Advanced Settings works even though motion smoothing is unavailable or that it has no effect? This should be answered in the documentation. In the latter case this should be displayed to the user.

**Comment by ykeara** [comment]
Yea It can be clarified, doubt we will change the behavior...

AMD cards do not work currently w/ motion smoothing (apparently it works for vega w/ some tweaks in settings)... My guess is it will just error out in logs, and it won't apply don't know w/o trying though.

**Comment by ykeara** [comment]
SteamVR Beta now has 1.4.8 w/ motion smoothing support for AMD cards, therefore should work w/ everything. closing issue.
