### ISSUE TITLE
Application Supersampling only takes effect when application is restarted

### ISSUE THREAD

**Issue by e00E** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#194]
I am not sure if this is a bug or expected. If it is expected it should be clarified in the documentation.

I have tested this with the SteamVR Home application. If I change the supersampling setting to something extreme (like 20% versus 200% so it is clearly noticable) then it only gets applied when switch applications, but I do not seem to have to restart the whole SteamVR.

**Comment by ykeara** [comment]
Behavior can vary app-> app and between systems, again clarification should be added, but not really any way to change the behavior.

**Comment by ykeara** [comment]
Will make sure restart button is re-added if not and update documentation etc.
