### ISSUE TITLE
Disable Vive Pro microphone in Room View

### ISSUE THREAD

**Issue by limited660** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#2]
Is it possible to get an option to disable the microphone when entering Room View on the Vive Pro? Currently when you switch to Room View, it provides a very high level of side tone to the headphones which is quite annoying and can be very loud due to breathing or touching the headset.

**Comment by ykeara** [comment]
Can you test if the PTT feature works while in this mode?
Does muting the Mic in audio Tab/windows mute it when you are in this mode?

**Comment by limited660** [comment]
Well I haven't been able to get my camera to work again since reinstalling Windows so I'm afraid I can't test this right now.

**Comment by ykeara** [comment]
That is fine waiting for more reports/clarification on what exactly is happening, before able to do anything about it.

**Comment by limited660** [comment]
The camera started working and I did some tests with the mute button on the right earpiece. With the mic muted using the button and confirmed with fpsVR I still get sound during room view. I'll try some other things tonight like using Windows to mute and the PTT.

**Comment by ykeara** [comment]
Yea seeming more and more likely that its a hardware/firmware issue with vive-pro... not much we can do with that.
