### ISSUE TITLE
Flip orientation configurable amount

### ISSUE THREAD

**Issue by horst789github** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#200]
can you please a button for:

flip orientation in 90° degrees left
flip orientation in 90° degrees right

**Comment by ykeara** [comment]
Functionality already Exists w/ snap turn left and right set at 90 degrees.

**Comment by horst789github** [comment]
where i can find this? i only found "flip orientation" whis make a 180° change

**Comment by ykeara** [comment]
What is the use case? do you want to turn in games or change your chaperone?

**Comment by ykeara** [comment]
IF you want to rotate yourself in a game i.e. "turn" you can set snap turn angle in the Motion tab and bind it via key-bind.... if you want something more permanent then yes this should be visited... I need to play around w/ a few things... but rotate in motion w/o chaperone adjust should do the same thing already.

**Comment by horst789github** [comment]
yes i want this permanent (like the "flip orientation" button)
