### ISSUE TITLE
desktop overlay function dont work

### ISSUE THREAD

**Issue by horst789github** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#201]
desktop overlay function dont work,

if i make changes on the slide nothing happends... i switch do desktop overlay and all is default > switch to desktop overlay settings make some changes and switch to desktop overlay and nothing changed...

**Comment by ykeara** [comment]
As per the words at the top. you will need to close the overlay and re-open it and then it should have applied.

**Comment by horst789github** [comment]
i read the words at the top and i close the overlay and reopen (as i write) but nothing works

**Comment by ykeara** [comment]
What Headset are you using? Version of SteamVR?

To be Clear while our settings save if you restart SteamVR you will have to open Dashboard-> close -> open for the changes to be applied on restart, and After making a change you will have to ->close-> open dashboard for changes to apply.

also if in SteamVR you could go to Developer->overlayViewer

find valve.steam.desktop and verify that it exists would be helpful.

**Comment by horst789github** [comment]
Pimax 5k+ with PiTool 1.0.1.129 and SteamVR beta 1.4.15

**Comment by ykeara** [comment]
can you got to in SteamVR overlay go to  Developer->overlay Viewer and give me a screenshot/list of all the Overlays?

**Comment by horst789github** [comment]
![grafik](https://user-images.githubusercontent.com/35397597/57973090-9a7ca180-79a3-11e9-810a-b737b6b8160b.png)

**Comment by ykeara** [comment]
Looks like it might be on Pimax's end, if you can post a pastebin of your log (%appdata%\AdvancedSettings-Team\advancedsettings.txt) it would be helpful other than that I will put it on hold.

**Comment by horst789github** [comment]
[INFO] 2019-05-18 12:12:56: Application started (Version v3.1.0)
[INFO] 2019-05-18 12:12:56: Log File: C:/Users/username/AppData/Roaming/AdvancedSettings-Team/AdvancedSettings.log
[INFO] 2019-05-18 12:12:56: Command line arguments processed.
[INFO] 2019-05-18 12:12:56: OpenVR initialized successfully.
[INFO] 2019-05-18 12:12:56: Settings File: C:/Users/username/AppData/Roaming/AdvancedSettings-Team/OpenVRAdvancedSettings.ini
[INFO] 2019-05-18 12:12:56: C:/Users/username/AppData/Roaming/AdvancedSettings-Team/OpenVRAdvancedSettings.ini
[INFO] 2019-05-18 12:12:56: VR Runtime Path: C:/Program Files (x86)/Steam/steamapps/common/SteamVR
[INFO] 2019-05-18 12:12:58: SUCCESS: Chaperone Data Updated and Offsets zeroed out
[INFO] 2019-05-18 12:13:23: room setup ENTRY detected
[INFO] 2019-05-18 12:14:17: room setup EXIT detected
[INFO] 2019-05-18 12:14:17: SUCCESS: Chaperone Data Updated and Offsets zeroed out
[INFO] 2019-05-18 12:15:22: SUCCESS: Chaperone Data Updated and Offsets zeroed out
[INFO] 2019-05-18 12:15:25: SUCCESS: Chaperone Data Updated and Offsets zeroed out
[INFO] 2019-05-18 12:21:21: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:21:23: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:22:02: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:22:03: seated mode ENTRY detected
[INFO] 2019-05-18 12:22:06: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:24:34: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:24:36: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:24:55: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:29:05: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:29:07: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:29:51: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:29:52: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:35:27: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:35:29: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:35:30: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:35:30: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:35:31: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:35:44: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:35:44: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:35:45: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:43:33: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:43:35: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:43:36: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:56:14: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:56:17: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:57:06: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:57:08: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:58:08: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:58:22: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:58:24: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 12:58:30: Game Triggered Seated Zero-Position Reset
[INFO] 2019-05-18 13:31:16: seated mode EXIT detected
[INFO] 2019-05-18 13:32:11: Received quit request.
[INFO] 2019-05-18 13:32:11: All systems exited.

**Comment by ykeara** [comment]
Might be an issue w/ Universe Tracking origin via getoverlayTransformAbsolute() or setoverlaytransformabsolute().

**Comment by horst789github** [comment]
need you futher information from me?
label as bug?

**Comment by ykeara** [comment]
Nope good for now.

**Comment by ykeara** [comment]
Another Pimax user tested and did not have issue, so it appears its something to do either with us or some config issue.

**Comment by ykeara** [comment]
With 4.0.0 this will be removed as valve changed behavior of api and it is no longer possible
