### ISSUE TITLE
Steam VR Input bindings documentation updated for system button.

### ISSUE THREAD

**Issue by Viperlotus** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#203]
Hello.  A month or so ago I made a topic inquiring about using the system button of a Vive wand as a push-to-talk toggle for Advanced Settings.  This topic was closed (understandably so) because at the time it was not possible to do so due to the limitations in SteamVR's binding options.  However, before the topic was closed, it was pointed out that SteamVR's beta branch had added the ability to rebind the system button.  I decided to wait until that change was added to the main branch of SteamVR, which happened with its latest update.

So, that leads me to today.  I tried using a system button as a push-to-talk toggle like before.  First I opened the bindings options for Advanced Settings and successfully set the left system button as a toggle button, then bound the click function as push-to-talk.  After that, I opened the bindings options for VR Compositor and unbound all actions from the left system button so that they wouldn't interfere with the push-to-talk setting.  Even after all that however, pressing the assigned system button still doesn't activate push-to-talk at all.

**Comment by username223** [comment]
Do other buttons work as PTT?

Do other actions work on the system button?

I must admit that I'm not familiar with binding to the system button. The regular bindings do not work when the SteamVR overlay view is up, could that be interfering somehow?

**Comment by Viperlotus** [comment]
> 
> 
> Do other buttons work as PTT?
> 
> Do other actions work on the system button?
> 
> I must admit that I'm not familiar with binding to the system button. The regular bindings do not work when the SteamVR overlay view is up, could that be interfering somehow?

The answer to the first question is yes, other buttons do work as push-to-talk.

I have not yet tried binding other OVRAS actions to the system button, but obviously VR Compositor bindings do work on the system button.

And yes, I made sure to test the bindings with the SteamVR overlay view closed, to no effect.

**Comment by ykeara** [comment]
OKAY figured it out.

in Steamvr.vrsettings Under Steam VR This line needs to be added `"sendSystemButtonToAllApps" : true`

I will submit a bug-Report because it does not feel like this should be the standard behavior.... and it is confusing.... on top of it it doesn't block the "touch" event on knuckles controllers so its just bizarre.

Changing Issue to reflect some updates on our end on documentation needed.....

**Comment by Viperlotus** [comment]
Sorry for the late response, everyone.  It took me a while to get to it, but I just tried the fix ykeara mentioned.  It _does_ work; However, there is one important caveat that he did not mention in his post.

In the file where you add the line mentioned in the fix, you _**absolutely must**_ add a comma mark to the end of the line preceding it if the added line is the last one in the Steam VR section block.

Alternatively, if the added line is _not_ placed as the last one in the Steam VR section block, then you must add a comma mark to the end of the added line.

If you don't add a comma mark where it's supposed to be in relation to the added line, the steamvr.vrsettings file won't be read by Steam VR, and the settings that file is responsible for adjusting will all be set to their default values.

**Comment by ykeara** [comment]
yea you have to respect json formatting.... if its last in the list of settings it won't have common, but ones before it will have to.
