### ISSUE TITLE
vive wand grip button only registers as toggle

### ISSUE THREAD

**Issue by taidai1338** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#204]
With the new binding method, i've been trying to rebind my grip as a push to talk but even when specifying "HELD" it only results in toggle, i've tried all other v3.x and they all have this issues, also changing from single/double/long all result in toggle as well.

the issue isn't in 2.8 but it's spotty as to whether my mic initializes or not

**Comment by ykeara** [comment]
Sounds like you have the grip set as a "toggle button" rather than a "button". behavior just tested and worked fine, check that if its still an issue say something.

**Comment by taidai1338** [comment]
it was on button, nuked everything including steamvr and it works on reinstall
