### ISSUE TITLE
Add Common Issues to documentation for some platforms (quest alvr)

### ISSUE THREAD

**Issue by Nielzo** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#209]
I am using ALVR (v2.4.0-alpha4) on PC in combination with 'ALVRClient-GithubNormalOvr-release-v2.4.0-alpha4' on the Oculus Quest. On top of that I installed the ADV tool (v3.1.0 from Github) which should give me some more options to set things up. Most things are working fine in SteamVR with the Quest except that the ADV button in the Steam home menu is not doing anything. It is there and I can click it but just nothing happens when I do.

Does anybody know a possible solution? I tried to uninstall/reinstall the ADV program a couple of times, even while SteamVR is running.

**Comment by username223** [comment]
The Advanced Settings overlay isn't showing up?

What happens if you run advanced settings in desktop mode (run the `startdesktopmode.bat` in the install directory)?

**Comment by Zac-Taylor** [comment]
I am having the same issue when using my Oculus Quest. Once you run the Advanced Settings overlay and click the gear in Steam VR then nothing shows up.

**Comment by ykeara** [comment]
If you can check in the overlay Viewer in Steam (SteamVR dialog->burger menu-> developer->overlayViewer)

If OVRAS-Team.AdvancedSettings is in the overlay key list.

Also if one of you could post pastebins of the following logs:

1. Advanced Settings log - %appdata%/AdvancedSettings-Team [C:\Uses\<Username>\AppData\Roaming\AdvancedSettings-Team] AdvancedSettings.txt

2. VRServer Log - SteamInstall directory /logs vrserver.txt [C:\Program Files (x86)\Steam\logs default]


Can you still Access Advanced Settings binding interface via the binding menu? http://127.0.0.1:8998/dashboard/controllerbinding.html (while steamVR is running) or dashboard->settings->controllerBindings

**Comment by seawave2** [comment]
Same problem here on Oculus Quest.
Pressing the Advance setting button gives an empty screen.
I post the 2 logs you asked for:
1. https://pastebin.com/7DS5RXbs
2. https://pastebin.com/KA0hGPjB

the link for controllerbinding.html is accessed.

**Comment by ykeara** [comment]
Okay possible solution Is to go to NVidia control panel (AMD might have equiv?) and go to manage 3d Settings and add Advanced Settings as a program and force it to run on your GPU. See if that works might not but worth a shot....

**Comment by seawave2** [comment]
@ykeara 
THANK YOU!
The force GPU on Nvidia did the job.
Now ADV setting is shown like accepted

**Comment by ykeara** [comment]
good to see will update documentation to reflect this issue and a few others such as

1. wmr set-up all experiences vs no/bounds/standing only
2. Quest/ALVR / multiple GPU set-ups
3. Standing only VS room-scale set-up's
