### ISSUE TITLE
Keyboard Shortcuts not shown in misc tab

### ISSUE THREAD

**Issue by trudesea** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#219]
Hi,

Just installed the latest version from the release page and I'm not seeing the 3 keyboard shortcuts.

My AdvancedSettings-Team file has the following, I expected the [keyboardShortcuts] section to already be there based on the documentation, so I appended that section at the end, this did not seem to work.  What am I doing wrong here...or is this functionality not in the latest release?

[playspaceSettings]
lockXToggle=false
lockYToggle=false
lockZToggle=false
momentumSave=false
turnBindLeft=false
turnBindRight=false
moveShortcutLeft=false
moveShortcutRight=false
allowExternalEdits=false

[utilitiesSettings]
desktopWidth=4

Appended the following to the file:
[keyboardShortcuts]
keyboardOne=^>x
keyboardTwo=^>x
keyboardThree=^>x

**Comment by ykeara** [comment]
While it is merged into Master It is not yet "released"

if you want to use the development build it can be found here: https://ci.appveyor.com/project/icewind1991/openvr-advancedsettings/builds/25068895/job/214kwl15k8fv4fqb/artifacts (this is the latest master build).... Note: its not well tested, and their may be issues in the build.
