### ISSUE TITLE
Fix Floor not working properly IN WMR, playspace universes not syncing correctly.

### ISSUE THREAD

**Issue by monopecez** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#225]
Preconditions: 
1. Did not connect to Network/Internet
2. Using Lenovo WMR
3. AdvancedSettings is installed with installer version 3.1.0

Test step:
1. Open/ play game
2. Open Advanced Settings
3. Place one controller on floor
4. Do  fix floor by select fix floor
5. Verify result

Current result
Cannot fix floor. When fix floor is selected, height is fixed then reverted back.
* Video will be attached

**Comment by ykeara** [comment]
In WMR you need to be set-up for all experiences or  have "boundary on" when you start SteamVR ( you can turn Boundary off once SteamVR has started

**Comment by monopecez** [comment]
I've set up all-experiences and re-set up boundary before starting SteamVR. Result is still same. Works fine on 2.8.
[video.zip](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/3293808/video.zip)

**Comment by ykeara** [comment]
Will be next week before I can test...... might have just missed it in last pass to fix the issue.

**Comment by ykeara** [comment]
Okay Work-around

after using the "fix floor" go to offsets tab and click the "reset" button this will fix the issue At least temporarily

**Comment by ykeara** [comment]
Soo it appears the reset is applied, but the change in floor height is not applied so x/y is reset and snaps back... but floor height only seems to apply on "reset" in offsets page.
