### ISSUE TITLE
[Feature Request] CV1 Touch controller haptic feedback adjustment

### ISSUE THREAD

**Issue by Dyingsoul** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#226]
When I'm playing games with CV1 using OpenVR, the haptic feedback with the touch controllers are really weak compared to Oculus mode.
For example: playing the steam verasion of Beat Saber with -vrmode oculus launch parameters, the cuts made on the blocks have a really nice feedback but when I'm using the OpenVR to launch the game it doesn't feel right. I can barely tell if I've successfully cut the cubes.
I'm using openVR mode for recording purposes, so using the -vrmode oculus launch parameter is not a fix for me since I cant use third party applications for recording green screen gameplay.
It would be a really nice addition to the Advanced Settings if we could adjust the strength of the haptic feedback.

**Comment by ykeara** [comment]
We can't adjust this.... it might be adjustable in the SteamVR binding interface http://127.0.0.1:8998/dashboard/controllerbinding.html (while steamVR is running) or dashboard->settings (not adv) ->controller bindings... but I am not 100% sure.
