### ISSUE TITLE
Chaperone disappears quickly while outside boundary

### ISSUE THREAD

**Issue by tselling** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#228]
So I set the chaperone to come on when I am quite close to the boundary.... but it also disappears almost immediately while I am outside the boundary when I go just a slight bit further outside the boundary. This makes it so I sometimes barely notice the chaperone.  I would like to be able to have the chaperone continue to show the whole time I am outside the set boundary.  Is there currently some way to make this happen or could it be added as a feature?

**Comment by ykeara** [comment]
Will have to double check, but 99% sure its behavior that can't really be changed.... that being said can look into forcing chaperone while outside bounds is an option.

**Comment by ykeara** [comment]
Opened an issue w/ valve here https://github.com/ValveSoftware/openvr/issues/1110 but no response. closing out the issue as it will require changes by valve.... and no acknowledgement or progress.
