### ISSUE TITLE
Held weapon is visible while in inventory view

### ISSUE THREAD

**Issue by Tsilliev** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#233]
Hello,

I am using a resource pack (Conquest) and now whenever I open my inventory, my weapon is still shown and cant point to move items in the inventory, is there a workaround? Which file modifies this behavior?

**Comment by Kung-vr** [comment]
This is the OpenVR Advanced Settings repository. I might be mistaken but you it looks like you could be having an issue with Vivecraft? for 1.13 the issues page for that is here: https://github.com/jrbudda/Vivecraft_113/issues If you use a different version you can find it here https://github.com/jrbudda?tab=repositories

**Comment by ykeara** [comment]
Closing out issue as it appears to be vive-craft related? re-open if we have misinterpreted greatly.
