### ISSUE TITLE
Unable to save chaperone profile after doing Steam VR Room Set up

### ISSUE THREAD

**Issue by natv** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#234]
I don't know if this is a SteamVR problem or an OpenVR Advanced Settings issue, but OpenVR Advanced Settings  *used* to at least help me mitigate the problem (that is, until I uninstalled the old version and installed the latest release from this repository)

**My issue:**

**Oculus guardian:** 100% perfect, no issues (I mention this because SteamVR supposedly is supposed to be importing the Oculus settings, according to Steam Support anyway...)

**Steam Chaperone:**
The chaperone is turned by about 30 degrees, and no matter what I do, it reverts to that position.

I've re-done the room set up many, many times. At first, the chaperone is positioned correctly, but as soon as I start a game or quit steam, it gets offset again (I literally see it jumping back to the twisted position as I'm shutting Steam down)

A few weeks ago, I had somehow managed to save a profile in OpenVR Advanced Settings, and although Steam would keep defaulting back to the default profile (twisted 30 degrees) I could manually apply the saved profile and it would temporarily fix it (until I launch a new game or restart SteamVR, but at least I could fix it temporarily), though some games wouldn't honor the saved profile for some reason (like Creed and Beatsaber)

Anyway, I put in a ticket with Steam Support about the issue, and at first they said I was running some things that might cause issues (like OpenVR Advanced Settings) and suggested I uninstall it, so I removed it, re-ran room setup, and still had the same issue.

Then I re-installed OpenVR Advanced Settings, and since then haven't been able to get a saved profile to save the new room setup.  I've tried creating a new profile just before doing room setup,  tried creating a new profile just after doing room setup.  But it's not saving the position of the chaperone anymore.

I do feel this is probably more of a SteamVR issue than an OpenVR Advanced Settings, but posting this here in hopes that you might have an idea of how to fix this, either by doing something inside the OpenVR Advanced Settings app, or something inside SteamVR

Steam's remaining suggesting is for me to uninstall SteamVR but there's a warning before doing that, that it will delete all my game content so I'd really rather avoid having to start all over.

Is there a config file where SteamVR stores the Chaperone settings? If so maybe I can edit that file and try to play with the X,Y,Z numbers to fix the chaperone that way? I just don't know where this setting gets saved.

OpenVR Advanced Settings did used to help me temporarily fix this issue so I'd be OK with that solution for now, if I can just get it to save the new chaperone right after I re-do room set up.

Thanks

**Comment by ykeara** [comment]
yea If you un-installed us it's probably not on our end...... assuming you re-ran setup. At any rate.

For SteamVR's chaperone it is stored in C:\Program Files (x86)\Steam\config in the chaperone_info.vrchap file....

you can safely re-install SteamVR as well it just deletes the SteamVR  files, not all your games. at least 99% seemed to do that last time when I re-installed.

Another option is you can check the "disable chaperone" button and just go w/ the guardian system? (not 100% sure how rift interacts.)

I would manually delete the .vrchap file, uninstall ADV-settings, and remove->reinstall SteamVR to see if it is a SteamVR issue or not then add ADV settings back on top after that.

**Comment by natv** [comment]
I thought it was a SteamVR problem initially (because this problem shows up when I enable the SteamVR chaperone) but now I think this setting is actually coming from Oculus.

I remember when setting up my sensors / guardian in the PAST, there was a step where it had me spin the orientation the play area so it matches the sensor placement.


I re-did my guardian setup and I think I see the problem, I realized the setup is never asking me to spin the area like it used to, and so maybe it can't identify which is the front sensors and which is the back or something.


Here is what it looks like in SteamVR with the chaperone and guardian on (SteamVR's chaperone is green here)

http://i63.tinypic.com/idr49j.jpg


And this is how it looks during the Oculus Guardian setup, see how the Oculus rectangle is not at the same angle as my play area? I think this is my problem:

http://i66.tinypic.com/6fmdyr.jpg



Any ideas about this?

I agree this isn't an OpenVR Advanced Settings, if you have any advice that would be great but you can definitely close this issue otherwise.


Thanks again

**Comment by ykeara** [comment]
hmm Might post a ticket to SteamVR support thread In Steam.... might be an issue they need to fix...

Possible that manually running roomsetup from EXE (Steam) might do something..... is it possible to select move and rotate the area in Oculus  other thant that unfortunately I don't know (don't have Any rift Products)

Good Luck, but am closing out issue as not really relevant to Us at any rate.

**Comment by natv** [comment]
UPDATE --  FIXED!

It turns out this was an Oculus issue after all. 

I seem to recall this used to be in one setup and I guess Oculus now made this two steps (or my memory is bad), but my issue was that was re-drawing my guardian area only in Oculus.  The option to spin the play area to match your sensor set up is in a different part of the setup (Sensor setup), so going in there and reconfiguring my sensors resolved this problem.
