### ISSUE TITLE
REvive grip option 

### ISSUE THREAD

**Issue by d1360** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#236]
Considering revive tab was removed, that option to avoid holding grip butto was only useful thing there, it allowed you to avoid holding grip and shoothing, which ius uncofrtable on vive wands, and i just saw on reddit valveindex controllers would appreciate this option because revive games  V.I con trollers have no grip button and us vivers want to stop pushing that awful grip button

**Comment by ykeara** [comment]
Re-vive tab was not removed, and is still in... option to force show it... OR it should show up automatically if It is installed.

p.s. The area for the finger tracking is in fact a grip button.... well its an analog force sensor, but it can be set up as a button.

**Comment by zxsdklfhskyrvk** [comment]
@ykeara 
I had the Revive tab disappear on me after I installed fpsVR.  I enabled this feature and that SEEMED to fix the issue.  Now I see the "Force Revive Tab" feature is being removed. Are you sure it isn't doing anything?
