### ISSUE TITLE
Fix floor don't work after upgrade to 3.2

### ISSUE THREAD

**Issue by seawave2** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#242]
Placing one controller on the floor and pressing "fix floor" doesn't change to floor hight.

I go back to 3.1 and fix floor" is working again.

**Comment by ykeara** [comment]
Which headset are you on?

**Comment by seawave2** [comment]
Oculus quest

**Comment by ykeara** [comment]
Via which program then? ALVR? or RiftCat or something else?

**Comment by seawave2** [comment]
RiftCat

**Comment by ykeara** [comment]
did you run room set-up as standing only or as room-scale? out of curiosity?

**Comment by ykeara** [comment]
Def a bug but  run in room-setup should fix? it maybe.... if not it will be a bit before we can address it.

**Comment by seawave2** [comment]
I update again to 3.2 and make sure I'm on room-scale in the oculus quest.
Didn't help - now "fix floor" again don't make any difference

**Comment by Kung-vr** [comment]
Do the xyz offsets in the Offsets tab move you around or are those broken too?

**Comment by seawave2** [comment]
In 3.2 the XYZ offsets don't do anything too.

In 3.1 the "reset" in offsets tab indeed revert the floor to the starting position (ground level)

**Comment by ykeara** [comment]
Closing out as no response, and should be dealt w/ in most recent pre-release and very soon 4.0.0
