### ISSUE TITLE
[Feature Request] Please add Misc stuff to the dashboard.

### ISSUE THREAD

**Issue by fwenny** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#245]
Unless Im missing something obvious, the Keyboard 1, 2 and 3 shortcuts have to be bound in Settings > Controller Binding?

Could it be possible to simple add a new Misc tab in the AdvancedSettings overlay so we can use the shortcuts on a button press? Much like the "Enter" key in the Utilities, etc.

Thank you. If Im missing something, please let me know.

**Comment by username223** [comment]
>Unless Im missing something obvious, the Keyboard 1, 2 and 3 shortcuts have to be bound in Settings > Controller Binding?

That is correct.

>Could it be possible to simple add a new Misc tab in the AdvancedSettings overlay so we can use the shortcuts on a button press? Much like the "Enter" key in the Utilities, etc.

Yes, I'll look into this. No promises when it'll be done since I won't have access to a full VR setup for a little while.
