### ISSUE TITLE
[Feature Request] Ability to set individual device offsets

### ISSUE THREAD

**Issue by Casuallynoted** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#248]
It looks like at the moment, OpenVR Input Emulator breaks the cameras on the Valve Index HMD. I’d been using it to change the positional offsets on Vive Trackers while keeping my headset and controllers in the same place. The ability to create a device offset profile to reuse would be fantastic and would allow me to get rid of Input Emulator forever.

**Comment by ykeara** [comment]
Unfortunately this is ultimately outside the scope of ADV-settings.... it would require emulating/intercepting drivers like Input Emulator... its not something that is planned.... and tbh would be better suited to say input emulator but updated. IF there is a way to do it via API w/o drivers.... it would be possible, but until such point it is unlikely to happen for the forseeable future.
