### ISSUE TITLE
Can't set height change off

### ISSUE THREAD

**Issue by tkapis** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#249]
I've set a height change to simulate crouching and it works great but I can't set it off by clearing the On checkbox, it is always active.

**Comment by Kung-vr** [comment]
Does it update if you close the dashboard after changing the checkbox?

**Comment by tkapis** [comment]
No, the checkbox is cleared but the height toggle is always active every time I play.

**Comment by Kung-vr** [comment]
Yeah, the "on" setting there means your height is currently offset, and if "on" is unchecked it means your heat is not currently offset. If you instead want the steamvr input bind to do nothing when clicked I recommend you set the "Height Offset" text to zero.

**Comment by tkapis** [comment]
If I do that and the game uses the same button will it be passed through by Advanced Settings?

**Comment by ykeara** [comment]
Yes.... while the keys are bound they will always go to all programs, that being said if you change the height change to 0 it just won't do anything so the end result is it appears to not go through.

**Comment by tkapis** [comment]
Ok, I just tested this and if a button is set in Advanced Settings for height toggle and it is used in a program it will not be recognized by the program no matter what the value of the height offset is.

Thanks for all your replies anyway.

**Comment by ykeara** [comment]
it should apply to both the game and ADV settings.... i.e. if you set it to a trigger in a shooting game you should shoot and toggle your height every time..

**Comment by ykeara** [comment]
Closing as issue appears to be resolved? comment here if not.
