### ISSUE TITLE
Motion Screen: Check values only affect if controlled by button (not stick).

### ISSUE THREAD

**Issue by javidoom** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#250]
Hi!

Awesome method to avoid games without smooth turn.

**ISSUE:**

- The checkmark which enables or disables the Left Hand or Right Hand option in the "MOTION SETTINGS" screen for SPACE DRAG and SPACE TURN, only works when they are mapped to a button.

If you map the thumbstick to "turn space", it keeps working even when the checkbox in "Motion Settings" is disabled.

Thanks!

My setup:
Valve Index HMD with Index controllers.

((( I'm using this configuration for rotate in various games wich doesn't offer such function, as Karnage Chronicles, or DOOM. )))

**Comment by Kung-vr** [comment]
I'll look into this when I get a chance but in the meantime, just in case, can you confirm that you're binding "Space Turn" and not "Smooth-Turn" (If it's Smooth-Turn, those check boxes aren't intended to affect it).

**Comment by javidoom** [comment]
Hi!

So fast!!

Sure, I'm using SMOOTH TURN LEFT/RIGHT.

You are completely right. SPACE TURNS works as intended, and it's enabled/disabled with the checkbox.

I think I'll have to change controller binding everytime I use a game without smooth turn.
Maybe you can add the Smooth Turn to be enabled/disabled too with this same checkbox?

The ability to smooth turn in this games without it is really awesome.

Thanks again!!!

PS: The UNIVERSE CENTERED ROTATION is an awesome option to have too :)

**Comment by ykeara** [comment]
Issue seems to be resolved closing out issue.
