### ISSUE TITLE
Playspace mover not working.

### ISSUE THREAD

**Issue by CodenameHaswell** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#253]
I was in the middle of a long session, and I tried to use my playspace mover on version 3.1.0 with the HTC Vive, and it wouldn't work. Checked my settings, tried a PC restart, didn't work. Then I decided to attempt to upgrade to version 3.2.0, still didn't work. Reinstalled SteamVR, still didn't work. Deleted all SteamVR preferences, still didn't work. Then I tried reinstalling AdvancedSettings again, by uninstalling and removing any trace of it in the folder. Still did not work. I do however notice that my settings are saved somehow, so there are still files from it somewhere on my PC. I'd like to know where these are located to see if deleting those files has any effect.

I've been using this for months and months without issue, up until today.

Thanks,

Haswell

**Comment by neoaptt** [comment]
There was an update to steam vr beta today. Are you using the steam vr beta?

**Comment by Kung-vr** [comment]
In a default windows install the settings folder is at C:\Users\USERNAME\AppData\Roaming\AdvancedSettings-Team

Also just as a confirmation, were you using "Space Drag" (the built in advanced settings feature) or "Playspace Mover" (The older app that has a dependency on Input Emulator)? I'm also interested in if you're on steamvr's beta or not.

**Comment by CodenameHaswell** [comment]
I fixed it by reverting to normal SteamVR, somehow I was opted into the beta. And yes I was using the space drag. Thanks for telling me where the settings are stored.
