### ISSUE TITLE
Pimax 5K+ mic stops working as soon as OpenVR advanced settings runs

### ISSUE THREAD

**Issue by arleas** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#263]
The Mic works just fine prior to OpenVR advanced settings starting up. Once OpenVR advanced settings starts up, then the mic goes dead and doesn't come back until I reset/reboot the headset itself.

**To Reproduce**
1. verify the headset mic works 
2. Start pitool
3. Start SteamVR
4. OpenVR advanced settings loads up automatically
5. Mic stops responding as if it's muted

**Expected behavior**
The program has a setting to mute the mic if the headset is not being worn, however this setting was not engaged and it didn't matter if I was wearing it or not, the mic did not work.  I expected the mic to work as long as it was the properly chosen device in the sound properties, in Windows 10 OS settings, and in SteamVR. 

**Screenshots**
Sorry, I can't really screenshot sound...or a lack thereof

**Software (please complete the following information):**
 - OS: Windows 10 Pro 64bit
 - Advanced Settings Version: 3.2
- SteamVR beta OR the main SteamVR branch, neither one mattered

**Hardware (please complete the following information):**
 - CPU: Intel i7 4770K
 - Graphics Card: EVGA GTX1080Ti
 - HMD: Pimax 5K+

**Additional context**
The problem promptly went away once the program was uninstalled.

**Comment by ykeara** [comment]
Sounds Like you had the `Proximity Sensor Mutes/Unmutes Microphone` option on, AS Pimax does not have a proximity sensor this setting can cause somewhat unpredictable behavior.....


It should also be noted due to limitations w/ SteamVR if this option is selected you WILL ALWAYS be muted while dashboard is up regardless of HMD.

Try that if you continue to have issues then I suspect PiTool Is misbehaving again, and I will have to do a work-around.

**Comment by ykeara** [comment]
To clarify its in the Audio Tab.

**Comment by arleas** [comment]
You would think that, but no... I checked it, then unchecked it and looked
at the icon for the  mic to see if it was enabled or not and if it had a /
through it I made sure to click it and basically I tried everything I could
think of to get the mic enabled, but absolutely nothing worked.  It's like
if it was set to disable it by default and like you said, there's no sensor
to tell it to enable it, then it stayed disabled except any and all
attempts to get it working from any angle at all failed the instant that
openVR advanced settings took control.  If It had been a simple fix I
wouldn't have bothered you with a bug report.

I don't know if you have a pimax 5K that you can test it out with, and
maybe somehow it's peculiar to my setup though I don't know why it would
be... but really the only thing I ever used out of OpenVR advanced settings
was changing the audio to headphones when it got switched off and
occasionally resetting my chaperone bounds when they got messed up. I can
live without both of those things but I'll check in a future version to see
if the problem still exists.

**Comment by ykeara** [comment]
Closing Out age and no more reports.
