### ISSUE TITLE
All overlays have tracking stutter with OVRAS installed

### ISSUE THREAD

**Issue by Rexios80** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#274]
**Describe the bug**
Today my overlays suddenly starting having tracking stutter (stuttering when moving head). I uninstalled OVRAS and the problem is gone. FPS is also about 30% lower with OVRAS installed (which was happening before the stutter started I just didn't notice until I uninstalled OVRAS).

**To Reproduce**
1. Install OVRAS
2. Launch SteamVR
3. Open any overlay including Steam itself
4. Move head at all (it's really bad)

**Expected behavior**
No stutter while viewing overlays. No significantly lower FPS.

**Screenshots**
It would have to be a video and I'm not sure how to capture SteamVR.

**Software (please complete the following information):**
 - OS: Windows 10 1903
 - Advanced Settings Version: 3.2.0

**Hardware (please complete the following information):**
 - CPU: Ryzen 9 3900X
 - Graphics Card: 2080Ti
 - HMD: Valve Index

**Additional context**
It was literally fine yesterday. I really hope we can figure this out because this program is really useful to me.

**Comment by Rexios80** [comment]
I did some more messing around and I've found that OVRAS 2.5 does not have the issue, but it also doesn't have the features I need.

**Comment by ykeara** [comment]
I have a 3900x, 1080, and an index and don't get the behavior so yea its odd.

Do you have any other SteamVR apps installed? fpsvr? input-emulator? re-vive? etc.?

have you tried other frame rates and what are you targeting w/ index?

and are you on SteamVR beta or live?


and you could try https://ci.appveyor.com/project/icewind1991/openvr-advancedsettings/builds/26119416/job/h5cltaml5gmum0h7/artifacts its a more recent dev build.... add the option to change our tick rate in settings... can try adjusting that behavior and seeing what happens.

**Comment by Rexios80** [comment]
I did just get fpsVR, but that was a couple days before the issue started. I even kept fpsVR stopped specifically to avoid conflicts. I'll try uninstalling it when I get home and report back.

**Comment by Rexios80** [comment]
See #275. That was my real issue. fpsVR had nothing to do with it.
