### ISSUE TITLE
Remove Velocity dependent fade.

### ISSUE THREAD

**Issue by bennybobz** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#275]
Going into chaperone settings and activating the velocity dependent proximity warning, completly freezes steam overlay on exit. The system button no longer opens the overlay and holding it down does not bring up the small menu. The overlay will continue to be unresponsive until i delete the configs in appdata. Or at least just deleting the apropriate line from the file. (I have gone through all the settings and made sure activating velocity dependent proximity warning is the only thing that does this for me).

 - Windows 10
 - Advanced Settings Version: 3.2.0
 - i5 7600k
 - GTX 1070
 - Vive HMD

**Comment by ykeara** [comment]
Yea have already noted this bug and done a work-around in most recent build -> https://ci.appveyor.com/project/icewind1991/openvr-advancedsettings/builds/26785240/job/3lrqy4w63k5srkel/artifacts though its going to be fairly un-responsive (and at least imo therefore un-useable.) I will make a quick change, that might get it to a somewhat use-able change, but no guarantees if the quick fix doesn't work Will more or less have to assume the feature to be on-hold/un-supported until a full re-work of it can be done.

**Comment by Rexios80** [comment]
Holy shit this is what was causing my issue in #274! That's why the issue seemed to pop up out of nowhere.

**Comment by Rexios80** [comment]
Also you might want to just disable the setting if you can't fix the issue fully. I'm willing to bet a lot of people like me will end up enabling it and then not know what the heck happened to their Steam overlay.

**Comment by ykeara** [comment]
based on issues, we are going to remove this feature for the forseeable feature, as it causes severe performance penalty, and would requrie extensive work and performance overhead to re-write and get it to work.... as it stands it is not currently feasible to change the boundaries in a timely manner with your speed of your controllers.
