### ISSUE TITLE
Proximity sensor mic mute mutes mic in Steam overlay

### ISSUE THREAD

**Issue by Rexios80** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#276]
**Describe the bug**
The proximity sensor mic mute is muting the microphone while in the Steam overlay

**To Reproduce**
1. Turn on proximity microphone muting
2. Open Steam overlay
3. Microphone is muted

**Expected behavior**
The microphone should not mute when in the Steam overlay

**Screenshots**
Pretty self explanatory

**Software (please complete the following information):**
 - OS: Windows 10 1903
 - Advanced Settings Version: 3.2.0

**Hardware (please complete the following information):**
 - CPU: Ryzen 9 3900X
 - Graphics Card: 2080Ti
 - HMD: Valve Index

**Additional context**
This is pretty annoying in social games such as VRChat. I'm not sure if this is intentional or if SteamVR is reporting the proximity sensor value incorrectly while in the overlay? If so it might not be fixable, but it's worth looking into.

**Comment by ykeara** [comment]
Unfortunately it is a SteamVR behavior thing, while the overlay is active the inputs are not sent to the application... and for all intents and purposes the "proximity sensor" is an "input"/button.

It would be possible to do work-around but then it would make behavior inconsistent, and that is not desire-able either. for the immediate future I doubt we will change.... essentially while your dashboard is up no keybinds will work, and all should be in the "off" position.
