### ISSUE TITLE
[Feature request] Space Flip

### ISSUE THREAD

**Issue by kafeijao** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#278]
**Is your feature request related to a problem? Please describe.**
In VRC whenever I lay down looking up I can't really interact with people, I would turn to my side so I could at least look at people, but the index headset doesn't allow for my head to rest on the side. Also it would be pretty neat to walk on walls and ceiling.

**Describe the solution you'd like**
What I basically would like was something like Space Turn but for the horizontal axis, so for instance I could flip myself 90 degrees or even 180 (making myself upside down).
I guess it could also be a simple button in the Space turn to allow rotating in all axis instead of just rotating with the vertical axis. Or even something new called Space Flip, as long as I'm able to flip I am very happy c:

Thanks for the attention

**Comment by ykeara** [comment]
Long story short we can't/won't do this.


We can freely control translation in all 3 axes, but can only control the yaw axis.....roll and pitch are not really work-able with our solution, and would require emulating drivers. while technically feasible it is not something we are going to approach. unless Steam changes the API to allow us to do something crazy XD.
