### ISSUE TITLE
Compositor Supersampling

### ISSUE THREAD

**Issue by unkellsam** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#284]
How can we change the compositor supersampling value like we used to be able to?

**Comment by ykeara** [comment]
SteamVR tab currently allows the changing of SS it changes the "application" SS value, as the compositor Value is more driven by drivers (and there is not really any control of the compositor SS exposed anymore from a quick ctrl+f)

IT should be noted that you will need to refresh (close and open) the overlay for you to be able to change your value.... based upon some reasonable experimentation this is an effect of SteamVR. The issue has already been addressed (in that there is more clear messaging) in current development builds and will be in future releases.

It should also be noted that not all games can have their SS value changed dynamically. i.e. you will be required to restart the game. [ I think unity works dynamically, while ue4 games require restart]

It should also be noted that some games have dynamic SS so you can't overly control SS in those titles (steamVR home being one of the big ones).
