### ISSUE TITLE
Motion settings working in Steamvr home but not in apps - Oculus Rift S

### ISSUE THREAD

**Issue by xW3APONX** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#285]
**Describe the bug**
Hi, I have setup my controllers to use the motion feature which works perfectly in Steamvr home but as soon as i load a app e.g. Bigscreen the overlay does not work nor do any motion controls.
I am quite new to this feature and vr so forgive me if i have missed something.

**To Reproduce**
1. I Load Steamvr
2. Motion controls e.g space drag n space turn work as expected 
3. enter app ...Bigscreen, Steamvr adv settings not accessible and motion controls not working.  
4. 

**Expected behavior**
Upon entering app bigscreen i should have access to advanced setting and motion controls.

**Screenshots**
N/A

**Software (please complete the following information):**
 - OS: Windows 10
 - Advanced Settings Version: 3.2

**Hardware (please complete the following information):**
 - CPU: i9 9900k 
 - Graphics Card: RTX 2080 Ti
 - HMD: Oculus Rift S 

**Additional context**
I did use a command in my bigscreen app in steam under launch options, which was like -openvr and some which mad it work but i had no app controls. Your assistance would be much appreciated.Thanks.

**Comment by ykeara** [comment]
To clarify can you still access other features of advanced settings.... or can you not access the menu at all?

**Comment by xW3APONX** [comment]
Advanced settings can be accessed only by pressing the oculus button on the right controller and entering the steam app that is still running in the background.

**Comment by xW3APONX** [comment]
I have discovered that if i use "-vrmode openvr" in the Steam set launch settings i have access to the steam overlay in Bigscreen and the motion settings work fine but i am unable to use any bigscreen default movement controller configs even if i disable the motion settings.

**Comment by xW3APONX** [comment]
Thank you for your assistance so far. I have been able to get the motion controls working in Bigscreen app but my buttons config is all mixed up. I have entered the address above to try and reconfigure my buttons but it does not give me options in the Advanced Setting tab to add or configure the buttons for bigscreen or vice versa.

**Comment by ykeara** [comment]
Closing as issue seems to be resolved?
