### ISSUE TITLE
Offset Rotation for Y-Axis

### ISSUE THREAD

**Issue by LazyMan1234** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#292]
I'm always frustrated when running games and I can't lay down while playing said game because 9 times out of 10,  I'm now looking at the ceiling with no way to adjust unless I do so in real life.

I see the app offers offsets of positions and x-axis rotations.  It would be amazing if Y-Axis rotation offsets were offered.

**Comment by ykeara** [comment]
This is unfortunately not technically feasible. we can control positional axis, and rotate about the y axis (meaning you turn left to right) but we can't control z/x axis (which would allow you to turn up/down) While its technically possible it would require setting up drivers, and  that is something that is outside of scope. 

https://github.com/matzman666/OpenVR-InputEmulator would probably be a good point for implementing a feature like this.
