### ISSUE TITLE
audio doesnt stream for Quest streaming under AMD relive.

### ISSUE THREAD

**Issue by BrotherO4** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#293]
i dont know if its a bug or a lack of feature.
i am using the Quest and Relive. when i remove open vr audio streams beautifully but when i do install open vr it does not at all. 

is this a bug, lack or feature, or me being stupid?

**Comment by ykeara** [comment]
Sounds like a bug, can you please explain the process top to bottom of specifically how your process works.

as Quest is not even remotely natively supported for PC let alone  SteamVR I need to understand what is the process here.

**Comment by BrotherO4** [comment]
its bug not relating to Open VR. after i took a look around it seems to be related to ALVR effecting Relive in some negative way. after i remove ALVR the audio was back up. you can disregard my post lol.
