### ISSUE TITLE
Feature Request Pole/Pillar boundry overlay

### ISSUE THREAD

**Issue by Sun-Gear** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#294]
Some of users have a pillar in the middle of their playspace with no way of marking it's location affectively. Many others (like me) have a Dancing pole in theirs.

When it comes to pole dancing in VR, being able to always see where your pole is located is extremely important. Currently I can fidge this with turn signal but doing so effectively prevents me from using playspace mover as doing so would more turn signal away from the pole. Having an overlay that will show the pole and stays locked to the chaperone bounds, this allowing use of playspace mover would be extremely beneficial to not just me but many other VR pole dancers and also those who have a pillar in their playspace.

Thanks for hearing me out. This is a problem me and my group have to deal with regularly and I cannot count the number of times I've straight up walked into my pole.

**Comment by Kung-vr** [comment]
I've given some thought to how we might accomplish this. There are a couple of ways to go about it, but either they'd be janky or a fair amount of work to implement. I'll keep it in mind as a possible thing to implement but I'm not sure when/if I'd get around to it.

In the meantime, have you tried using  Xavr0k's Chaperone Tweak? It can be found here: https://github.com/Xavr0k/ChaperoneTweak

It should allow you to edit your chaperone to encroach within your playable area boundary, so you can make a spike coming in from the chaperone bounds pointing to the location of your pole. Note, for changes from external tools to stick you'll have to enable "Allow External App Edits" in the settings tab (just while the other tool is running).

**Comment by ykeara** [comment]
Talked going to close it out... between the complexity of adding it to the app, niche, and we think its better served by another project at least for now.
