### ISSUE TITLE
how to use push to talk?

### ISSUE THREAD

**Issue by BrotherO4** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#295]
I do not understand the instruction.
first i check mark push to talk
than according to the little writing on the side it says to change said setting in "Steam VR binding".
in there i see nothing at all to make any of my inputs to push to talk.
anyone can point me to the right direction so i can set it up?

**Comment by Kung-vr** [comment]
We have a guide to steamvr input in our docs here: https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/blob/master/docs/SteamVRInputGuide.md

Push to talk is under the "Misc" section of the bindings.

**Comment by BrotherO4** [comment]
i am trying to use the touch. when i open the inputs sets there is no "misc" tap anywhere.

**Comment by BrotherO4** [comment]
edit, nvm i was choosing side game not AdvanceVR.  i let you know how it goes than

**Comment by Kung-vr** [comment]
Ok, closing this issue for now since it seems to be solved.
