### ISSUE TITLE
Movement broken

### ISSUE THREAD

**Issue by Eddie821** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#300]
When testing the play space move, turn, and gravity setting in VRchat, it would work for maybe half a second before it starts stuttering before the actual place/rotation in game and the place that advanced settings is trying to put me, and after a few second will put me in the same place I was before I used playspace turn, move, or gravity. This makes it unusable. It tried several controller layouts and nothing worked. I’m on an oculus rift with 3 Vive trackers.

**Expected behavior**
I expect to move around / turn as I move my had

**Software (please complete the following information):**
 - OS: Windows 10 Latest

**Hardware (please complete the following information):**
 - CPU: 2700x
 - Graphics Card:  2060
 - HMD: OG Rift

**Additional context**
I’m also using 3 Vive trackers

**Comment by Kung-vr** [comment]
Can you try it again on this build, while also using the steamvr beta branch?

build: https://ci.appveyor.com/project/icewind1991/openvr-advancedsettings/builds/28416788/job/2u0u0rkm9xvlif5d/artifacts

**Comment by ykeara** [comment]
Closing out should be resolved, or re-confirmation on 4.0.0
