### ISSUE TITLE
A "zoom" feature for visually impaired people

### ISSUE THREAD

**Issue by IngwiePhoenix** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#301]
Hello there! I would like to propose a rather interesting, yet universally useful feature.

**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Kind of :)! I am visually impaired, and I always find it frustrating that I can not read menus in the SteamVR overlay - at all. They are too far away from me to properly read them, so I would like to bring them closer. Some VR games also do not have the ability to physically "walk up" on the menus to make them bigger - but this is likely something this tool can not fix. But just being able to bring the SteamVR overlay closer would be a huge help!

**Describe the solution you'd like**
I honestly don't know what a viable route for this implementation would be. As far as I know, the SteamVR overlay is fixed to a certain distance. Maybe if there was a way to reduce this distance, it would allow me to bring the menu and all the other components closer?

**Describe alternatives you've considered**
There is no real alternative here. Walk closer and the menu walks away from you...kinda makes you think it doesn't like you :p . But jokes aside; I did try to see if there were settings for text sizes and did not find one, unfortunately...

**Additional context**
I use a Valve Index and I mainly see on my left eye. The right eye is more or less support, because it barely works anymore. My FoV is really small and tiny, but my glasses work perfectly within the Index - although there is only about half a millimeter between my glasses and the lenses which is kinda scary. But it works! I played some VR titles so far and I have had no problems - only when trying to really do something with the SteamVR menu...

Hopefuly you can help me out here :)

**Comment by username223** [comment]
Thank you for leaving some feedback.

Moving the menu overlays (desktop, Advanced Settings itself, whatever else) has already been implemented for the desktop overlay, but Valve broke it in a recent patch. I'm not up to date on whether that's only for the beta branch or on live as well, but I hear that beta is going live soon, so that feature should count as being broken by Valve.

It has been discussed with @ykeara to create a sort of virtual magnifying glass using the SteamVR overlays. The exact mechanics and implementation have not been decided on yet.

**Comment by IngwiePhoenix** [comment]
Ohh, that sounds interesting! I am Looking Forward to this magnifying glass feature honestly 😊

Alright then… Looks like it’s your task to un-break the feature now, I guess? Good luck, you have my support! ^.^ If there is anything I can do to contribute, let me know. I am not super experienced in C/C++ development, let alone Unity, but I should be able to poke things and see what happens. So if there is something, let me know 😊

Von: username223
Gesendet: Sonntag, 3. November 2019 13:25
An: OpenVR-Advanced-Settings/OpenVR-AdvancedSettings
Cc: Ingwie Phoenix; Author
Betreff: Re: [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings] A "zoom"feature for visually impaired people (#301)

Thank you for leaving some feedback.
Moving the menu overlays (desktop, Advanced Settings itself, whatever else) has already been implemented for the desktop overlay, but Valve broke it in a recent patch. I'm not up to date on whether that's only for the beta branch or on live as well, but I hear that beta is going live soon, so that feature should count as being broken by Valve.
It has been discussed with @ykeara to create a sort of virtual magnifying glass using the SteamVR overlays. The exact mechanics and implementation have not been decided on yet.

**Comment by ykeara** [comment]
Unfortunately going to close this issue out.

It is not currently possible w/ OpenVR, and with their Shift To OpenXR it will probably never Be possible.
