### ISSUE TITLE
Include the missed features from dead Input Emulator

### ISSUE THREAD

**Issue by mmorselli** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#302]
Since OpenVR Input Emulator dosn't works anymore, would be nice if some usefull missed features, like controllers redirection, controllers offsets and input remapping will be included in AdvancedSettings

**Comment by ykeara** [comment]
input re-binding should all be done through steam now. as the system is in place, and is quite good.

we can't do redirection and controller offsets as our approaches are considerably different. and most noticeably we don't want to be a driver.
