### ISSUE TITLE
Allow the user to extend the distance of your hands or rotate them via a controller binding.

### ISSUE THREAD

**Issue by Mr-Foxtrot** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#303]
Enhancement:
Add a menu which allows you to bind a button to either controller to extend a defined hand further and reach objects you otherwise would be unable to reach or rotate a defined hand at varying speeds for fighting games as just a bit of fun.

**Comment by ykeara** [comment]
see #302 not really feasible for how we are set-up.
