### ISSUE TITLE
Add application update notification

### ISSUE THREAD

**Issue by username223** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#305]
**Is your feature request related to a problem? Please describe.**
It is difficult for users to know when a new version of the application is available.

**Describe the solution you'd like**
A notification for when new versions are available.

It should be possible to disable the feature, and customize the size of update to notify at (patch, feature, major, as defined by SemVer).

**Describe alternatives you've considered**
A dedicated installer/updater would be more powerful, but would also require substantially more time and effort. Lacking any sufficiently powerful third party distribution mechanisms, a simple notification will have to do.

**Comment by ykeara** [comment]
Fixed With #308 and #317
