### ISSUE TITLE
Space Turn using Controller rotation

### ISSUE THREAD

**Issue by crashbandicool** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#310]
A problem for me is nausea during the current HMD based space turning. 
I’d love an option to use the respective controllers rotation change, rather than the HMD. 

There was an app that demonstrated this once ( can’t remember the name of it sorry ) but it was nice having the redirection motion decoupled from the HMD. You would walk up to the threshold, engage redirection and sort of rotate the world around yourself. Comfort tricks employed in that one were: bounds / grid forced on during redirection/ rotation(which you already have). Controllable / variable amount of blurring of the game world. 

Not sure how feasible the blurring would be but controller based space turning would be amazing. 

I have tried using the comfort mode slider but I feel for me it does decrease the accuracy of the redirection process.

Thanks for considering!

**Comment by ykeara** [comment]
our space turn should be exactly what you want.....

Note we offer smooth turning via a bind, and then also space turn which does grab your controller and turns you based on your controller orientation?

maybe I am mis-understanding?

**Comment by crashbandicool** [comment]
No you’re right. I just thought it was stuck to the hmd rotation. I was just turning on the spot and misinterpreted. Sorry! So foolish of me.
