### ISSUE TITLE
Color Correction forced to 1% when installing 4.0

### ISSUE THREAD

**Issue by dtupper** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#320]
**Describe the bug**
When you launch OVRAS after installing 4.0, your Color Correction values for RGB are set to 1% instead of 100%. This results in a very dark screen.

**To Reproduce**
1. Install OVRAS as an upgrade or a fresh install.
2. Launch into SteamVR.

**Expected behavior**
Color values are set to reasonable values such that the screen isn't super dark.

**Software (please complete the following information):**
 - OS: Win10
 - Advanced Settings Version: 4.0

**Hardware (please complete the following information):**
 - CPU: i9-9900k
 - Graphics Card: 2080 
 - HMD: Index

**Comment by ykeara** [comment]
Yep fixed already, CI's are building atm will do a  4.0.1 release within the hour.

**Comment by ykeara** [comment]
4.0.1 is available now.
