### ISSUE TITLE
What do you use to make the box for the centerMarker and playspaceMarker appear?

### ISSUE THREAD

**Issue by MaxAbillion12** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#325]

**Comment by Kung-vr** [comment]
It's a feature built into SteamVR's chaperone system. We provide settings to enable it from within vr in our chaperone tab. Once enabled, the vr compositor will handle the rendering of the centerMarker and playSpaceMarker. Were you wondering how it's implemented in code? Or just wondering what was doing the rendering? I might be of more help if you could be a little more specific with your question.
