### ISSUE TITLE
Desktop view in steamHome becomes very small.

### ISSUE THREAD

**Issue by BrotherO4** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#333]
System,
index
5700XT
3800X
32gb of ram

sadly I do not how to reduce this bug or feature. It just happens and than it never went back to normal size desktop view. what do i mean is when you press Steam Home button to open the setting and selecting Desktop view its normally a nice large view...for some reason is extra small.

with Valve support we were able to narrow it down to this software that was causing the issue. removing it make it go away and installing it bring the desktop back to small mode again.

if there anything i can do to help with this issue let me know.
here is a SteamVR log just incase.

[SteamVR-2019-12-04-AM_09_43_49.txt](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/3925046/SteamVR-2019-12-04-AM_09_43_49.txt)

**Comment by ykeara** [comment]
In the "SteamVR" tab adjust the "desktop Overlay Width:" should be your issue I think 4.0 is default size though I'm not 100% sure without looking at it

**Comment by BrotherO4** [comment]
yup that was the issue.
i dont think i ever touch it or maybe i did somehow but that was it.

thank you very much.
