### ISSUE TITLE
Accessiblity tab - Where did the height offset go?

### ISSUE THREAD

**Issue by dantharp** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#336]
Hi, it's quite possibly just that I'm missing something, but in older (3.x) versions, I used a setting on the "Accessiblity tab" that adjusted my height in a game world (Fallout 4 VR, for example) to compensate for the fact that I'm sitting down.
Instead of always looking up (being very short) I could make this adjustment and it was if I was standing while playing.
According to the documentation the "Accessiblity tab" options were moved to other tabs, but for the life of me, I can't seem to locate the one used to adjust a player's height position.
I pretty much use this utility to set supersampling and the height adjustment so it's pretty important to me.
Attached is a screenshot of the old setting I'm looking for in 4.0.1.
Thanks!   Dan Tharp (dantharp@gmail.com)
![SVRAS_Accessibility](https://user-images.githubusercontent.com/8082289/70402663-c6bc4600-19f9-11ea-8088-eccb79e7478f.png)

**Comment by ykeara** [comment]
In the Motion Tab:

[image](https://i.imgur.com/29r2HxL.png)

There is no longer a slider, you either direct input your value, or you can set from an existing y-offset via dragging or manually setting via the offset tab.

keybinds are ofc handled via steamvr keybinds now.

**Comment by dantharp** [comment]
Awesome!  Thanks @ykeara!  👍
