### ISSUE TITLE
I can't disable chaperone.

### ISSUE THREAD

**Issue by TheCodeFiend** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#346]
**Describe the bug**
I cannot hide the chaperone.  I setup my room and drew boundaries.  When I sit on my couch, it shows me outside the boundaries of my play space.  I tried to disable it by using "Disable Chaperone" in 4.0.1.  I then restart SteamVR, but the chaperone is still there.

**To Reproduce**
1. Click "Disable Chaperone"
2. Click Apply.
3. Chaperone is still visible.
4. Turn off SteamVR.
5. Turn on SteamVR.
6. Chaperone is still visible.

**Expected behavior**
The chaperone should disappear.

 - OS: Windows 10 1809
 - Advanced Settings Version: 4.0.1

**Hardware (please complete the following information):**
 - CPU: AMD Ryzen 7 2700
 - Graphics Card: Geforce GTX 1080 Ti
 - HMD: Vive Cosmos

**Comment by ykeara** [comment]
Does Adjusting the fade distance to 0 do anything? the disable chaperone button is essentially just a shortcut for that?

and should also note does the Cosmos have any external software like pi-tool/oculus/wmr etc?

**Comment by SyDroX** [comment]
I can confirm this isn't working as well. 
I wanted to completely remove the blue circle.
Visibility, Fade Distance, Height, Center Marker, Play Space, Force Bounds and Disable Chaperone
Don't seem to affect the chaperone. I tried restarting SteamVR.

OS: Windows 10 x64 1909
Advance Settings Version: 4.0.1
SteamVR: 1.9.16

Hardware:
CPU: Intel i7-7800X
GPU: Geforce GTX 1080Ti
HMD: Vive Pro

**Comment by ykeara** [comment]
@SyDroX The "standing only" playspace (i.e. the circle) is different from "roomscale" set-up option, and unfortunately some of the settings won't work w/ the "standing only" option.

**Comment by paulopsx2** [comment]
The same here !! I can confirm this isn't working.
I wanted to completely remove the blue circle.
Visibility, Fade Distance, Height, Center Marker, Play Space, Force Bounds and Disable Chaperone
Don't seem to affect the chaperone. I tried restarting SteamVR.

OS: Windows 10 x64 1903
Advance Settings Version: 4.0.1
SteamVR: 1.9.16

Hardware:
CPU: Intel i7-5960X
GPU: Geforce RTX 2080Ti
HMD: Vive Pro EYEtracking

**Comment by ykeara** [comment]
@paulopsx2 as stated the "standing only" setup is different from "room-scale" and can't be disabled. if your intent is to disable the chaperone anyways its best to set up as room-scale and then disable.

**Comment by TheCodeFiend** [comment]
> Does Adjusting the fade distance to 0 do anything? the disable chaperone button is essentially just a shortcut for that?
> 
> and should also note does the Cosmos have any external software like pi-tool/oculus/wmr etc?

Yes, that's what the checkbox does.  Changing it manually makes no difference.  I'm not using Oculus.  Not sure what pi-tool or WMR are.

**Comment by ykeara** [comment]
So after looking at things the Cosmos does appear to use its own little software layer, as such it probably supplies its own "chaperone" or barrier system, and ADV-Settings won't disable it. You will have to look at the cosmos software to see if there is an option to disable it.


The chaperone settings can only really be guaranteed to work for Vive/Vive Pro Index..... and I know there is some ways to get it to work w/ WMR (really you run both the chaperone and the WMR boundary and its not perfect) and Pimax may also work as well (though not 100% sure)

Going to close out issue unless we know for sure it's using steam's system, but the software layer that I see seems to indicate it does not.
