### ISSUE TITLE
OpenVR not displaying in stand alone steamvr

### ISSUE THREAD

**Issue by tails1972** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#358]
**Describe the bug**
I have the stand alone version of Steamvr which is found in the enterprise site of htc,
And with this version openvr does not display in the overlay .

**To Reproduce**
Run steamvr

**Expected behavior**
have the advance steamvr setting available in the menu inside the htc vive headset

**Screenshots**

**Software (please complete the following information):**
 - OS: windozs 10
 - Advanced Settings Version: 4.0.1

**Hardware (please complete the following information):**
 - CPU:i7 7700
 - Graphics Card: rtx 2080
 - HMD: htc vive pro in wireless mode

**Additional context**
I do not have steam installed at all
the location of the app that runs when i click on the steamvr shortcut is 
C:\Program Files (x86)\SteamVR\bin\win32\vrstartup
My steam config folder is found
C:\ProgramData\Steam\config
I have manifest.vrmanifest in my config\appconfig.json file
I have been able to make it work on a computer with steam installed,
I noticed that the manifest.vrmanifest doesn't have a open with programme attached to it, wondering if that is causeing the issue.
Which programme should it be using, maybe i can force it

thanks

**Comment by tails1972** [comment]
here is my advance settings log
[INFO] 2020-01-28 16:37:07: Application started (Version 4.0.1-dev+50c84156)
[INFO] 2020-01-28 16:37:07: Log File: C:/Users/Backlight/AppData/Roaming/AdvancedSettings-Team/AdvancedSettings.log
[INFO] 2020-01-28 16:37:07: Settings File: C:/Users/Backlight/AppData/Roaming/AdvancedSettings-Team/OpenVRAdvancedSettings.ini
[INFO] 2020-01-28 16:37:07: defaultlockXToggle: 'false' | lockYToggle: 'false' | lockZToggle: 'false' | momentumSave: 'false' | turnBindLeft: 'false' | turnBindRight: 'false' | turnBounds: 'false' | moveShortcutLeft: 'false' | moveShortcutRight: 'false' | dragBounds: 'false' | allowExternalEdits: 'false' | oldStyleMotion: 'false' | universeCenteredRotation: 'false' | enableSeatedMotion: 'false' | adjustChaperone: 'true' | showLogMatricesButton: 'false' | simpleRecenter: 'false' | disableVersionCheck: 'false' | previousShutdownSafe: 'true' | vsyncDisabled: 'false' | crashRecoveryDisabled: 'false' | enableDebug: 'false' | pttEnabled: 'false' | pttShowNotification: 'false' | micProximitySensorCanMute: 'false' | micReversePtt: 'false' | alarmEnabled: 'false' | alarmIsModal: 'true' | vrcDebug: 'false' | brightnessEnabled: 'false' | isOverlayMethodActive: 'false' | colorOverlayEnabled: 'false' | chaperoneSwitchToBeginnerEnabled: 'false' | chaperoneHapticFeedbackEnabled: 'false' | chaperoneAlarmSoundEnabled: 'false' | chaperoneAlarmSoundLooping: 'true' | chaperoneAlarmSoundAdjustVolume: 'false' | chaperoneShowDashboardEnabled: 'true' | disableChaperone: 'false' | defaultheightToggleOffset: '-1.000000' | gravityStrength: '9.800000' | flingStrength: '1.000000' | brightnessOpacityValue: '0.000000' | colorOverlayOpacity: '0.000000' | colorRedNew: '1.000000' | colorGreenNew: '1.000000' | colorBlueNew: '1.000000' | chaperoneSwitchToBeginnerDistance: '0.500000' | chaperoneHapticFeedbackDistance: '0.500000' | chaperoneAlarmSoundDistance: '0.500000' | chaperoneShowDashboardDistance: '0.500000' | fadeDistanceRemembered: '0.500000' | defaultkeyboardOne: '^>m' | keyboardTwo: '^>m' | keyboardThree: '^>m' | defaultsnapTurnAngle: '4500' | smoothTurnRate: '100' | dragComfortFactor: '0' | turnComfortFactor: '0' | frictionPercent: '0' | debugState: '0' | customTickRateMs: '20' | alarmHour: '0' | alarmMinute: '0' | 
[INFO] 2020-01-28 16:37:07: Command line arguments processed.
[ERROR] 2020-01-28 16:37:07: Failed to initialize OpenVR: Interface Not Found (105)

**Comment by tails1972** [comment]
here is the steamvr logs for vrclient_advancesettings
Tue Jan 28 2020 16:51:30.241 - //==============================================================================================
Tue Jan 28 2020 16:51:30.241 - ================================================================================================
Tue Jan 28 2020 16:51:30.241 - ================================================================================================
Tue Jan 28 2020 16:51:30.241 - AdvancedSettings.exe 1.6.10 startup with PID=1616, config=C:/ProgramData/Steam/config, runtime=C:\Program Files (x86)\SteamVR
Tue Jan 28 2020 16:51:30.242 - vrclient type=VRApplication_Overlay
Tue Jan 28 2020 16:51:30.244 - Skipping external driver C:\Program Files (x86)\Steam\steamapps\common\SteamVRKnucklesDriver because it is not a directory
Tue Jan 28 2020 16:51:30.245 - [Settings] Load Default Json Settings from C:\Program Files (x86)\SteamVR\drivers\htc\resources\settings\default.vrsettings
Tue Jan 28 2020 16:51:30.245 - [Settings] Load Default Json Settings from C:\Program Files (x86)\SteamVR\drivers\lighthouse\resources\settings\default.vrsettings
Tue Jan 28 2020 16:51:30.245 - [Settings] Load Default Json Settings from C:\Program Files (x86)\SteamVR\drivers\null\resources\settings\default.vrsettings
Tue Jan 28 2020 16:51:30.245 - [Settings] Load Default Json Settings from C:\Program Files\DisplayLink XR\displaylink\resources\settings\default.vrsettings
Tue Jan 28 2020 16:51:30.246 - [Settings] Load Default Json Settings from C:\Program Files (x86)\SteamVR\resources\settings\default.vrsettings
Tue Jan 28 2020 16:51:30.246 - [Settings] Load Json Settings from C:\ProgramData\Steam\config\steamvr.vrsettings
Tue Jan 28 2020 16:51:30.255 - CSharedResourceNamespaceClient::Init(): received namespace data 5680
Tue Jan 28 2020 16:51:30.263 - Received success response from vrserver connect
Tue Jan 28 2020 16:51:30.264 - Not looking for a good app key because Steam didn't start this app
Tue Jan 28 2020 16:51:30.264 - App key after connect message:ovras-team.advancedsettings
Tue Jan 28 2020 16:51:30.274 - Received success response from vrcompositor connect
Tue Jan 28 2020 16:51:30.274 - Initializing the limited version of CVRCompositorClient
Tue Jan 28 2020 16:51:30.283 - VR_Shutdown called

**Comment by username223** [comment]
> I noticed that the manifest.vrmanifest doesn't have a open with programme attached to it, wondering if that is causeing the issue.

This is not the issue. The `.vrmanifest` files are just simple text files, you can open it with any text editor.

I don't have experience with HTCs offline SteamVR version, but I think it's out of date. Can you write what it says in `SteamVR -> Help -> About SteamVR`?
____

On our side the issue is in `initializeProperly()` of the `openvr_init.cpp` file. We call `vr::VR_Init( &initError, initializationType );` which calls `VRToken() = VR_InitInternal2( &eError, eApplicationType, pStartupInfo );`. The function is defined [here](https://github.com/ValveSoftware/openvr/blob/39205f6b281a6131d1373d0217c1ab9ed19735ea/src/openvr_api_public.cpp#L56) and it calls `VR_LoadHmdSystemInternal()` which I believe errors out around 
```cpp
int nReturnCode = 0;
g_pHmdSystem = static_cast< IVRClientCore * > ( fnFactory( vr::IVRClientCore_Version, &nReturnCode ) );
if( !g_pHmdSystem )
{
	SharedLib_Unload( pMod );
	return vr::VRInitError_Init_InterfaceNotFound;
}
```

**Comment by tails1972** [comment]
Ok i was just about to add i just got it to work by updateing to SteamVR 1.8.2, before i was on 1.6.2

So i suppose i can close this issue?
