### ISSUE TITLE
Unable to do Push to Talk or Push to Mute

### ISSUE THREAD

**Issue by idle-Mercy** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#360]
**Describe the bug**
I installed the latest version of OpenVR Advanced settings and wanted to try push to talk out for the first time. I go to set it up, and it says I have to set the bindings in steam vr bindings menu...
I go to steamvr binding and there's no option for push to talk. I'm kind of new to steam and all that good stuff, but it can't be that hard, can it?

**To Reproduce**
1. OpenVR ADV
2. Click on 'Push-TO-tALK'
3. SEE "Change the ptt settings in the steamVR Bindings Menu
4. Go to steamVR controller bindings
5. See no option to set up ptt

**Expected behavior**
To be able to activate push to talk, or have more instructions on how to do so.

**Screenshots**
![image](https://user-images.githubusercontent.com/52788111/73714461-f37d9880-46de-11ea-9bc6-8ace0f1aa85f.png)

**Software (please complete the following information):**
 - OS: Windows 10
 - Advanced Settings Version: 4.0.1

**Hardware (please complete the following information):**
 - CPU: AMD Ryzen 5 2600
 - Graphics Card: GTX 1660ti
 - HMD: HTC Vive

**Additional context**
I'd love if you could tell me if it's a bug, or if I'm not doing it right...and if the latter, explain how to do it...like I'm an 8 year  old with step-by-step instructions. I'm ok with installing mods and stuff, I just have no idea where to go from the initial keybind page. I've clicked everything.

**Comment by idle-Mercy** [comment]
Tried switching to steam vr beta, no luck. I saw a push to talk button in the bindings, but binding it to a button doesn't work either. Check the ptt box, the mic stays off, un-check it, it stays on. But the bindings don't do a thing.

**Comment by username223** [comment]
If you enable `Push to Mute` in the Audio tab, does an icon show up in your headset?

**Comment by ykeara** [comment]
So a couple of things.

1. the PTT functionality will never work while the dashboard is up, this is a limitation to steamvr
2. The push-to-talk binding is under the "misc" action set https://i.imgur.com/ZgM0zSi.png (see tabs at top)
3. if you still have issues you might try turning off the proximity sensor option.

**Comment by idle-Mercy** [comment]
So, I just have to try it while in the game, not while I'm out in SteamVR place or viewing my desktop from within the headset? I had only tried to test it by looking at OBS and seeing if the mic would record when I pressed the ptt buttons. I did bind it to Up on the track pad in MISC, so I'll try recording a game and seeing if it works in game. I didn't do it under beat saber bindings, but under misc which I assume is a general  bindings area. (Only know how to get to that from openvr adv settings, haha) I'll try and see. 

Also...the push to talk, it isn't for in game voice only, is it? I'd like it to fully mute and fully unmute the headset mic so when I'm recording a game of beat saber, you don't hear my breathing, but when I press the button on the controller and hold it down, I can talk. 

But also if I ever do play another game that has chat capabilities, I'd like to be able to do the ptt if I need to, but that's not AS necessary  since I won't really need to mute my mic quickly for any reason.

**Comment by idle-Mercy** [comment]
> If you enable `Push to Mute` and `Push to Talk` at the same time in the Audio tab, does an icon show up in your headset?

Where in the headset should that show up? While I'm in a game itself? I just got home, so I guess I'll turn on vr now, haha. Was planning on doing it in the morning, but now curiosity is getting to me, haha.

**Comment by username223** [comment]
> So, I just have to try it while in the game, not while I'm out in SteamVR place or viewing my desktop from within the headset?

A current limitation of the bindings system is that it can't activate while the overlay menu is up (the one containing the little Advanced Settings circle). It doesn't matter which environment/game you're in, so if you're just playing Beat Saber it works from there.

> I did bind it to Up on the track pad in MISC, so I'll try recording a game and seeing if it works in game.

I'm not sure how well the trackpads work for something like Push to Talk. Try binding it to the trigger or something that you definitely know is activated for testing.

> I didn't do it under beat saber bindings, but under misc which I assume is a general bindings area.

That's the correct way.

> Also...the push to talk, it isn't for in game voice only, is it?

When Push To Talk is activated, the microphone is muted directly in Windows.

> Where in the headset should that show up? While I'm in a game itself?

Yes, the top right corner of your field of view. You can't miss it if it shows up.

**Comment by idle-Mercy** [comment]
Thank you for all your help! 

Is there a way to get it to be set for some games and not for others? (I totally don't mind disabling it and re-enabling it if need be, just worth a check)

**Comment by ykeara** [comment]
We don't have any game profiles, so you will have to either un-bind it or un-check the ptt option manually currently for each session.

As issue appears to be solved going to close out issue.
