### ISSUE TITLE
Font DPI on linux makes text odd

### ISSUE THREAD

**Issue by feilen** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#369]
Adding before I forget:

**Describe the bug**
I have my DPI set to 113 on Xubuntu 19.10, also experienced with 18.04. All of the dashboard items are about in their right place, but the text is oversized.
**Screenshots**
![image](https://user-images.githubusercontent.com/1109288/75949785-250f8e00-5e5c-11ea-8882-3ad78244e7b7.png)
![image](https://user-images.githubusercontent.com/1109288/75949864-61db8500-5e5c-11ea-9919-e2917aef5de5.png)

**Software (please complete the following information):**
 - OS: Ubuntu 19.10
 - Advanced Settings Version: 4.0.1-git

From digging, I believe this can be solved by setting QAppilcation::setAttribute(Qt::AA_Use96Dpi) before launch, I'll try it when I get a chance.

**Comment by ykeara** [comment]
Fixed in #370
