### ISSUE TITLE
Offer Linux binaries for releases

### ISSUE THREAD

**Issue by username223** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#37]
Despite the low number of SteamVR Linux users and lack of Linux specific features offering a compiled binary with installer would make things easier for Linux users and increase adoption.

For starters, a very simple setup containing the binaries and necessary license and lib files would do.

The installer could just be a bash script.

The implementation should probably be a build script similar to `build_windows.cmd` that builds and packages the application.

**Comment by username223** [comment]
After looking into it, even a build script with error correction for more than one platform is a relatively big undertaking for relatively little gain.

It does not seem possible to install Qt and compile from Windows Subsystem for Linux, hence it is very difficult for me to test anything.

According to @icewind1991, the [SUSE Open Build Service](https://build.opensuse.org/) does a good job of creating multi platform packages.

Another alternative could be the Qt Installer Framework that is also cross platform, however with the deprecation of the regular Windows installer coming with the jump to Steam, it might not be worth spending the time to create an installer.

The issue will remain open, but will not be ready for 2.8.0.

**Comment by username223** [comment]
The `res` folder is currently required to be at `/home/myname/.local/share/AdvancedSettings-Team/OpenVRAdvancedSettings/res`, at least on DebianTesting.

**Comment by username223** [comment]
The action manifest, action manifest defaults and `.vrmanifest` must also be in the `/home/myname/.local/share/AdvancedSettings-Team/OpenVRAdvancedSettings/res` folder.

**Comment by username223** [comment]
As of #122 it is now possible to install manifests on Linux.

**Comment by username223** [comment]
AppImages along with [linuxqtdeploy](https://github.com/probonopd/linuxdeployqt) are considered for shipping binaries with Qt included.

**Comment by SupraLP** [comment]
one alternative for packaging would be snap packages. They contain dependencys and work on any linux distro like an AppImage. https://snapcraft.io/build

**Comment by username223** [comment]
AppImages are now being created on CircleCI.

These will serve as Linux binaries.

Currently, other formats are not being considered due to massive time investment for very little gain.
