### ISSUE TITLE
Flux style blue light filtering Night Mode

### ISSUE THREAD

**Issue by swilliams-dev** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#371]
**Is your feature request related to a problem? Please describe.**
The amount of blue light generated by a VR headset signals to the brain that it is still daytime. While it is possible to color correct this in Advanced Settings, it cannot be done automatically to mimic day/night hours.

**Describe the solution you'd like**
The ability to change color profiles based on time of day. Ideally there would be a default template available to automatically reduce blue light between certain hours. If it could fade between one color value to another over a given length of time, it would emulate sunset which would promote healthier sleep.

**Describe alternatives you've considered**
Permanently or manually reducing blue levels. This would require setting up alarms and would be disruptive.  ... Although an Alarm in general would be nice ... ( not suggesting scope creep or anything ;) )

**Additional context**
See the product Flux for examples of this in the wild. All major smartphone manufacturers also include this feature, and those devices are providing much less light to the eyes than a VR headset.

**Comment by egemenertugrul** [comment]
I think I've got you covered: https://github.com/egemenertugrul/LuxVR

**Comment by username223** [comment]
Thanks for the excellent PR.

Fortunately the tool already exists as mentioned by @egemenertugrul. :)

**Comment by guysoft** [comment]
Hey, I have managed to get OpenVR-Advanced-Settings working on Linux, but not LuxVR. So still relevant.
Related:
https://github.com/egemenertugrul/LuxVR/issues/1
