### ISSUE TITLE
Motion Tab UI adjustment

### ISSUE THREAD

**Issue by ykeara** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#372]
### Why?

With a few possible upcoming features that will add to the motion tab (re-directed walking, possibly selected tracked devices) We have a need to modify the UI and make more space. Two possibilities, will be discussed, Additional Options can be discussed as well.

## Option 1: Advanced Options

The general ideais to massively re-work the UI by removing low priority/use items, to a sub-menu of advanced options, while still providing all features and usually adjusted features at first page.

![Advanced Options](https://i.imgur.com/Q8u4e66.png)

### Pros
-  should be minimal amount of depth per session

### Cons
-  breaks up some features to multiple locations, that being said these features are used in-frequently/by advanced Users.

## Option 2: Lesser Used (by clicks/session) Moved to secondary page.

The general idea of this option is to keep the most used features front and center and obscuring lesser used features behind another click.

![Lesser used](https://i.imgur.com/UmwPkoO.png)

### Pros
-  Features are kept logically together

### Cons

- Some features are obscured, may be harder for new users to find/realize they exist, and could cause some panic for existing users that use the features.

## Other Alternatives

-  Motion 2 Tab, I don't think this is a good option, because it limits future expandibility in current framework, and looks sloppy.

- Moving some features to Offset Tab, I don't think this is a good option because increase in amount of tabs altered, and Offset tab would require a decent bit of re-work.

### My Opinions

My opinion is for Option 1, I think it benefits existing users the most by reducing amount of clicks needed, and doesn't obscure features for new users, it might not make quite as much logical sense, but most of the advanced features don't need to be adjusted from defaults.

**Comment by username223** [comment]
I don't really use the motion options, so I have no opinion one way or the other.

**Comment by feilen** [comment]
I like Option 1 generally. I expect more people will use the Motion options when they can be automatic. I can't really advocate trying to settle on an exact idea of what we want until I'm more sure of what options we'll have, but we can get a general idea hashed out.

A question though: Now that I think about it, what are the space turn/drag left/right hand checkboxes for? Aren't those essentially determined by your binds?

**Comment by Kung-vr** [comment]
I'm against removing a lot of the convenience buttons (planet gravity settings, snap turn angle buttons), or hiding existing things too deep (whole gravity section)

I suggest separating motion and rotation to different pages accessible on the root sidebar. All rotation related features should be moved to a new "Rotation" page. So: space/snap/smooth/auto turn goes on the Rotation page. Space Drag, Height Toggle, Gravity, (not shown here Friction) stay on the Motion page. this would free up a lot of space and also give some added conceptual clarity to rotation vs moving things. Both pages would have a button that would go to a new 2nd layer deep devices config (shared) page where it would be possible to select a reference device for Space Drag (right/left) Turn (right/left) and possibly Universe Pivot (currently always set to hmd location).

Hopefully this would leave enough space on the main rotation page to allow text entry and check-boxes for various auto turn options, but I could see Auto Snap/Smooth Turn needing another sub page if a lot of options are needed.

> A question though: Now that I think about it, what are the space turn/drag left/right hand checkboxes for? Aren't those essentially determined by your binds?

Those are there for two reasons: It allows us to have default binds for them while not suddenly surprising new users by their activation, requiring them to purposely go into the menu to turn on. It also allows responsive activation/deactivation when the function is wanted in one game, but is interfering in another. This is technically possible by removing the bind in steamvr input, but the steamvr interface there isn't very responsive and you need to drill down through multiple dialogues. So a quick toggle was needed.

**Comment by feilen** [comment]
Without anything else to go on, I think the best step for now would be to create a new tab for all the features I'm adding (automatic turn/snap, space extender) and put everything there, and we can change things as needed once we've got a better idea of what we want?

**Comment by ykeara** [comment]
Going w/ Kung's suggestion, it does make logical sense, we have room, and the Room Turn setttings take up ~40-50% of a tab so it makes sense to just have it set.
