### ISSUE TITLE
Floor chaperone bounds not staying behind using space turn

### ISSUE THREAD

**Issue by Gromit97** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#377]
**Describe the bug**
I have the chaperone set up, I have centre marker and play space ticked, I move using space turn the floor to ceiling grid moves ok, but the centre marker and play space markings on the floor (the ones I have ticked in chaperone settings) stay where they are and don't follow where I walk.
I tried messing around with other stuff to see if it was me but could not fix it, did something wrong tripped on PC tower fell into my £1050 Samsung ultra wide and broke it :-( Doh so when you hear of things going wrong in VR I'm sure you will remember that one I will. What you have created is amazing tho really something.

**To Reproduce**
1. Go to '...'chaperone settings
2. Click on '....'check centre marker box and floor bounds box (this will put the play space square on the floor with the centre box)
3. Scroll down to '....'move around using space turn
4. See error floor bounds and centre bounds stay where you started off.

**Expected behavior**
The floor bounds box and the centre marker sould follow the floor to ceiling chaperone bounds (the blue grid)

**Screenshots**
Not sure how to screen shot but if you need one let me know I'll learn

**Software (please complete the following information):**
 - OS: Windows 10
 - Advanced Settings Version: 4.0.1

**Hardware (please complete the following information):**
 - CPU: i9 9900K
 - Graphics Card: Gigabyte Aorus 1080ti waterforce
 - HMD:  Vive pro with wireless

**Additional context**
Keep up the good work your cleaver people +++++++

**Comment by Thynix** [comment]
Oh no! Sorry to hear you damaged hardware.

You can screenshot the chaperone bounds by taking a screenshot of your screen with the headset mirror open. I would expect that you can set a custom binding for Windows+Printscreen in the [Utilities tab](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#--utilities-page) and then find the screenshots under `Pictures/Screenshots` in your user directory.

**Comment by Gromit97** [comment]
Sorry I meant the floor bounds are staying behind, but I have looked into this and it appears that only the chaperone floor to ceiling box moves the actual box on the floor stays where it is, hopefully this will be added at some point tho. As for the damage, thanks and I should of moved slower.
Thanks Darren

**Comment by ykeara** [comment]
Right This can be considered resolved,  new center marker moves w/  our movements now, we don't move the "play-space" but that is a somewhat intentional decision.
