### ISSUE TITLE
Can't open SteamVR settings

### ISSUE THREAD

**Issue by sneakyjoeru** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#384]
I used to have installed a version from around a year or more ago. Currently I have this issue:

When my HMD isn't connected it flashes settings like crazy and doesn't react to anything:
https://imgur.com/a/QEjvuWM

When HMD is connected I can't access the menu - it's just white window.
https://imgur.com/a/uLPwD7g

**To Reproduce**
1. Open Steam VR,
2. Click Settings.

**Expected behavior**
Settings window opened

**Screenshots**
https://imgur.com/a/QEjvuWM
https://imgur.com/a/uLPwD7g

**Software (please complete the following information):**
 - OS: Windows 10
 - Advanced Settings Version: 4.0.1

**Hardware (please complete the following information):**
 - CPU: Ryzen 7 1700x
 - Graphics Card: Nvisia 2080
 - HMD: Oculus Rift

**Additional context**
The issue started a while ago, but I didn't bother - now it blocks me from playing HL Alyx. 
I tried reinstalling Steam, Reinstalling SteamVR, installing and removing 2.5 and 4.0.1 advanced settings. 
Cleared some files from %appdata% - nothing helped.

**Comment by ykeara** [comment]
when you un-installed OVRAS did the issue go away?. If it persists when OVRAS is uninstalled you should submit a bug-report to steam directly or open a support ticket w/ valve/steam

https://steamcommunity.com/app/250820/discussions/3/ (bug reports) or https://steamcommunity.com/app/250820/discussions/2/ (troubleshooting).

Off the top of my head I don't think OVRAS should be causing this, but sometimes weird stuff happens.

**Comment by sneakyjoeru** [comment]
It persists whenI uninstall it. 
I also contacted Steam support but they weren't helpful so far.

I contact here because of that Reddit post and comment on it about the same issue.
https://www.reddit.com/r/SteamVR/comments/fnpxi7/cant_access_settings_tried_reinstallation/

**Comment by ykeara** [comment]
Going to close out issue, I believe issue is not on our end especially as you did a clean install of SteamVR.

When you un-install OVRAS it removes many settings, but does not reset the SteamVR settings. that being said those should not persist through a steamvr re-install.... and you could make doubly sure by deleting the `steamvr.vrsettings` file in `C:\Program Files (x86)\Steam\config` (by default).

That being said it could be an edge case based on some sort of bug with the API. If more people exhibit the issue, or there is some sort of starting point Will re-open the issue. Sorry couldn't be of more hep.
