### ISSUE TITLE
Action Set opportunity to change

### ISSUE THREAD

**Issue by ykeara** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#388]
# Discussion on Action Sets for 5.0.0

## Explained
With 5.0.0 we are doing a complete breaking change, where settings and bindings will BOTH be reset. This gives us an opportunity to add/re-arrange actions w/o additional repercussions to existing User base.

### No new action sets
- New Auto-Turn/Redirected walking Actions will be added to Existing Motion Tab
- New  Exclusive input action "shift-key/xor" will be added to haptics
  - All existing keys in there are essentially "system" level keys that should never be disabled

### Split Motion Action Set Into "Motion" and "Rotation"

- Existing snapturn/smooth turn/ space turn moved into new Action set under "Rotation"
- New Rotation actions will be added to Rotation Tab

### Re-name "Haptic" action set to better identify with its role.

Currently the Haptic Action-set has unique keys like the prox sensor, and haptics that really should not be modified by the average user, and a better name may enforce that.

## My thoughts.

Proposal 1 makes the most sense, will lead to the least amount of confusion for the user-base, while not being completely out of whack, the only "issue" is the somewhat large number of people using. As per side proposal, I would not do it, it adds un-necessary work, and possibly user confusion for those that use the artificial "clicks"

## Additional Changes

- Defaults - Any default setting changes should be taken note of.
- Default keybinds - again rare opportunity to change w/o repercussion.
- Other Options/proposals?

**Comment by feilen** [comment]
If I'm understanding this correctly, I don't think proposal 2 makes terribly much sense. Space turn/drag/autoturn are all, really, 'displacement' options, they all fit in the same space logically. They just don't fit on the one page in the settings.

**Comment by username223** [comment]
Agreed with @feilen.

**Comment by ykeara** [comment]
Any real comments on a shift/xor bind. or the haptic action set as a whole?

**Comment by username223** [comment]
Which specific actions would be in the XOR set?

**Comment by ykeara** [comment]
its haptics, the prox sensor, and the simulated "clicks"

**Comment by username223** [comment]
Interestingly, the Onward action manifest includes the line
```json
  "action_sets": [
    {
      "name": "/actions/Onward",
      "usage": "single"
    },
    {
      "name": "/actions/Hidden",
      "usage": "hidden"
    }
  ],
```
It might be possible to entirely hide the haptics/prox sensors?

The actions don't seem to need changing.
```json
    {
      "name": "/actions/Hidden/in/BlockoutPullIn",
      "type": "boolean",
      "requirement": "optional"
    },
    {
      "name": "/actions/Hidden/in/BlockoutPushOut",
      "type": "boolean",
      "requirement": "optional"
    },
    {
      "name": "/actions/Hidden/in/BlockoutRotate",
      "type": "boolean",
      "requirement": "optional"
    },
    {
      "name": "/actions/Hidden/in/BlockoutDelete",
      "type": "boolean",
      "requirement": "optional"
    }
  ],
```
