### ISSUE TITLE
Setting to Tie Center Marker Visibility to Visibility of Chaperone Bounds

### ISSUE THREAD

**Issue by MRock004** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#390]
**Is your feature request related to a problem? Please describe.**
Often times in VR games I want to examine something on the ground I'm standing over but the center marker, while very useful for finding the center of the room when I need to, makes this action difficult as it gets in the way and makes things wonky since it renders over the top of all the game graphics and the VR controllers

**Describe the solution you'd like**
I would like to propose a simple setting that might fix this.  What if you make the center marker disappear when you're standing on it.  Maybe it could be set to a more sensitive triggered distance so that when you're directly on it you see no center marker or chaperone bounds.  Then If you stray to the halfway point between the center marker and the trigger that makes the chaperone bounds visible, the center marker becomes visible.  And, of course, if you stray further and reach the distance trigger for the chaperone bounds to appear, they do so.

**Describe alternatives you've considered**
An alternative to this (or possibly in addition to the above) would be to provide some other options for the way the marker looks; perhaps a less intrusive dot or circle that you could control the size of. 

**Additional context**

**Comment by ykeara** [comment]
Should be tied in now I think XD closing issue
