### ISSUE TITLE
Cleanup improvements (todo)

### ISSUE THREAD

**Issue by feilen** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#396]
- Calls to std::sqrt(std::pow(x, 2.0), std::pow(y, 2.0)) (and similar with 3-arguments) can be converted to std::hypot(x,y)
- ~~Need a __attribute((warn_unused_result)) macro to use on any function returning a success/fail condition (bool or success/fail enum), can prevent a lot of ugly cases~~ (already taken care of with [[nodiscard]] barring one or two cases)
- ~~Consider explicitly enabling sse2 support~~ (#398)
- ~~Consider increasing default compiler optimization to -O3~~ (#397)
- ~~Consider enabling link-time optimization~~ (#398)
- Use "CONFIG += ltcg" for link-time optimization on GCC and Clang, instead of manually passing build flags

**Comment by username223** [comment]
> Need a __attribute((warn_unused_result)) macro to use on any function returning a success/fail condition (bool or success/fail enum), can prevent a lot of ugly cases

C++17 provides the `[[nodiscard]]` attribute which works with the main compilers we're using.

> Consider explicitly enabling sse2 support

I'll look into it, although CPU features aren't really my area of expertise, so I might need some help.

> Consider increasing default compiler optimization to -O3

This should be relatively simple, I'll look into it.

> Consider enabling link-time optimization

LTO is used on Windows, I'll look into enabling it on Linux as well.

**Comment by username223** [comment]
I looked into SSE2 and it seems to be enabled by default on 
[MSVC](https://docs.microsoft.com/en-us/cpp/build/reference/arch-x64?view=vs-2019):
`The default mode uses SSE2 instructions for scalar floating-point and vector calculations.`

and [GCC](https://gcc.gnu.org/onlinedocs/gcc-4.5.3/gcc/i386-and-x86_002d64-Options.html):
`For the i386 compiler, you need to use -march=cpu-type, -msse or -msse2 switches to enable SSE extensions and make this option effective. For the x86-64 compiler, these extensions are enabled by default. [...] This is the default choice for the x86-64 compiler.`

[Clang](https://stackoverflow.com/questions/50786263/does-compiler-use-sse-instructions-for-a-regular-c-code) seems to enable it even at `-O2`:
`Yes, modern compilers auto-vectorize with SSE2 if you compile with full optimization. clang enables it even at -O2, gcc at -O3.`

I'll get a PR up for LTO and O3 shortly.

**Comment by username223** [comment]
There are some issues with getting LTO up on CI. It works fine for GCC on CI, but clang requires the `gold` plugin, which does not seem to be present in the current compiler for some reason.

This made me realize that the CI setup is kind of a nightmare, and that I would like to change it to make more sense. I'll create a new issue and move LTO and O3 there, SSE2 should be considered fixed.

**Comment by feilen** [comment]
> Clang seems to enable it even at -O2:
> Yes, modern compilers auto-vectorize with SSE2 if you compile with full optimization. clang enables it even at -O2, gcc at -O3.

Yeah, the reason I'd want -O3 (on gcc) is pretty much just for the tree vectorization, we probably want that if we're doing a lot of floating point math.

> I'll create a new issue here and do LTO and O3 after that, SSE2 should be considered fixed.

Alright, I can update this bug to be more about cleanup then.

**Comment by feilen** [comment]
Added ltcg stuff
