### ISSUE TITLE
Redirected walking not working

### ISSUE THREAD

**Issue by Rexios80** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#411]
**Describe the bug**
I tried out redirected walking, but it does not seem to work correctly. My space auto-turns as I walk, but it keeps switching turning directions in such a way that I don't actually get any expanded walking distance. I hit my play space boundary at the same distance I would have anyways. I tried it on every radius setting, and even tried lower values than Extreme. The lower values do turn me more, but still it switches turning directions in such a way that the feature does not work.

**To Reproduce**
1. Turn on Redirected Walking
2. Walk in a straight line
3. Follow the redirection
4. Hit wall

**Expected behavior**
Redirected walking to actually redirect me away from my playspace boundary.

**Software (please complete the following information):**
 - OS: Windows 10
 - Advanced Settings Version: 5.0.0

**Hardware (please complete the following information):**
 - CPU: 3900X
 - Graphics Card: 2080Ti
 - HMD: Wireless Vive Pro (I do have an Index as well, but I did not test with it as it doesn't make sense for this application)

**Additional context**
I have a 4x5 meter play space, so this feature should work pretty well for me. I really hope we can figure this out because I'm really excited about this feature.

For even more context: I really want to be able to infinitely walk in a circle around the edge of my playsapce, and this feature doesn't seem to be able to do that right now. Auto-turning is close, but it's not as smooth as I would like.

**Comment by Reival83** [comment]
Hi. I'm testing it just now.
When I deactivate "Use corner angle" it works better for me.
I don't have a perfect square room, maybe it fails for this.

**Comment by Rexios80** [comment]
That setting is only for auto turning which works mostly fine for me. I did some more testing with redirected walking and it’s literally directing me into my wall when it could turn me the other way to avoid it.

**Comment by feilen** [comment]
Redirected walking is, for the moment, mostly intended to give you some increased space, not quite infinite turning yet (that's what autoturn is for). Your case sounds odd though. Is it directing you into the wall at corners, or anything special?

The way Redirected walking works is, it determines the angle by selecting the nearest point on the nearest wall you're walking _towards_, and then tries to turn away from it. So I guess in some weird cases this could angle you into a corner, but the only time it would go back and forth would be down the center of your space.

**Comment by feilen** [comment]
Actually... I just had a clue for how a dynamic auto-turn could work. Could be rather upsetting to your stomach but we'll see!

**Comment by Rexios80** [comment]
If I start in the middle of my play space and walk forward it doesn’t even seem to turn. Even on Extreme. If I walk from one end/corner of my play space to the other it turns one way then the other, but not enough in either direction for my play space to be at all bigger. I can use reference points in game and walk towards them and I’m not getting any further with redirection on or off.

Okay I did some further testing. I changed the radius to 0.5 and got it to actually do something sometimes, but it’s very inconsistent. Sometimes it will turn perfectly and actually extend my play space, and other times I’ll get close to a wall and it’ll turn me straight into it for no reason. Also it changes turn directions abruptly sometimes causing a bit of motion sickness (and I rarely ever get motion sick).

**Comment by Rexios80** [comment]
And hit me with a beta test for that dynamic auto-turn if you want to. It really takes a lot to get me motion sick. Especially after I get used to it.

**Comment by Rexios80** [comment]
And again if you want a video of the behavior I could record one for you. Although I think I remember reading that the overhead view in SteamVR is gone now so I'm not sure how I could make a useful video for you.

**Comment by feilen** [comment]
First person video + a video of you in third person might help? It should be extremely consistent, so if it's not, perhaps I'm calculating things wrong (or something's still wrong with how chaperone bounds are applied?)

And yeah, hop on our discord, I'll try hacking something together this weekend, though obviously I'd wanna know what's happening with your setup first

**Comment by feilen** [comment]
Fixed with #413
