### ISSUE TITLE
Offset profiles are invisible

### ISSUE THREAD

**Issue by Dman883** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#414]
Manually deleted previous version. 4.0.1
Installed new version 
When hitting the drop down list for offset profiles, the profiles are invisible. I had first thought they simply weren't there but was able to select or delete the invisible entries. Uninstalled and reinstalled several times. Reinstalled 4.0.1 and my profiles are back. (Keyboard shows up behind the active window though. It's always done that)

**Comment by ykeara** [comment]
5.0.0 Was a Breaking change, It broke saved settings and key-bindings, They cannot be trivially ported over you will have to re-make them. They are technically saved in a different File,  that is not deleted, so you still have your 4.0.1 settings, but they are independent of 5.0.x settings

If you look at the releases, they include documentation on how to properly migrate, from 4.0.1 -> 5.0.0 (or newer)

**Comment by Dman883** [comment]
I thought it was something like that. I don't care about migrating them. It's just a couple of presets that take seconds to make. Can you point me to the default folder location where these are saved? I looked at the .json file in the steamvr folder as mentioned in the uninstall info but it didn't say anything about advanced settings/openvr

**Comment by ykeara** [comment]
Advanced Settings log files, and settings are saved at %appdata%/AdvancedSettings-Team in Windows

**Comment by Dman883** [comment]
think I got it. Thanks.

**Comment by Dman883** [comment]
spoke too soon. Profiles aren't visible after after restarting game/vr. They're there, just not not visible. Any idea what would cause that?

**Comment by ykeara** [comment]
#419  is issue posted. Need to look into it.

**Comment by Dman883** [comment]
Problem solved. I did a comprehensive search for openvr and advanced settings and finally found the conflicting file/files needed deleting.
