### ISSUE TITLE
set brightness value below 10% (via direct text input)

### ISSUE THREAD

**Issue by mcproprot** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#419]
Since the last update it's not possible to turn the brightness back to 0% and that's a problem for me.
I sleep in VRC and have it usally set to like 3% brightness so it's not to bright to be able to fall asleep.
But it's really hard to pass out since I can't go lower than 10% brightness.
So it would be great if it would become a feature again or else I will need to downgreat to v.4

**Comment by ykeara** [comment]
I'll change it next update to allow it to be set to 1% (previous value minimum) via Direct Text Input only.
