### ISSUE TITLE
chaperone config too aggressive holding "preview" state.

### ISSUE THREAD

**Issue by sakkaku** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#420]
**Describe the bug**
After restarting steam vr, advanced settings reverts room setup.

**To Reproduce**
1. Enable redirected walking (this screwed up my room setup initially, hence why I'm trying to run setup again).  This step might not be needed to replicate but everything went wrong after this was turned on.
2. Run steam vr room setup (either with advanced settings running or shutdown)
3. Shutdown steam vr.
4. Relaunch steam vr without starting advanced settings.
5. Validate room config is correct.
6. Open advanced settings.
7. Notice your room setup has reverted and your head is now in the floor.

**Expected behavior**
Advanced settings honors new room setup and doesn't revert to a bad configuration.

**Software (please complete the following information):**
 - OS: Windows 10 PRO
 - Advanced Settings Version: 5.0.1 (Steam version)

**Hardware (please complete the following information):**
 - CPU: Ryzen 2700
 - Graphics Card: Geforce 1080
 - HMD: Valve Index

**Additional context**
I tried nuking various configurations of advanced settings, reinstalling the app, and it is persisting still.

**Comment by ykeara** [comment]
In Settings of ADV Settings check the box for "Disable Automatic Crash Recovery of Chaperone Config"

**Comment by sakkaku** [comment]
Toggling on "Disable Automatic Crash Recovery of Chaperone Config" seems to have done the trick.

**Comment by sakkaku** [comment]
Since my issue is fixed I'm going to close the issue.  But I would look into redirected walking causing room scale setup corruption since that threw me for a loop >_<

**Comment by sakkaku** [comment]
I just did a "revert all changes for this session" from the space fix menu and it ended up b0rking the setup again.

**Comment by ykeara** [comment]
I would advise you in the short term, to turn off ADV-Settings, Delete the settings file @ %appdata%/AdvancedSettings-Team/OVR Advanced Settings.ini, run room set-up, then re-enable Advanced Settings disable automatic recovery again.

Did you re-do Room-setup after turning off (And restarting) Automatic Crash recovery?
or some other order?

And then order of things you did to get to clicking "revert all changes"

If you could please post your log file (%appdata%/AdvancedSettings-Team/AdvancedSettings.txt)


The issue is related to "live" and "preview" chaperone views... and passing control back and forth between them, we have several elements that do them, so I'm just trying to figure out exactly where you are.

**Comment by sakkaku** [comment]
> If you could please post your log file (%appdata%/AdvancedSettings-Team/AdvancedSettings.txt)

[AdvancedSettings.log](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/4498270/AdvancedSettings.log)

> Did you re-do Room-setup after turning off (And restarting) Automatic Crash recovery? or some other order?  And then order of things you did to get to clicking "revert all changes"

1. I toggled the setting.
2. Ran room setup.  
3. Shutdown steam vr (I do this because I have reverted room setups before)
4. Restarted steam vr and validated that room configuration looked ok.  
5. Started a game (vrchat).  
6. Used the offset move tool
7. Reverted the offset with the space fix tool mentioned above, and noticed that the room config reverted.

**Comment by sakkaku** [comment]
I've tried nuking the directories %appdata%\AdvancedSettings-Team and %localappdata%\AdvancedSettings-Team before and it didn't fix the issue.

I think deleting wherever the chaperone information is cached might be a better idea.  I still haven't figured out where that is stored.

**Comment by ykeara** [comment]
C:\Program Files (x86)\Steam\config\chaperone_info.vrchap is where steam stores your chaperone file... (assuming default install)

**Comment by sakkaku** [comment]
That makes things 100x easier because I can stop rerunning the room setup >_<

Ok.  I think things are happy now because I'm not getting an unsafe shutdown warning any more.

[AdvancedSettings.log](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/4498297/AdvancedSettings.log)

The correct procedure seems to be:

1. Run room setup (optionally copy the chaperon config somewhere else so you can easily revert it if adv settings nukes it).
2. Shutdown steam vr.
3. Delete OVR Advanced Settings.ini
4. Start up steam vr and advanced settings is happy again.

**Comment by sakkaku** [comment]
Maybe the unsafe shutdown being detected prevented the new chaperon profiles from being loaded even when "Disable Automatic Crash Recovery of Chaperone Config" is enabled?

**Comment by sakkaku** [comment]
I think everything is on the up and up on my system now.  Thanks for your help.  

The only other thing that might be useful is the config file that was deleted. 

[OVR Advanced Settings.ini.txt](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/4498316/OVR.Advanced.Settings.ini.txt)

**Comment by ykeara** [comment]
There is now a Beta Live on Steam that should fix this issue, feedback is appreciated.
