### ISSUE TITLE
CHAPERONE OCULUS QUEST LINK 

### ISSUE THREAD

**Issue by steamvr3000** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#421]
I am using Quest Link in combination with Oculus Guardian Boundary Editor. When I load a profile from the quardian editior the Open VR Settings does not detect my guardian boundaries. It´s just a large circle on the ground where my quardian profile was in previous versions of OpenVR settings.

**Comment by ykeara** [comment]
I think this is related to #420 I would recommend looking at steps outlined there.

**Comment by ykeara** [comment]
There is now a Beta Live on Steam that should fix this issue, feedback is appreciated.

**Comment by steamvr3000** [comment]
Hello,

i haven´t tried the beta yet but I tried 5.01. Your solution seems to work but only for a few Minutes, afterwards that Quest went black. I have no idea if it is the new open VR settings or something else which caused it. I will try it within the next days (most probalby saturday) again and sent you feedback.

kind regards
________________________________
Von: ykeara <notifications@github.com>
Gesendet: Montag, 20. April 2020 10:44
An: OpenVR-Advanced-Settings/OpenVR-AdvancedSettings <OpenVR-AdvancedSettings@noreply.github.com>
Cc: steamvr3000 <steam.vr@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings] CHAPERONE OCULUS QUEST LINK (#421)


Closed #421<https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/issues/421> via #422<https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/pull/422>.

**Comment by ykeara** [comment]
Curious to see how it behaves on 5.0.2 should be.

That bieng said oculus boundary editor is no longer supported? based on quick google. could be un-related, but I would have to say check if ovras works w/o boundary editor. you may need to check "allow external chapperone edits" in settings of OVRAS for it to work decent.

**Comment by steamvr3000** [comment]
Hello,

I tried it today, version 5.02. No issues! I played for more than one hour flawlessly. I did not changed anything in the options. Just installed it and started Oculus and Steam. Works great now. No interruptions.

Thanks for the programm and your work on it.

If I find anything suspicious I will let you know.

kind regards

________________________________
Von: ykeara <notifications@github.com>
Gesendet: Dienstag, 21. April 2020 13:17
An: OpenVR-Advanced-Settings/OpenVR-AdvancedSettings <OpenVR-AdvancedSettings@noreply.github.com>
Cc: steamvr3000 <steam.vr@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings] CHAPERONE OCULUS QUEST LINK (#421)


Curious to see how it behaves on 5.0.2 should be.

That bieng said oculus boundary editor is no longer supported? based on quick google. could be un-related, but I would have to say check if ovras works w/o boundary editor. you may need to check "allow external chapperone edits" in settings of OVRAS for it to work decent.
