### ISSUE TITLE
Reword Redirected walking feature titlebars (Auto-turn, 'redirected walking' and space turn)

### ISSUE THREAD

**Issue by feilen** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#425]
When Auto-turn and redirected walking first debuted, there was a ton of confusion as to which was used for infinite-walk (with people trying redirected walking and not being able to walk very far, when auto-turn is more suited for that). In actuality, all of these features are some implementation of [Redirected Walking](https://en.wikipedia.org/wiki/Redirected_walking) and should have some mention of that. In order to make things less confusing, we ended up adding 'aka infinite walk' to auto-turn's title bar, but it's not quite right and doesn't really follow industry terms.

As discussed in chat, the most agreeable (for the moment) change would be to change the following titlebars from
- Auto-turn (aka infinite walk) Settings
- Redirected walking
- Space-turn

to something like 
- Auto-turn Settings (for discrete redirected walking)
- Vestibular motion (?) (for gradual redirected walking?)
- Space-turn (for manual redirected walking)

More input here, any suggestions/comments?

**Comment by Kung-vr** [comment]
Those sound good to me! For consistency you could remove "Settings" after Auto-turn so that it's just "Auto-turn (for discrete redirected walking)" but I'm ok with it there too, either way.

**Comment by ykeara** [comment]
@Kung-vr @feilen  I set "Vestibular Motion (for continuous redirected walking)"
followed Other Advice though.
I think that makes most sense? but If I need to change holler, committing changes on my current working branch.

And I suppose do we want `Space-Turn Settings (...)` or `Space-Turn (...)`
