### ISSUE TITLE
No display.

### ISSUE THREAD

**Issue by dynamojake** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#428]
**Describe the bug**
So I'm trying to use the Advanced Settings and I keep having the same issue:

Each time I open vr either through steam or through the application in the OpenVR Advanced Settings folder, I am given the cog icon to access the settings, but upon clicking that button, I am greeted with a blank screen.

I have tried so far:
Deleting and re-installing.
Running the instillation twice over.

Would be nice to have a little help, Thanks!

Edit: I am attempting to use the 5.0.2 version.

**To Reproduce**
1. Install.
2. Open VR.
3. No display of options.

**Expected behavior**
Explained above.

**Screenshots**
![image](https://user-images.githubusercontent.com/33065980/80278490-a2ce7800-86ee-11ea-9a1f-266553899e15.png)

**Software (please complete the following information):**
 - OS: Windows 10
 - Advanced Settings Version: 5.0.2

**Hardware (please complete the following information):**
 - CPU: I7 6700k
 - Graphics Card: Radeon 5700 XT 
 - HMD: Vive.

**Comment by username223** [comment]
Thank you for creating an issue, a few questions first:

* Are you running multiple GPUs?

* If you go into the SteamVR status window > Developer > Overlay Viewer and select the OVRAS overlay, what do you see? You might need to enable developer settings in the settings.

* In `%appdata%\AdvancedSettings-Team` there's a logfile, could you paste the contents of it here?

**Comment by dynamojake** [comment]
Sort of, I'm running the 5700 XT and using integrated graphics for my monitors as I only use this machine for VR. 

OVRAS Isn't an option in that menu.

The log file:

[AdvancedSettings.log](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/4532858/AdvancedSettings.log)

**Comment by ykeara** [comment]
So you can try
https://www.digitalcitizen.life/set-which-video-cards-are-used-apps-games-windows-10 to set OVRAS to use your GPU.

It would also be helpful to see if you had monitors plugged  into your GPU and not IGPU if it behaved differently.

**Comment by ykeara** [comment]
@dynamojake  any update? no response I will close out in 7 days

**Comment by Off-Elia** [comment]
i had same issue, unistalling then reinstalling ovr BUT this time on the same drive "C" fixed my issue...
