### ISSUE TITLE
v5.0.1 Profiles do not save.

### ISSUE THREAD

**Issue by hatesigningup** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#430]
I was using version 4.0.1 and all was good, but since updating to 5.0.1 all my profiles are lost each time I quit steam VR and I have to re-create them each session.  Am I doing something wrong or is there a problem?

I uninstalled v4.0.1 before installing v5.0.1.

Thanks.

**Comment by ykeara** [comment]
Try 5.0.2 Specifically fixed an issue where we weren't saving names for offset and video profiles. the profiles in that case should still exist they were just blank lines in the box.

**Comment by ykeara** [comment]
Closing Out no Response, and believed to be resolved in 5.0.2.
