### ISSUE TITLE
Manjaro/Aur package not running

### ISSUE THREAD

**Issue by lllsondowlll** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#431]
**Describe the bug**
ovras Aur package fails to display the OpenVR Advanced Settings tab menu in SteamVR when executed. 
OS: Manjaro Linux
KERNEL: 5.4.33-3-MANJARO
CPU: Intel Core i7-8700K @ 3.70GHz
GPU: NVIDIA GeForce RTX 2080
GPU DRIVER: NVIDIA 440.82
RAM: 32 GB
HMD: VALVE INDEX
SteamVR: 1.11.11
PACKAGE: https://aur.archlinux.org/packages/ovras | 2020-04-20 18:03

P.S. the standalone AppImage functions correctly

**To Reproduce**
1. Go to 'pamac and search ovras'
2. Click on build and apply''
3. Go to terminal and execute ovras'
4. See error: 
`[INFO] 2020-04-26 19:46:51: Application started (Version 5.0.1-dev)
[INFO] 2020-04-26 19:46:51: Log File: /home/lllsondowlll/.local/share/AdvancedSettings-Team/AdvancedSettings.log
[INFO] 2020-04-26 19:46:51: Settings File: /home/lllsondowlll/.config/AdvancedSettings-Team/OVR Advanced Settings.ini
[INFO] 2020-04-26 19:46:51: defaultlockXToggle: 'false' | lockYToggle: 'false' | lockZToggle: 'false' | momentumSave: 'false' | turnBindLeft: 'false' | turnBindRight: 'false' | turnBounds: 'false' | moveShortcutLeft: 'false' | moveShortcutRight: 'false' | dragBounds: 'false' | allowExternalEdits: 'false' | oldStyleMotion: 'false' | universeCenteredRotation: 'false' | enableSeatedMotion: 'false' | adjustChaperone: 'true' | showLogMatricesButton: 'false' | simpleRecenter: 'false' | disableVersionCheck: 'false' | previousShutdownSafe: 'true' | vsyncDisabled: 'false' | crashRecoveryDisabled: 'false' | enableDebug: 'false' | pttEnabled: 'false' | pttShowNotification: 'false' | micProximitySensorCanMute: 'false' | micReversePtt: 'false' | alarmEnabled: 'false' | alarmIsModal: 'true' | vrcDebug: 'false' | brightnessEnabled: 'false' | isOverlayMethodActive: 'false' | colorOverlayEnabled: 'false' | chaperoneSwitchToBeginnerEnabled: 'false' | chaperoneHapticFeedbackEnabled: 'false' | chaperoneAlarmSoundEnabled: 'false' | chaperoneAlarmSoundLooping: 'true' | chaperoneAlarmSoundAdjustVolume: 'false' | chaperoneShowDashboardEnabled: 'false' | disableChaperone: 'false' | autoturnEnabled: 'false' | autoturnUseCornerAngle: 'true' | autoturnVestibularMotionEnabled: 'false' | defaultheightToggleOffset: '-1.000000' | gravityStrength: '9.800000' | flingStrength: '1.000000' | brightnessOpacityValue: '1.000000' | colorOverlayOpacity: '0.000000' | colorRedNew: '1.000000' | colorGreenNew: '1.000000' | colorBlueNew: '1.000000' | chaperoneSwitchToBeginnerDistance: '0.500000' | chaperoneHapticFeedbackDistance: '0.500000' | chaperoneAlarmSoundDistance: '0.500000' | chaperoneShowDashboardDistance: '0.500000' | fadeDistanceRemembered: '0.500000' | activationDistance: '0.400000' | deactivateDistance: '0.150000' | cordDetanglingAngle: '0.261799' | autoturnMinCordTangle: '6.283185' | autoturnVestibularMotionRadius: '11.000000' | defaultkeyboardOne: '^>m' | keyboardTwo: '^>m' | keyboardThree: '^>m' | defaultsnapTurnAngle: '4500' | smoothTurnRate: '100' | dragComfortFactor: '0' | turnComfortFactor: '0' | frictionPercent: '0' | debugState: '0' | customTickRateMs: '20' | alarmHour: '0' | alarmMinute: '0' | autoturnLinearTurnSpeed: '9000' | autoturnMode: '1' | 
[INFO] 2020-04-26 19:46:51: Command line arguments processed.
[INFO] 2020-04-26 19:46:51: OpenVR initialized successfully.
[INFO] 2020-04-26 19:46:51: VR Runtime Path: /home/lllsondowlll/.local/share/Steam/steamapps/common/SteamVR
[ERROR] 2020-04-26 19:46:51: Could not find activation sound file /home/lllsondowlll/.local/share/Steam/steamapps/common/SteamVR/content/panorama/sounds/activation.wav
[ERROR] 2020-04-26 19:46:51: Could not find focus changed sound file /home/lllsondowlll/.local/share/Steam/steamapps/common/SteamVR/content/panorama/sounds/focus_change.wav
[ERROR] 2020-04-26 19:46:52: Could not get recording override setting: VRSettingsError_UnsetSettingHasNoDefaultA clear and concise description of what you expected to happen.
[INFO] 2020-04-26 19:46:52: Setting recording override to false
[ERROR] 2020-04-26 19:46:52: Could not get playback override setting: VRSettingsError_UnsetSettingHasNoDefault
[INFO] 2020-04-26 19:46:52: Setting playback override to false
[WARNING] 2020-04-26 19:46:52: alpha value is invalid setting to 1.0
[INFO] 2020-04-26 19:46:52: OPENSSL VERSION: OpenSSL 1.1.1f  31 Mar 2020
[ERROR] 2020-04-26 19:46:52: QML Error: file:///opt/AdvancedSettings/res/qml/common/mainwidget.qml:2:1: module "QtQuick.Controls" is not installed

[WARNING] 2020-04-26 19:46:52: QTMSGH: QQmlComponent: Component is not ready`

OpenVR Advanced Settings tab does not appear in SteamVR menu

**Expected behavior**
OpenVR Advanced Settings tab should appear in SteamVR menu

**Comment by username223** [comment]
Thanks for the bug report.

We've had this problem before on Ubuntu due to an older Qt version.

Could you try getting the `qt5-quickcontrols` package from the AUR and then trying again?

And if that doesn't work could you give me a full list of installed Qt packages?

**Comment by lllsondowlll** [comment]
qt5-quickcontrols installed, ovras complained qt5.quickcontrols 2.0 was not installed. Uninstalled qt5-quickcontrols and installed qt5-quickcontrols2 and now it is complaining QtQuick.Dialogs is not found which I cannot find a standard pamac / aur package for.

`ovras
[INFO] 2020-05-02 12:54:01: Application started (Version 5.0.1-dev)
[INFO] 2020-05-02 12:54:01: Log File: /home/lllsondowlll/.local/share/AdvancedSettings-Team/AdvancedSettings.log
[INFO] 2020-05-02 12:54:01: Settings File: /home/lllsondowlll/.config/AdvancedSettings-Team/OVR Advanced Settings.ini
[INFO] 2020-05-02 12:54:01: defaultlockXToggle: 'false' | lockYToggle: 'false' | lockZToggle: 'false' | momentumSave: 'false' | turnBindLeft: 'false' | turnBindRight: 'false' | turnBounds: 'false' | moveShortcutLeft: 'true' | moveShortcutRight: 'true' | dragBounds: 'false' | allowExternalEdits: 'false' | oldStyleMotion: 'false' | universeCenteredRotation: 'false' | enableSeatedMotion: 'false' | adjustChaperone: 'true' | showLogMatricesButton: 'false' | simpleRecenter: 'false' | disableVersionCheck: 'false' | previousShutdownSafe: 'true' | vsyncDisabled: 'false' | crashRecoveryDisabled: 'false' | enableDebug: 'false' | pttEnabled: 'false' | pttShowNotification: 'false' | micProximitySensorCanMute: 'false' | micReversePtt: 'false' | alarmEnabled: 'false' | alarmIsModal: 'true' | vrcDebug: 'false' | brightnessEnabled: 'false' | isOverlayMethodActive: 'false' | colorOverlayEnabled: 'false' | chaperoneSwitchToBeginnerEnabled: 'false' | chaperoneHapticFeedbackEnabled: 'false' | chaperoneAlarmSoundEnabled: 'false' | chaperoneAlarmSoundLooping: 'true' | chaperoneAlarmSoundAdjustVolume: 'false' | chaperoneShowDashboardEnabled: 'false' | disableChaperone: 'false' | autoturnEnabled: 'false' | autoturnUseCornerAngle: 'true' | autoturnVestibularMotionEnabled: 'false' | defaultheightToggleOffset: '-1.000000' | gravityStrength: '9.800000' | flingStrength: '1.000000' | brightnessOpacityValue: '1.000000' | colorOverlayOpacity: '0.000000' | colorRedNew: '1.000000' | colorGreenNew: '1.000000' | colorBlueNew: '1.000000' | chaperoneSwitchToBeginnerDistance: '0.500000' | chaperoneHapticFeedbackDistance: '0.500000' | chaperoneAlarmSoundDistance: '0.500000' | chaperoneShowDashboardDistance: '0.500000' | fadeDistanceRemembered: '0.500000' | activationDistance: '0.400000' | deactivateDistance: '0.150000' | cordDetanglingAngle: '0.261799' | autoturnMinCordTangle: '6.283185' | autoturnVestibularMotionRadius: '11.000000' | defaultkeyboardOne: '^>m' | keyboardTwo: '^>m' | keyboardThree: '^>m' | defaultsnapTurnAngle: '4500' | smoothTurnRate: '100' | dragComfortFactor: '0' | turnComfortFactor: '0' | frictionPercent: '0' | debugState: '0' | customTickRateMs: '20' | alarmHour: '0' | alarmMinute: '0' | autoturnLinearTurnSpeed: '9000' | autoturnMode: '1' | 
qt5ct: using qt5ct plugin
[INFO] 2020-05-02 12:54:01: Command line arguments processed.
[INFO] 2020-05-02 12:54:02: OpenVR initialized successfully.
[INFO] 2020-05-02 12:54:02: VR Runtime Path: /home/lllsondowlll/.local/share/Steam/steamapps/common/SteamVR
[ERROR] 2020-05-02 12:54:02: Could not find activation sound file /home/lllsondowlll/.local/share/Steam/steamapps/common/SteamVR/content/panorama/sounds/activation.wav
[ERROR] 2020-05-02 12:54:02: Could not find focus changed sound file /home/lllsondowlll/.local/share/Steam/steamapps/common/SteamVR/content/panorama/sounds/focus_change.wav
[WARNING] 2020-05-02 12:54:02: alpha value is invalid setting to 1.0
[INFO] 2020-05-02 12:54:02: OPENSSL VERSION: OpenSSL 1.1.1f  31 Mar 2020
[ERROR] 2020-05-02 12:54:02: QML Error: file:///opt/AdvancedSettings/res/qml/common/mainwidget.qml:28:5: Type ChaperonePage unavailable

[ERROR] 2020-05-02 12:54:02: QML Error: file:///opt/AdvancedSettings/res/qml/chaperone_page/ChaperonePage.qml:4:1: module "QtQuick.Dialogs" is not installed

[WARNING] 2020-05-02 12:54:02: QTMSGH: QQmlComponent: Component is not ready
Segmentation fault (core dumped)
`

**Comment by username223** [comment]
Sorry for the late reply, it's a pretty difficult issue to diagnose when I don't have a Linux version to debug myself.

Could you give me an `ldd` on the binary?

> Uninstalled qt5-quickcontrols and installed qt5-quickcontrols2:

Are you unable to have them both installed at the same time?

**Comment by ykeara** [comment]
Closing out Issue seems to be dead.
