### ISSUE TITLE
Playspace mover not working

### ISSUE THREAD

**Issue by MrSir2552** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#433]
**Describe the bug**
I'm trying to get onto VRChat to hang out with some friends, but the playspace mover or even manual offset inputs are not working. I've tried restarting my computer multiple times, uninstalled and reinstalled but nothing has seemed to work.

**Software (please complete the following information):**
 - OS: Windows 10
 - Advanced Settings Version: 5.0.2

**Hardware (please complete the following information):**
 - CPU: i7 7700K
 - Graphics Card: GTX 1070
 - HMD: Oculus CV1 and controllers, Rift trackers

**Comment by sooTsi** [comment]
I'm having the same issues.

Software (please complete the following information):

    OS: Windows 10
    Advanced Settings Version: 5.0.2

Hardware (please complete the following information):

    CPU: E5-2698
    Graphics Card: GTX 1070x2
    HMD: Vive + Wireless, 3 HTC Trackers

**Comment by ykeara** [comment]
make sure you are set-up as roomscale (or have the seated motion override in setting checked). Other than that post your logs + settings from `%appdata%/AdvancedSettings-Team`

**Comment by MrSir2552** [comment]
The seated motion override worked, thank you very much.

**Comment by sooTsi** [comment]
Fixed as well, ty.

**Comment by jespertheend** [comment]
Where can I find this seated motion override? I'm having this issue where the space offsets screen gets replaced with `Tracking Universe: Unknown(2)` whenever I open a WebXR page in Chrome. But specifically [this page](https://immersive-web.github.io/webxr-samples/immersive-vr-session.html) in my case.

**Comment by Bluscream** [comment]
^ this
