### ISSUE TITLE
Controls randomly invert since installing this

### ISSUE THREAD

**Issue by ayoits0913** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#434]
I was using the old OpenVR Advanced Settings and everything was fine. Then I installed this, and while playing Half Life Alyx, the thumbsticks will randomly invert, I'm trying to walk toward something and it moves me backwards. I checked the bindings in the OVR settings and nothing is changed. I'm using the Odyssey+

**Comment by ykeara** [comment]
When you say old what was the previous version?

Are you using controller orientation based motion in HL:A?

would love to see our logs/settings @ %appdata%/AdvancedSettings-team/
and Steam's "vrserver.txt" in <steaminstalllocation>/logs/

You are first to report this that I know of, and we shouldn't do anything that effects controls in games... which leads me to believe its a bug w/ HL:A or SteamVR.... there is one possibility that we might be causing it.... but again would point to a bug in SteamVR we just cause it.... but its curious.

**Comment by ayoits0913** [comment]
My bad it was a settings issue in HL Alyx I changed by accident, all good now
