### ISSUE TITLE
Write Wrappers for OVR getters/setters

### ISSUE THREAD

**Issue by ykeara** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#435]
### Rationale

We have several instances in our code where we  get/set w/ OVR api, and effectively duplicate the code.

Example:

```
            vr::EVRSettingsError vrSettingsError;
            vr::VRSettings()->SetInt32( vr::k_pch_CollisionBounds_Section,
                                        vr::k_pch_CollisionBounds_Style_Int32,
                                        m_chaperoneSwitchToBeginnerLastStyle,
                                        &vrSettingsError );
            if ( vrSettingsError != vr::VRSettingsError_None )
            {
                LOG( WARNING )
                    << "Could not set \""
                    << vr::k_pch_CollisionBounds_Style_Int32 << "\" setting: "
                    << vr::VRSettings()->GetSettingsErrorNameFromEnum(
                           vrSettingsError );
            }
```

### Solution

We could make a simple wrapper w/ a very similiar function prototype

```
SetInt32( vr::k_pch_CollisionBounds_Section,
                                        vr::k_pch_CollisionBounds_Style_Int32,
                                        m_chaperoneSwitchToBeginnerLastStyle,
                                        &vrSettingsError, LogCustomString );
```

This would make it easier to understand whats going on be consistent w/ our input API wrapping, and reduce code-base by 400-1000 lines.

**Comment by username223** [comment]
I would take it a step further even, and instead of a generic `SetInt32` that we stil pass OpenVR keys to, we should do a 

```cpp
SetCollisionBoundsStyle( m_chaperoneSwitchToBeginnerLastStyle );
```

with error handling and logging handled inside the functions.

The advantages of this are a very large reduction in code size, as well as better IDE auto complete and searching for usage.

The functions could return an error enum, if we need to know if something failed.

I'm not a big fan of exceptions for general error handling, as I think they often times get difficult to track through the call stack.

**Comment by ykeara** [comment]
I'm moving forward with a wrapper to IVRSettings in particular (in namespace `ivrsettings`)

I have two Enums I want to use and I don't know what namespace I should put them in.

I have a `logType` (though up for changing)  enum that specifies which Log Flag to use `(warn/err/bug)`, Currently It's in `ivrsettings` but that doesn't make sense long term, and need a general one maybe `utils` [already exist, but may not make logical sense]

Also the error enum we do need it to drive logic, again though a generalized one should be sufficient so I just don't know how we should structure the namsepace.... or maybe put it in `util` and enum class name as `ovrerror`?


I did wrap up the error Handling, but don't pass the error's up, and might need to. I see what you are suggesting, and think it should be done in addition, it would make the code much easier to understand, I need to look around a bit, and make sure that it's not too convultued in some of our cases.

Current Function Prototypes:
```
bool getBool( const char* pchSection,
              const char* pchSettingsKey,
              logType errorType,
              std::string customErrorMsg = "" );

void setBool( const char* pchSection,
              const char* pchSettingsKey,
              bool bValue,
              logType errorType,
              std::string customErrorMsg = "" );
```
I may need to add  `* ErrRetEnum`[maybe just a bool] , though I'm not sure it's necessary... at least for `ivrsettings` if we don't "set" we don't do anything.... the `get` could be more problematic, but I need to look at existing logic to see if it makes sense

**Comment by ykeara** [comment]
I think what actually might make sense is to add a fallback Value as an arg for the "Getters" this would allow us to easily know and set behavior for any call, without having to deal in exceptions or IMO an ugly side-effect... param, we could also initialize it so it would be hidden most of the time.

**Comment by username223** [comment]
Maybe return a `std::pair<bool, ErrorType>`?
