### ISSUE TITLE
Text Scaling Issues Linux

### ISSUE THREAD

**Issue by ykeara** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#442]
From steam Discussions

https://i.imgur.com/3U6vLqp.png

have similiar text scaling issue in linux.

**Comment by ykeara** [comment]
@feilen any ideas?

**Comment by feilen** [comment]
Perhaps we need to try to force a specific font on Linux, one with the same footprint as the font we use on Windows and that's installed by default on Ubuntu. I can try messing with my DPI settings and see if that still impacts the scaling?

**Comment by ykeara** [comment]
ahh so you think it might just be a font issue and not scaling.... if you can see if the dpi scaling effects it would be great help.

**Comment by ykeara** [comment]
@feilen if we just force set a font then you think the issues would be resolved in linux?

**Comment by ykeara** [comment]
Closing Out Haven't heard any updates, appears to be specific to certain distros.
