### ISSUE TITLE
Custom bindings no longer working

### ISSUE THREAD

**Issue by LucianUsagi** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#445]
**Describe the bug**
Bindings don't seem to work in latest release

**To Reproduce**
1. Use v5.1.0
2. Adjust custom bindings for advanced settings in steam overlay, ie. space drag
3. Attempt to use set binds, they do not work

**Expected behavior**
Set bindings work once set

**Screenshots**
N/A, any bindings I set don't work, offset, gravity, space drag, resets, etc

**Software (please complete the following information):**
 - OS: Windows 10 Pro
 - Advanced Settings Version: 5.10

**Hardware (please complete the following information):**
 - CPU: i5-7600k
 - Graphics Card: GTX980
 - HMD: Oculus CV1

**Additional context**
Primary reason for me using adv settings is for playspace moving, and it's what prompted me to create this issue

**Comment by ykeara** [comment]
Upload logs/settings file from %appdata%/advanced-settings team
Upload log file from steam install in <steaminstalldir>/logs/vrserver.txt, and "vrclient_AdvancedSettings.txt" if you have it in that directory as well.

As for actual issue... I think it might just be Steam input being finicky. Try re-loading (switching back and forth) of default bindings or another... and see if that fixes it.

then try toggling the state of say space/drag turn on/off

and then in settings of OVRAS try (one at a time) "enable motion features when in seated mode", "enable old style motion", "allow external app chaperoen edits", "disable automatic crashy recovery of chaperone config".

and if any of those work please leave a message here.

**Comment by LucianUsagi** [comment]
> Upload logs/settings file from %appdata%/advanced-settings team
> Upload log file from steam install in /logs/vrserver.txt, and "vrclient_AdvancedSettings.txt" if you have it in that directory as well.

I'll test the other mentioned possibilities soon and post back any info I learn on whether or not it helps, fixes, or does nothing.

[AdvancedSettings.log](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/4631626/AdvancedSettings.log)

<details>
<summary>OpenVRAdvancedSettings.ini</summary>

[utilitiesSettings]
desktopWidth=4

[videoSettings]
videoSettings\brightnessEnabled=false
videoSettings\brightnessOpacityValue=@Variant(\0\0\0\x87\0\0\0\0)
videoSettings\brightnessValue=@Variant(\0\0\0\x87?\x80\0\0)
videoSettings\colorOverlayEnabled=false
videoSettings\colorOverlayOpacity=@Variant(\0\0\0\x87\0\0\0\0)
videoSettings\colorRedNew=@Variant(\0\0\0\x87?\x80\0\0)
videoSettings\colorGreenNew=@Variant(\0\0\0\x87?\x80\0\0)
videoSettings\colorBlueNew=@Variant(\0\0\0\x87?\x80\0\0)
videoSettings\isOverlayMethodActive=false
brightnessEnabled=false
brightnessOpacityValue=@Variant(\0\0\0\x87\0\0\0\0)
brightnessValue=@Variant(\0\0\0\x87?\x80\0\0)
colorOverlayEnabled=false
colorOverlayOpacity=@Variant(\0\0\0\x87\0\0\0\0)
colorRedNew=@Variant(\0\0\0\x87?\x80\0\0)
colorGreenNew=@Variant(\0\0\0\x87?\x80\0\0)
colorBlueNew=@Variant(\0\0\0\x87?\x80\0\0)
isOverlayMethodActive=false

[keyboardShortcuts]
keyboardOne=^>m
keyboardTwo=^>m
keyboardThree=^>m

[playspaceSettings]
lockXToggle=false
lockYToggle=false
lockZToggle=false
momentumSave=false
turnBindLeft=false
turnBindRight=false
turnBounds=false
moveShortcutLeft=true
moveShortcutRight=true
dragBounds=true
allowExternalEdits=false
oldStyleMotion=false
universeCenteredRotation=false
enableSeatedMotion=false
dragComfortFactor=0
gravityStrength=@Variant(\0\0\0\x87\x41\x1c\xcc\xcd)

[chaperoneSettings]
chaperoneProfiles\1\profileName=\xab\x41utosaved Profile (previous)\xbb
chaperoneProfiles\1\includesChaperoneGeometry=true
chaperoneProfiles\1\chaperoneGeometryQuadCount=4
chaperoneProfiles\1\chaperoneGeometryQuads=@Variant(\0\0\0\t\0\0\0\x4\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\0\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87\xbf\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\0\0\0\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87\xbf\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\0\0\0\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87?\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\0\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87?\0\0\0), @Variant(\0\0\0\t\0\0\0\x4\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\0\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87?\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\0\0\0\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87?\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87?\0\0\0\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87?\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87?\0\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87?\0\0\0), @Variant(\0\0\0\t\0\0\0\x4\0\0\0\t\0\0\0\x3\0\0\0\x87?\0\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87?\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87?\0\0\0\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87?\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87?\0\0\0\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87\xbf\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87?\0\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87\xbf\0\0\0), @Variant(\0\0\0\t\0\0\0\x4\0\0\0\t\0\0\0\x3\0\0\0\x87?\0\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87\xbf\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87?\0\0\0\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87\xbf\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\0\0\0\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87\xbf\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\0\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87\xbf\0\0\0)
chaperoneProfiles\1\standingCenter=@Variant(\0\0\0\t\0\0\0\x4\0\0\0\x87?\x80\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87\x80\0\0\0), @Variant(\0\0\0\t\0\0\0\x4\0\0\0\x87\0\0\0\0\0\0\0\x87?\x80\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87\x80\0\0\0), @Variant(\0\0\0\t\0\0\0\x4\0\0\0\x87\x80\0\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87?\x80\0\0\0\0\0\x87\0\0\0\0)
chaperoneProfiles\1\playSpaceAreaX=@Variant(\0\0\0\x87?\x80\0\0)
chaperoneProfiles\1\playSpaceAreaZ=@Variant(\0\0\0\x87?\x80\0\0)
chaperoneProfiles\1\includesVisibility=true
chaperoneProfiles\1\visibility=@Variant(\0\0\0\x87?\x19\x99\x9a)
chaperoneProfiles\1\includesFadeDistance=true
chaperoneProfiles\1\fadeDistance=@Variant(\0\0\0\x87?333)
chaperoneProfiles\1\includesCenterMarker=true
chaperoneProfiles\1\centerMarker=false
chaperoneProfiles\1\includesPlaySpaceMarker=true
chaperoneProfiles\1\playSpaceMarker=false
chaperoneProfiles\1\includesFloorBoundsMarker=true
chaperoneProfiles\1\floorBoundsMarker=false
chaperoneProfiles\1\includesBoundsColor=true
chaperoneProfiles\1\boundsColor=0, 255, 255
chaperoneProfiles\1\includesChaperoneStyle=true
chaperoneProfiles\1\chaperoneStyle=0
chaperoneProfiles\1\includesForceBounds=true
chaperoneProfiles\1\forceBounds=false
chaperoneProfiles\1\includesProximityWarningSettings=true
chaperoneProfiles\1\chaperoneSwitchToBeginnerEnabled=false
chaperoneProfiles\1\chaperoneSwitchToBeginnerDistance=@Variant(\0\0\0\x87?\0\0\0)
chaperoneProfiles\1\chaperoneHapticFeedbackEnabled=false
chaperoneProfiles\1\chaperoneHapticFeedbackDistance=@Variant(\0\0\0\x87?\0\0\0)
chaperoneProfiles\1\chaperoneAlarmSoundEnabled=false
chaperoneProfiles\1\chaperoneAlarmSoundLooping=true
chaperoneProfiles\1\chaperoneAlarmSoundAdjustVolume=false
chaperoneProfiles\1\chaperoneAlarmSoundDistance=@Variant(\0\0\0\x87?\0\0\0)
chaperoneProfiles\1\chaperoneShowDashboardEnabled=false
chaperoneProfiles\1\chaperoneShowDashboardDistance=@Variant(\0\0\0\x87?\0\0\0)
chaperoneProfiles\size=2
chaperoneProfiles\2\profileName=\xab\x41utosaved Profile\xbb
chaperoneProfiles\2\includesChaperoneGeometry=true
chaperoneProfiles\2\chaperoneGeometryQuadCount=4
chaperoneProfiles\2\chaperoneGeometryQuads=@Variant(\0\0\0\t\0\0\0\x4\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\0\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87\xbf\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\0\0\0\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87\xbf\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\0\0\0\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87?\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\0\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87?\0\0\0), @Variant(\0\0\0\t\0\0\0\x4\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\0\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87?\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\0\0\0\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87?\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87?\0\0\0\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87?\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87?\0\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87?\0\0\0), @Variant(\0\0\0\t\0\0\0\x4\0\0\0\t\0\0\0\x3\0\0\0\x87?\0\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87?\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87?\0\0\0\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87?\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87?\0\0\0\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87\xbf\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87?\0\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87\xbf\0\0\0), @Variant(\0\0\0\t\0\0\0\x4\0\0\0\t\0\0\0\x3\0\0\0\x87?\0\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87\xbf\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87?\0\0\0\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87\xbf\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\0\0\0\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87\xbf\0\0\0\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\0\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87\xbf\0\0\0)
chaperoneProfiles\2\standingCenter=@Variant(\0\0\0\t\0\0\0\x4\0\0\0\x87?\x80\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87\x80\0\0\0), @Variant(\0\0\0\t\0\0\0\x4\0\0\0\x87\0\0\0\0\0\0\0\x87?\x80\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87\x80\0\0\0), @Variant(\0\0\0\t\0\0\0\x4\0\0\0\x87\x80\0\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87?\x80\0\0\0\0\0\x87\0\0\0\0)
chaperoneProfiles\2\playSpaceAreaX=@Variant(\0\0\0\x87?\x80\0\0)
chaperoneProfiles\2\playSpaceAreaZ=@Variant(\0\0\0\x87?\x80\0\0)
chaperoneProfiles\2\includesVisibility=true
chaperoneProfiles\2\visibility=@Variant(\0\0\0\x87?\x19\x99\x9a)
chaperoneProfiles\2\includesFadeDistance=true
chaperoneProfiles\2\fadeDistance=@Variant(\0\0\0\x87?333)
chaperoneProfiles\2\includesCenterMarker=true
chaperoneProfiles\2\centerMarker=false
chaperoneProfiles\2\includesPlaySpaceMarker=true
chaperoneProfiles\2\playSpaceMarker=false
chaperoneProfiles\2\includesFloorBoundsMarker=true
chaperoneProfiles\2\floorBoundsMarker=false
chaperoneProfiles\2\includesBoundsColor=true
chaperoneProfiles\2\boundsColor=0, 255, 255
chaperoneProfiles\2\includesChaperoneStyle=true
chaperoneProfiles\2\chaperoneStyle=0
chaperoneProfiles\2\includesForceBounds=true
chaperoneProfiles\2\forceBounds=false
chaperoneProfiles\2\includesProximityWarningSettings=true
chaperoneProfiles\2\chaperoneSwitchToBeginnerEnabled=false
chaperoneProfiles\2\chaperoneSwitchToBeginnerDistance=@Variant(\0\0\0\x87?\0\0\0)
chaperoneProfiles\2\chaperoneHapticFeedbackEnabled=false
chaperoneProfiles\2\chaperoneHapticFeedbackDistance=@Variant(\0\0\0\x87?\0\0\0)
chaperoneProfiles\2\chaperoneAlarmSoundEnabled=false
chaperoneProfiles\2\chaperoneAlarmSoundLooping=true
chaperoneProfiles\2\chaperoneAlarmSoundAdjustVolume=false
chaperoneProfiles\2\chaperoneAlarmSoundDistance=@Variant(\0\0\0\x87?\0\0\0)
chaperoneProfiles\2\chaperoneShowDashboardEnabled=false
chaperoneProfiles\2\chaperoneShowDashboardDistance=@Variant(\0\0\0\x87?\0\0\0)

[applicationSettings]
previousShutdownSafe=true
</details>
<details>
  <summary>OVR Advanced Settings.ini</summary>
  [playspaceSettings]
lockXToggle=false
lockYToggle=false
lockZToggle=false
momentumSave=false
turnBindLeft=false
turnBindRight=false
turnBounds=false
moveShortcutLeft=false
moveShortcutRight=false
dragBounds=false
allowExternalEdits=false
oldStyleMotion=false
universeCenteredRotation=false
enableSeatedMotion=false
adjustChaperone=true
showLogMatricesButton=false
simpleRecenter=false
heightToggleOffset=-1
gravityStrength=9.8
flingStrength=1
snapTurnAngle=4500
smoothTurnRate=100
dragComfortFactor=0
turnComfortFactor=0
frictionPercent=0

[applicationSettings]
disableVersionCheck=false
previousShutdownSafe=true
vsyncDisabled=false
crashRecoveryDisabled=false
enableDebug=false
debugState=0
customTickRateMs=20

[audioSettings]
pttEnabled=false
pttShowNotification=false
micProximitySensorCanMute=false
micReversePtt=false

[utilitiesSettings]
alarmEnabled=false
alarmIsModal=true
vrcDebug=false
alarmHour=0
alarmMinute=0

[videoSettings]
brightnessEnabled=false
isOverlayMethodActive=false
colorOverlayEnabled=false
brightnessOpacityValue=1
colorOverlayOpacity=0
colorRedNew=1
colorGreenNew=1
colorBlueNew=1
chaperoneSwitchToBeginnerDistance=0.5
chaperoneHapticFeedbackDistance=0.5
chaperoneAlarmSoundDistance=0.5
chaperoneShowDashboardDistance=0.5

[chaperoneSettings]
chaperoneSwitchToBeginnerEnabled=false
chaperoneHapticFeedbackEnabled=false
chaperoneAlarmSoundEnabled=false
chaperoneAlarmSoundLooping=true
chaperoneAlarmSoundAdjustVolume=false
chaperoneShowDashboardEnabled=false
disableChaperone=false
centerMarkerNew=false
fadeDistanceRemembered=0.5

[rotationSettings]
autoturnEnabled=false
autoturnUseCornerAngle=true
autoturnVestibularMotionEnabled=false
activationDistance=0.4
deactivateDistance=0.15
cordDetanglingAngle=0.2617993877991494
autoturnMinCordTangle=6.283185307179586
autoturnVestibularMotionRadius=11
autoturnLinearTurnSpeed=9000
autoturnMode=1

[keyboardShortcuts]
keyboardOne=^>m
keyboardTwo=^>m
keyboardThree=^>m

[ChaperoneTabController%3A%3AChaperoneProfile-1]
bools\1\bools=true
bools\2\bools=true
bools\3\bools=true
bools\4\bools=false
bools\5\bools=true
bools\6\bools=false
bools\7\bools=true
bools\8\bools=false
bools\9\bools=true
bools\10\bools=true
bools\11\bools=true
bools\12\bools=false
bools\13\bools=true
bools\14\bools=false
bools\15\bools=false
bools\16\bools=false
bools\17\bools=true
bools\18\bools=false
bools\19\bools=false
bools\20\bools=false
bools\21\bools=false
bools\size=21
ints\1\ints=4
ints\2\ints=0
ints\3\ints=255
ints\4\ints=255
ints\5\ints=0
ints\size=5
doubles\1\doubles=-0.5
doubles\2\doubles=0
doubles\3\doubles=-0.5
doubles\4\doubles=-0.5
doubles\5\doubles=2.430000066757202
doubles\6\doubles=-0.5
doubles\7\doubles=-0.5
doubles\8\doubles=2.430000066757202
doubles\9\doubles=0.5
doubles\10\doubles=-0.5
doubles\11\doubles=0
doubles\12\doubles=0.5
doubles\13\doubles=-0.5
doubles\14\doubles=0
doubles\15\doubles=0.5
doubles\16\doubles=-0.5
doubles\17\doubles=2.430000066757202
doubles\18\doubles=0.5
doubles\19\doubles=0.5
doubles\20\doubles=2.430000066757202
doubles\21\doubles=0.5
doubles\22\doubles=0.5
doubles\23\doubles=0
doubles\24\doubles=0.5
doubles\25\doubles=0.5
doubles\26\doubles=0
doubles\27\doubles=0.5
doubles\28\doubles=0.5
doubles\29\doubles=2.430000066757202
doubles\30\doubles=0.5
doubles\31\doubles=0.5
doubles\32\doubles=2.430000066757202
doubles\33\doubles=-0.5
doubles\34\doubles=0.5
doubles\35\doubles=0
doubles\36\doubles=-0.5
doubles\37\doubles=0.5
doubles\38\doubles=0
doubles\39\doubles=-0.5
doubles\40\doubles=0.5
doubles\41\doubles=2.430000066757202
doubles\42\doubles=-0.5
doubles\43\doubles=-0.5
doubles\44\doubles=2.430000066757202
doubles\45\doubles=-0.5
doubles\46\doubles=-0.5
doubles\47\doubles=0
doubles\48\doubles=-0.5
doubles\49\doubles=1
doubles\50\doubles=0
doubles\51\doubles=0
doubles\52\doubles=0
doubles\53\doubles=0
doubles\54\doubles=1
doubles\55\doubles=0
doubles\56\doubles=0
doubles\57\doubles=0
doubles\58\doubles=0
doubles\59\doubles=1
doubles\60\doubles=0
doubles\61\doubles=1
doubles\62\doubles=1
doubles\63\doubles=0.6000000238418579
doubles\64\doubles=0.699999988079071
doubles\65\doubles=0.5
doubles\66\doubles=0.5
doubles\67\doubles=0.5
doubles\68\doubles=0.5
doubles\size=68
strings\1\strings=\xab\x41utosaved Profile (previous)\xbb
strings\size=1

[ChaperoneTabController%3A%3AChaperoneProfile-2]
bools\1\bools=true
bools\2\bools=true
bools\3\bools=true
bools\4\bools=true
bools\5\bools=false
bools\6\bools=true
bools\7\bools=false
bools\8\bools=true
bools\9\bools=false
bools\10\bools=true
bools\11\bools=true
bools\12\bools=true
bools\13\bools=false
bools\14\bools=true
bools\15\bools=false
bools\16\bools=false
bools\17\bools=false
bools\18\bools=true
bools\19\bools=false
bools\20\bools=false
bools\21\bools=false
bools\size=21
ints\1\ints=4
ints\2\ints=0
ints\3\ints=255
ints\4\ints=255
ints\5\ints=0
ints\size=5
doubles\1\doubles=-0.5
doubles\2\doubles=0
doubles\3\doubles=-0.5
doubles\4\doubles=-0.5
doubles\5\doubles=2.430000066757202
doubles\6\doubles=-0.5
doubles\7\doubles=-0.5
doubles\8\doubles=2.430000066757202
doubles\9\doubles=0.5
doubles\10\doubles=-0.5
doubles\11\doubles=0
doubles\12\doubles=0.5
doubles\13\doubles=-0.5
doubles\14\doubles=0
doubles\15\doubles=0.5
doubles\16\doubles=-0.5
doubles\17\doubles=2.430000066757202
doubles\18\doubles=0.5
doubles\19\doubles=0.5
doubles\20\doubles=2.430000066757202
doubles\21\doubles=0.5
doubles\22\doubles=0.5
doubles\23\doubles=0
doubles\24\doubles=0.5
doubles\25\doubles=0.5
doubles\26\doubles=0
doubles\27\doubles=0.5
doubles\28\doubles=0.5
doubles\29\doubles=2.430000066757202
doubles\30\doubles=0.5
doubles\31\doubles=0.5
doubles\32\doubles=2.430000066757202
doubles\33\doubles=-0.5
doubles\34\doubles=0.5
doubles\35\doubles=0
doubles\36\doubles=-0.5
doubles\37\doubles=0.5
doubles\38\doubles=0
doubles\39\doubles=-0.5
doubles\40\doubles=0.5
doubles\41\doubles=2.430000066757202
doubles\42\doubles=-0.5
doubles\43\doubles=-0.5
doubles\44\doubles=2.430000066757202
doubles\45\doubles=-0.5
doubles\46\doubles=-0.5
doubles\47\doubles=0
doubles\48\doubles=-0.5
doubles\49\doubles=1
doubles\50\doubles=0
doubles\51\doubles=0
doubles\52\doubles=0
doubles\53\doubles=0
doubles\54\doubles=1
doubles\55\doubles=0
doubles\56\doubles=0
doubles\57\doubles=0
doubles\58\doubles=0
doubles\59\doubles=1
doubles\60\doubles=0
doubles\61\doubles=1
doubles\62\doubles=1
doubles\63\doubles=0.6000000238418579
doubles\64\doubles=0.699999988079071
doubles\65\doubles=0.5
doubles\66\doubles=0.5
doubles\67\doubles=0.5
doubles\68\doubles=0.5
doubles\size=68
strings\1\strings=\xab\x41utosaved Profile\xbb
strings\size=1

</details>

[vrserver.txt](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/4631632/vrserver.txt)
[vrclient_AdvancedSettings.txt](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/4631634/vrclient_AdvancedSettings.txt)

**Comment by ykeara** [comment]
Quick look at your log files you don't have the Left/Right Hand Space drag checked... both are false, so you couldn't drag?

**Comment by LucianUsagi** [comment]
> Quick look at your log files you don't have the Left/Right Hand Space drag checked... both are false, so you couldn't drag?

It's changed in the steamvr menu, so maybe it's just not communicating with the files? I don't have any manually set to read-only but if I'm told where the binds are found I can attempt to do it manually via the cfg without fiddling with it in vr

**Comment by ykeara** [comment]
It's the OVR Advanced Settings.ini

and moveShortcutLeft=false (and right obviously)

If changing that directly works tell me.

**Comment by LucianUsagi** [comment]
> Try re-loading (switching back and forth) of default bindings or another... and see if that fixes it.
no dice

> try (one at a time) 
> "enable motion features when in seated mode"
no dice
> "enable old style motion"
no dice
> "allow external app chaperoen edits"
no dice
> "disable automatic crashy recovery of chaperone config".
no dice
> If changing that directly works tell me:  OVR Advanced Settings.ini moveShortcutLeft/moveShortcutRight
tried changing before launching, tried changing while open, tried changing while open then restarting, none of the above worked

**Comment by ykeara** [comment]
did you change it to moveShortcutLeft=true? or leave it at false? (changes should only effect while OVRAS is not running from that file)

And if you could upload the .ini file again.

As well as can you upload from Steam install /config/appconfig.json

are the checkboxes on https://i.imgur.com/JbNSXlG.png checked or unchecked

**Comment by LucianUsagi** [comment]
oddly enough, restarting it like three times and toggling around the moveshortcutleft and the checkboxes again worked?
ill just knock on wood and be happy i suppose, thank you for the help
