### ISSUE TITLE
Force Chaperone Walls to be visible for WMR users.

### ISSUE THREAD

**Issue by pupphelper** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#446]
For some reason WMR disables the default chaperone walls in SteamVR.  Presumably because they want to use their own "Boundaries".  The WMR boundary wall difficult to see where the chaperone grid would have help you away from danger.    It would be great to have an option to re-enable or force the chaperone walls to show for WMR users.   All other settings of OVAS work, ie. audible warning, vibration all properly activate when passing the steamvr chaperone, however the Wall does not show.

Please consider this feature in a future version if its possible.  

ps. Thanks again for this amazing tool, its made things much easier for WMR users.   Sometimes steamvr will rotate the playspace, and you have no ability to save a new one, creating a preset for offsets in OVRAS has made a huge difference.  First time i pop into steamVR, i load up the preset, and everything is right again :)

**Comment by ykeara** [comment]
Posted in the discord as well https://drive.google.com/open?id=1ZmpIOkbVgvw057MgnuD3HicP_9l5EqwR if you can try this build (just delete your current install and replace with these files.)

in `settings` there is a `force use steam's native chaperone` option,  (it should be on by default which is allow import of bounds) try turning it off and see what happens... I think it should require steam's chaperone... you may have to manually run roomsetup, but I am not entirely sure what the behaviour is. (room setup is in steamvr install location `C:\Program Files (x86)\Steam\steamapps\common\SteamVR\tools\steamvr_room_setup\win64` by default

**Comment by ykeara** [comment]
I'm marking this with 5.1.1 release, while there is a lot of work I think that technically this staisfies this issue.
