### ISSUE TITLE
[Request] Desktop mode and Multi Monitors

### ISSUE THREAD

**Issue by horst789github** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#47]
> something that I've seen the need for and have found the need for personally, as a user of 2 screens text become difficult due to the down scaling, and whilst the ability to scale up the desktop mode helps (Thanks, really helps) its not a perfect fix, it makes text of the far side of the text stupidly far away.
> 
> what id like to suggest is either a way to add a offset to the monitors so that at least 1 screen is centered for users of 2 screens, or a way to limit desktop mode to a single display.
> 
> Thanks keep up the great work <3 this app

https://github.com/matzman666/OpenVR-AdvancedSettings/issues/146

please add better multimonitor support (like virtual desktop steamapp)

**Comment by username223** [comment]
As a multi screen user myself this is also something I want. We'll look into it. It might not be possible, but we'll try.

**Comment by username223** [comment]
A feature to move the desktop overlay has been added to the next release (3.1.0) by PR #143.

Rotation of the overlay is also possible, but I failed to see any uses for it. If it's important to any of you then open another issue.
