### ISSUE TITLE
Can I exclude the possibility of pressing button "mute" on headset in last version of OpenVR?

### ISSUE THREAD

**Issue by ivchuk-dmytro** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#480]

**Comment by ykeara** [comment]
What button are you talking about?

**Comment by ivchuk-dmytro** [comment]
I`m talking about button "mute" micro located on left speaker of HTC Vive Pro glasses

**Comment by ivchuk-dmytro** [comment]
In previous version we have "Proximity Sensor Mutes/Unmutes Micro", but I didn`t saw this in current version

**Comment by ykeara** [comment]
"Proximity Sensor Mutes/Unmutes Microphone" should still be in Audio Tab (make sure you are on 5.2.0 and not an older version.)


As for can you disable the button on the HMD..... I don't know off the top of my head, but you should be able to change the bindings in the "compositor" app in steamvr for your HMD... though not 100% how to do that off top of my head (hmd is somewhat hidden by default)


but you should be able to disable the button completely by removing it in `C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\htc\resources\input\vive_pro_profile.json` Obviously be careful.... you are adjusting how things are working and it may not work.

**Comment by ykeara** [comment]
Going to Close out in ~7 days if no response
