### ISSUE TITLE
Cant find fake fullbody setting

### ISSUE THREAD

**Issue by Brayton1234567** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#483]
I cant find the fake fullbody setting, and i need it for vrchat, since i dont already have fullbody.

**Comment by ykeara** [comment]
We don't support the ability to add virtual tracked objects, and it's something we will probably never support due to forcing us to become a driver to do so.

**Comment by Brayton1234567** [comment]
Alright, thank you!
