### ISSUE TITLE
Space Drag Toggle Control Binding

### ISSUE THREAD

**Issue by CateBoi** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#487]
Being able to toggle space drag, similar to how we can toggle gravity would be great for switching games without switching our control bindings. Switching from games that are space drag friendly, such as VRChat, to games that aren't, such as Boneworks takes a minute.

**Comment by ykeara** [comment]
so easiest way you can just go un-check "space drag l/r" w/o re-doing your bindings (or lock axis in offsets tab)

obviously not a keybind but something to be aware of.

I doubt we will add a keybind specifically for that... but I do have a plan for one (it just hasn't gotten done yet) that will do something relatively tangentally.
