### ISSUE TITLE
controller positioning and rotation control + macro to script of actions

### ISSUE THREAD

**Issue by MrBob132** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#504]
as the title said I would like if there was an option to manipulate the controller's positioning and rotation
for example and offset in the axis.
further more, things like a smooth rotation of the controller in vr.
additionally, a way to create and execute a script of actions.

**Comment by ykeara** [comment]
While we would love to do this, (at least the former) it would require a driver to do, and that is not something we are willing to become i.e. it would be a different app. As Such we can't really do this.
