### ISSUE TITLE
Custom keyboard shortcuts do not hold modifier keys

### ISSUE THREAD

**Issue by who-wrote-this** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#508]
**Describe the bug**
A custom keyboard shortcut defined by `keyboardOne` in `OVR Advanced Settings.ini` involving modifier keys did not properly hold the modifier keys. 

**To Reproduce**
1. In the INI, set `keyboardOne=#*g`
2. In OVRAS, bind the Index left trackpad click to invoke that keyboard shortcut
3. In SteamVR Home, click the Index left trackpad

The Windows menu opens as if the Win key had been pressed and released separately. Furthermore, if notepad was initially focused on the desktop when the shortcut is invoked, it dings as if Alt and 'g' had been typed separately with notepad focused.

**Expected behavior**
The Xbox DVR Record That feature should be triggered as if Win+Alt+G had been pressed on the keyboard.

**Software**
 - OS: Windows 10
 - Advanced Settings Version: 5.2.2 (from Steam)

**Additional notes**
I peeked at the source and don't see anywhere in `input_parser.cpp` that would add a `TOKEN_NO_KEYUP_NEXT` which seems to be required to hold modifier keys in a sequence, judging by the premade ones in `keyboard_input.cpp`. 

I installed OVRAS for the first time today, so cannot say whether this previously worked.

**Comment by ykeara** [comment]
I'll have to look, I know there is another Issue I want to look at for order of key-up events.

**Comment by ykeara** [comment]
yep,  have addressed this will be in next update.
