### ISSUE TITLE
Incorporate Input Emulator

### ISSUE THREAD

**Issue by Activusto** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#519]
As of the recent SteamVR update, the original Input Emulator has broken.
It has not been updated for 3 years and it seems like no other person has bothered to update it.
I mainly use it for using Vive Pucks as Trackers for Controllers, I have another friend interested in that same setup, and anothjer uses it for motion sims.

I would like to see this incorporated into OVRAS since I'd think it's an undervalued plugin that deserves to be updated and known.

**Comment by ykeara** [comment]
It's not feasible for us to incorporate those features, as they require hooking into the drivers, something that has been decided we aren't going to implement into OVRAS
