### ISSUE TITLE
SteamVr overlay Width Save state

### ISSUE THREAD

**Issue by ykeara** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#52]
Add a save state to steamvroverlay width setting.

**Comment by username223** [comment]
I was also thinking about this. 

Sometimes when I've started Advanced Settings the value has been something other than 1.0. It could just be a lack of zero initialization, or it could be that something remembers the value but doesn't apply it.

The proper way to do it would probably to save it in the `settings` object and write it to the `.ini` file.

**Comment by ykeara** [comment]
similiar to #47, but as the current implementation is to grab valve's overlay..... The behavior is hard to define. [sometimes ADV settings starts before the overlay is init, sometimes the overlay inits just fine... etc.] On hold until we can find path moving forward.
