### ISSUE TITLE
Add Disable SteamVR Home Button

### ISSUE THREAD

**Issue by ykeara** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#521]
To SteamVR tab

key is `k_pch_SteamVR_EnableHomeApp`

Need to double check to make sure it's not an option in regular settings.

**Comment by Rectus** [comment]
It's already an advanced setting under the General tab.

**Comment by ykeara** [comment]
Closing out, as something that is already implemented and fairly niche.
