### ISSUE TITLE
Issues after update from 2.8.0 to 5.30, lost settings, keyboard behind overlay, cannot type.

### ISSUE THREAD

**Issue by gormanj** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#524]
I just went from 2.8.0 to 5.30 (tried to update via Steam a while back, didn't know that it did not take, so updated manually with installer).

The keyboard shows up behind the steam overlay, it does not input type and I cannot use my physical keyboard.

I've lost my numerous profile saves, the chaperone profiles I really want back.

Other than my problems, looks like a lot of improvements/features. Thanks!

**Comment by ykeara** [comment]
sounds like 2.8.0 is still running

follow these instructions on uninstalling

specifically the appconfig.json in steam's config folder should point to the version of OVRAS that is being ran if not running the steam version....

**5.0.0 and Steam**

- This update **WILL** reset your current settings
  - They **CANNOT** be trivially moved and updated
- This update **WILL** break your Saved Keybinds
  - The keybinds  **WILL** have to be remade
- This update **WILL** change the name from `Advanced Settings` to `OVR Advanced Settings` In the Steam Keybinding Menu.
- We highly **RECOMMEND** to un-install the current version before installing the new version
**How To Uninstall**
  - Automatically
    - Simply run the un-installer
    - delete install directory
    - (optional) delete logs and settings `%appdata%/AdvancedSettings-Team` by default
  - Semi-manually
    - Run `AdvancedSettings.exe` with the command `--force-remove-manifest`
    - delete install directory
    - (optional) delete logs and settings `%appdata%/AdvancedSettings-Team` by default
  - manually
    - go to steam install/config directory (`C:\Program Files (x86)\Steam\config` by default)
    - edit the `appconfig.json` to remove the path pointed to Advanced Settings (`"C:\\Program Files\\OpenVR-AdvancedSettings\\manifest.vrmanifest"` by default)
    - delete install/setting/log file manually
