### ISSUE TITLE
Space Turn option missing from Motion Settings window

### ISSUE THREAD

**Issue by Darkhand81** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#525]
Hello! For me, the Space Turn option is missing from the Motion Settings window, preventing me from enabling it for use.  I'm sure it's something on my end but thought this would be the easiest way to solve the issue.  Please let me know what other info you might need:

**Expected behavior**
The option to enable/disable space turn is missing from my version of the OVRAS Motion Settings window.

**Screenshots**
<img width="287" alt="SpaceTurnMissing" src="https://user-images.githubusercontent.com/1334381/94724951-a6f76500-0320-11eb-9a8d-f86becd3d480.png">

**Software (please complete the following information):**
 - OS: Windows 10 v2004
 - Advanced Settings Version: At least from version 5.2.0 to 5.3.0 (only versions tested so far)

**Hardware (please complete the following information):**
 - CPU: Intel i7-6700k
 - Graphics Card: Nvidia 1080ti
 - HMD: Original Vive and wands

**Additional context**
Thanks in advance for what is most likely user error!

**Comment by ykeara** [comment]
The rotation methods are all located in the "rotation" tab now.

**Comment by Darkhand81** [comment]
> The rotation methods are all located in the "rotation" tab now.

And that's exactly why I prefaced my ticket. Thanks very much. :)
