### ISSUE TITLE
Wont appear when clicked on

### ISSUE THREAD

**Issue by EricSkye7** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#528]
The Page that allows you to turn the setting on and off and change gravity, all those settings, wont appear and I've uninstalled and reinstalled it about 3 times now and still nothing and don't really know what else to do, thought it was because I haven't updated it but when I did the problem persisted.
Not to sure what to do now.

**Comment by ykeara** [comment]
https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#common-issues

Assuming you have logo, but no menus at all? then follow first direction there to force OpenGL to run on your VR gpu.
