### ISSUE TITLE
Feature Request: Screen Savor to prevent burn in

### ISSUE THREAD

**Issue by OzzyHelix** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#531]
**Is your feature request related to a problem? Please describe.**
there are headsets with oled and other screen types that can suffer from burn in, limiting a headsets life spam
**Describe the solution you'd like**
a solution add a screen savor option that can detect an inactive headset and display a screen savor.
**Describe alternatives you've considered**

**Additional context**
People could get headset screensavers from developers who want to write ones for Advanced Settings or perhaps through the steam workshop. the headset when inactive for a set amount of time could turn the screen off or go near completely dark perhaps the amount of time for the headset to turn off/go dark could be done with a slider. The users can use the slider to determine the time it takes for the headset to turn off/go dark. this could be helped to extend the life span of user headsets and help combat burn in on screens
![RedFatalAfricanaugurbuzzard-size_restricted](https://user-images.githubusercontent.com/29835364/97130668-6967db00-1718-11eb-8c57-f23cbe550ed3.gif)

**Comment by ykeara** [comment]
This is actually already handled by several features... and all the major headsets turn off VERY quickly after being removed from your face? (<5 minutes)
