### ISSUE TITLE
Feature Request: World Pitch and Roll Fix

### ISSUE THREAD

**Issue by Miles3298** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#538]
**Is your feature request related to a problem? Please describe.**
Presently, there does not seem to be a way to correct problems related to a tilted VR world, seemingly regardless of headset vendor. Running room setup from a fresh Steam and SteamVR installation has never corrected this nor has hardware calibration or any other popular troubleshooting method. For me personally, this is a problem across two headsets; it is very frustrating that I 100% cannot ever have a correctly level world due to having lost the HMD IMU lottery twice.

**Describe the solution you'd like**
It would do wonders to have a "Reset Horizontal Level" button in OpenVR Advanced Settings which prompts you to hold your head as straight as possible and pull your controller's trigger. Maybe have it take multiple samples, having you turn 90 degrees to the left or right for each one. Alternatively or additionally, it would be helpful to provide manual adjustments of pitch and roll by 0.01 degree increments, similar to how the current playspace rotation system works.

**Describe alternatives you've considered**
Solution 1: New headset. This did not work; I have the same problem to a slightly different angle with a newer one.
Solution 2: Hardware calibration, via SteamVR Tracking Licensee program. It does not seem to have any actual effect when uploading new configs to the headset.
Solution 3: Complete wipe of Steam, SteamVR, lighthouse settings in appdata, and so on. This does not work; upon completing the new "first time" room setup, the problem of tilted world still exists.
Solution 4: Moving base stations and changing rooms. This doesn't help; across two rooms, the world is still always ending up tilted.
Solution 5: Solutions 3 and 4 together. Same result.
Solution 6: Change the angle at which controllers and the HMD are facing upon SteamVR boot. This has never had any effect.

**Additional context**
My two headsets in question are both HTC Vives. Both have different (but large) leftward world tilts. Curiously, after much Googling, I have noticed some Oculus users having the same problem with no apparent solution, and at least one Pimax user. I feel it would be beneficial for VR users in general to be able to correct this issue if they notice that they have it.

**Comment by ykeara** [comment]
Unfortunately this is outside of our ability to do based on how we are set-up....

At least with LH tracking In my experience it's caused by a large IR reflective flat surface (mirror, monitor, window, etc.)

we simply cannot control pitch/roll of the world with how we are setup.
