### ISSUE TITLE
[Feature Request] option for smoothing the controller movement/rotations

### ISSUE THREAD

**Issue by laundmo** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#542]
**Is your feature request related to a problem? Please describe.**
Sometimes your hands can be more shaky than you want. Sometimes controllers can jiggle a bit because of momentum.

**Describe the solution you'd like**
A option in OVR Advanced Settings that allows for configurable smoothing of the controller data sent to games. Configurable strength, smoothing algorithm, range (if movements are larger than a certain distance in the last n frames, dont smooth).

**Describe alternatives you've considered**
Asking each game to implement it themselves - a lot of effort and probably not going to happen.
Physically dampening controllers with rubber bands - doesnt work well

**Additional Context**
in BONEWORKS the cursor/laser pointer is smoothed, thats what i want my controllers to be like.

**Comment by ykeara** [comment]
Unfortunately this is outside the scope of the project, and would require a different base solution  solution as such It won't be implemented
