### ISSUE TITLE
Tracking Universe: Unknown(2)

### ISSUE THREAD

**Issue by Bluscream** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#545]
I have this only in Microsoft Flight Simulator 2020 and it makes it impossible to move in there

**Comment by ykeara** [comment]
Yea know what the issue is, will probably just remove are lock on unknown tracking universes

**Comment by Bluscream** [comment]
What?

**Comment by JBB888** [comment]
I know this is old thread but I'm also getting this issue with War Thunder. Any way around it?

**Comment by ykeara** [comment]
Should be removed now
