### ISSUE TITLE
Does OVR Advanced Settings provide the entire dashboard, or just the settings menu? 

### ISSUE THREAD

**Issue by happysmash27** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#546]
So, I _was_ going to file a bug report about how the desktop view in the bottom-right corner didn't seem to work... but after a little thought, I am now wondering if that is even relevant to this project. Does OVR Advanced Settings provide the entire overlay, or only the third button in the bottom right? I cannot open the overlay without OVR Advanced Settings installed, but the overlay also seems to be integrated into SteamVR better than I would expect for something third-party, since when I click on games in the SteamVR Home, the preview opens up in the overlay. So, I am not sure if OVR Advanced Settings is what is making the entire dashboard, or if there is a bug where the dashboard doesn't show up that is fixed by OpenVR Advanced Settings somehow.

**Comment by username223** [comment]
The VR menu, the thing that comes up when you press the menu button on your controller, is default SteamVR.
OVR Advanced Settings just adds the little circle with Advanced Settings on it.

**Comment by ykeara** [comment]
Closing Out as issue should be resolved
