### ISSUE TITLE
Any way to bind 'rotate play space' to keyboard instead of controller?

### ISSUE THREAD

**Issue by JBB888** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#547]
I've tried everything to make this work as War Thunder doesnt allow look back in VR and its essential but taking hand off the keyboard to use the gamepad is annoying in battle. I've tried every external software I can find but I can only make it work where a gamepad button emulates a key and not the other way around :( Any ideas would be appreciated thanks. Also the built in steam remapper doesn't work either only the wrong way around.

**Comment by username223** [comment]
It is not possible at the moment.

Implementing it would be a larger project, since all the different Advanced Settings functionality would need to be categorized and somehow listed in a logical way.

**Comment by JBB888** [comment]
ok, thanks for the info. If you're the dev great app my game would be a nightmare without it!
