### ISSUE TITLE
nmake / jom don't know how to create Qt5Quick.lib

### ISSUE THREAD

**Issue by RensTillmann** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#549]
When I try to run `build_windows.cmd` with jom.exe environment variable set or without by setting to "1" (to force using nmake) I am getting the following error.

```
[vcvarsall.bat] Environment initialized for: 'x64'
Environment set up.
Running qmake:
qmake done.
Running jom:

jom 1.1.3 - empower your cores

        C:\Qt5\Tools\QtCreator\bin\jom.exe -f Makefile.Release
Error: dependent 'C:\Qt5\5.15.2\mingw81_64\lib\Qt5Quick.lib' does not exist.
jom: C:\Users\Rens\go\src\github.com\RensTillmann\OpenVR-AdvancedSettings\Makefile [release] Error 2
```

And with nmake enabled:

```
[vcvarsall.bat] Environment initialized for: 'x64'
Environment set up.
Running qmake:
qmake done.
Running nmake:

Microsoft (R) Program Maintenance Utility Version 14.28.29336.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\nmake.exe" -f Makefile.Release

Microsoft (R) Program Maintenance Utility Version 14.28.29336.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1073: don't know how to make 'C:\Qt5\5.15.2\mingw81_64\lib\Qt5Quick.lib'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
```

The file C:\Qt5\5.15.2\mingw81_64\lib\Qt5Quick.lib (as jom reports). But nmake tries to create this file, so I don't understand.
Any idea what to do here? I can't really find much info about this error, and what I found wasn't to helpful.

**Comment by RensTillmann** [comment]
I manually grabbed the following lib files from this repo, and added them in the directory:
https://github.com/GPUOpen-Archive/common-lib-ext-Qt-5.5/tree/master/5.5/lib/win32

Qt5Widgets.lib, Qt5Multimedia.lib, Qt5Quick.lib

However I feel like something is odd here. Anyway, now I am getting this error after running `build_windows.cmd`

```
Setting up environment with Visual Studio 'vcvarsall.bat':
The input line is too long.
The syntax of the command is incorrect.
```

**Comment by username223** [comment]
Have you installed the full Qt package in `C:\Qt5\5.15.2\`?

**Comment by RensTillmann** [comment]
Hi, as the installation directory I choose C:\Qt5. The folder inside it `5.15.2` is created by Qt installation itself. I didn't do that. Please see below folder structure:

![image](https://user-images.githubusercontent.com/16322803/108599319-c0ad4d80-7390-11eb-8660-c0ad97ceb5cc.png)

![image](https://user-images.githubusercontent.com/16322803/108599324-c73bc500-7390-11eb-993e-2a84af818954.png)

![image](https://user-images.githubusercontent.com/16322803/108599340-dcb0ef00-7390-11eb-83b4-50dc5c1229bf.png)

![image](https://user-images.githubusercontent.com/16322803/108599330-ce62d300-7390-11eb-82fe-d684c74e78d3.png)

![image](https://user-images.githubusercontent.com/16322803/108599346-e76b8400-7390-11eb-90fd-fa5d7a7b1412.png)

![image](https://user-images.githubusercontent.com/16322803/108599353-ef2b2880-7390-11eb-993a-7aab912acf0c.png)

**Comment by username223** [comment]
I don't have a Windows machine to test on, but the docs say that the Qt location should be `"DRIVE_LETTER:\Qt\VERSION\msvc2017\bin"` while yours is `mingw81_64`, have you installed the Visual Studio 2017 version of Qt? I believe that both the `msvc` and `clang-msvc` compilers require `msvc2017`.

**Comment by RensTillmann** [comment]
Hi, thanks for the feedback, I appreciate it a lot. I have Visual Studio 2019 installed. Are you saying I must have 2017 installed in order for Qt to function properly?

I am going to reinstall Qt now, but with the installer from this page (https://www.qt.io/offline-installers) **Qt 5.12.10 for Windows (3.7 GB)**.

There also seems to be a "Other downloads" TAB, with some sort of "Add-in" for Visual Studio 2019/2017. Is this required? I am guessing not, but would you happen to know what it does or why someone would install this?

**Comment by username223** [comment]
I do not know if msvc2019 works. I remember there being something about it not working around the release but I'm not sure if it works now.

If it doesn't work with msvc2019 try it with msvc2017.

You should not need any addons other than the C++ part.

You must also have Python3 installed in the PATH. I don't think the install scripts checks for it so I'm not sure what the symptoms would be with it missing.

**Comment by RensTillmann** [comment]
I got the python3 in my path, so that's not it. Installation just finished. So I am going to test it again. I will report back if I encounter issues. I will also test with v2017 after this fails.

**Comment by RensTillmann** [comment]
I got it to work, I only got the below error after running `build_windows.cmd` but was able to fix that by editing the following file (OpenVR-AdvancedSettings\installer\installer.nsi), and adding `Unicode True` at the top.

```
Starting NSIS:
warning 7998: ANSI targets are deprecated
Error: warning treated as error

Note: you may have one or two (large) stale temporary file(s) left in your temporary directory (Generally this only happens on Windows 9x).
```

After changing that, it build properly it seems :)

```
7zip done.
Starting NSIS:
NSIS done.
MASTER: MASTER DONE.
```

Trying to get it to run now, and then I can finally work on some code 😁🎉
