### ISSUE TITLE
Can't scroll to diffrent modes when changing controls with a lot of diffrent modes, (No mans sky)

### ISSUE THREAD

**Issue by Splintersm** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#551]
**Describe the bug**
When playing NMS and trying to change the mounted controls I found that I cant scroll left or right in regurds to changing the control modes (In vehicel, build mode, on foot, in spaceship, exc). Im assuming mounted controls are just further to the right or left as I can see that Im missing some visually. I need a way to scroll left and right .

**To Reproduce**
1. Get in Steam VR
2. try and change NMS mounted controls
3. notice that you cant scroll left or right at the top

**Comment by ykeara** [comment]
So We are not the keybinding interface, that is on Valve's End, so I would recommend to make an issue in the steamvr community page for bug reports.

only real suggestion I have is maybe try to go to  http://localhost:27062/dashboard/controllerbinding.html (in a browser) while steamvr is running.... and may be able to adjust it from desktop.
