### ISSUE TITLE
SteamVR Tracker Position and Rotation to be Frozen in Playspace

### ISSUE THREAD

**Issue by wilton323** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#552]
To have a button in settings and/or controller binding that freezes the current position and rotation of a selected SteamVR tracker. Therefore, the frozen tracker will not move in the SteamVR playspace. It should also allow multiple trackers to be frozen.

To have a setting that overrides the position and rotation of a selected SteamVR tracker. Therefore, the user can define where the tracker is and the where the selected tracker is facing in the SteamVR playspace. It should also allow override to multiple trackers.

**Comment by ykeara** [comment]
Not possible for how we are set up, going to close out.
