### ISSUE TITLE
OVR Toolkit

### ISSUE THREAD

**Issue by Doubs115** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#553]
I heard somewhere that OVR toolkit is incompatible with OVR AS.

I was thinking that if this has already been solved maybe have what you can do be in OVR AS because some people don't have money after buying a headset.

**Comment by ykeara** [comment]
No outstanding issues with compatibility between us and OVR toolkit that I know, and I regularly talk to Curtis (dev of OVR toolkit) I think he would yell at me if something was bad.... 5.3.2 did fix a minor issue with ovr toolkit and other apps but by and large shouldn't be anything critical)

and for the record we are 100% separate teams.
