### ISSUE TITLE
Quest 2 Calibration

### ISSUE THREAD

**Issue by xMako** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#555]
**Describe the bug**
When I take off my Quest 2 my index controllers shift to the right

**To Reproduce**
1. Take off the Quest 2 after calibrating
2. Wait a couple of minutes
3. Put on the headset
4. BOOM!

**Expected behavior**
The controllers shift to the right making me re-calibrate which is annoying.

**Software (please complete the following information):**
 - OS: Windows 10
 - Advanced Settings Version: Newest

**Hardware (please complete the following information):**
 - CPU: 9700K
 - Graphics Card: 2060S
 - HMD: Quest 2 Index controllers

**Comment by ykeara** [comment]
This is almost certainly just drift related to the HMD.... probable that when the Quest 2 shuts off it drifts more than when running (when you take it off your head it's off or goes off)

At any rate shouldn't be related to us and not something we can really effect at any rate.
