### ISSUE TITLE
Space Dragging doesn't seem to work with the OpenXR runtime

### ISSUE THREAD

**Issue by synergiance** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#556]
**Describe the bug**
Space dragging doesn't seem to work with the OpenXR runtime

**To Reproduce**
1. Load a game or application that uses the OpenXR runtime
2. Attempt to space drag
3. Nothing happens

**Expected behavior**
Space moves with controller as usual

**Software (please complete the following information):**
 - OS: Windows 10 20H2
 - Advanced Settings Version: 5.3.2
 - SteamVR version: 1.16.10

**Hardware (please complete the following information):**
 - CPU: Ryzen 5 3600
 - Graphics Card: NVidia GTX 970
 - HMD: Oculus Rift CV1

**Additional context**
I'm not sure if this is a SteamVR bug or an OVR Advanced Settings bug, or whether its intended behavior.  I have an application I'm testing that uses the OpenXR runtime. I've checked that I am indeed using OpenXR with SteamVR and not Oculus Home directly.

**Comment by ykeara** [comment]
I haven't even looked at OpenXR tbh, almost certainly going to be some difficulties swapping over. If you isolate interested to know, but have no idea what the state is.

and valve's implementation of OpenXR doesn't really have the overlay layer implemented yet (1.1 something I think of Openxr)

**Comment by ImTiara** [comment]
Can confirm this is still an issue.
Using the latest OpenXR, Unity LTS version, SteamVR etc.
Going into Space Offsets while in the game thats using OpenXR will give you a message "Tracking Universe: Unknown(2)" which i assume is linked with this issue.

**Comment by JBB888** [comment]
Getting the same 'tracking universe:unknow' error since War Thunder changed to openXR :(

**Comment by ykeara** [comment]
There is an "uncalbeta" branch on steam that might fix this issue, as it does allow for space drag in "unknown" environments. wortha try and be interesting to see if it fixes your issue as well.

**Comment by JBB888** [comment]
One thing that still works is in chaperone- rotate orientation (permanent) is it possible to bind that to a button?

**Comment by BattleAxeVR** [comment]
I would love it if we could use OVR Advanced settings to enable smooth locomotion and turning in every single VR game, whether it uses the older OpenVR API or OpenXR, as long as we have OVR Advanced settings installed as a plugin for SteamVR and use the SteamVR OpenXR runtime (even on Oculus headsets, as a wrapper / interception / translation layer for input remapping and abstraction).

I'm sick to death of all these teleport-only games, there is no need for it. It's our experience, we should be able to play our games the way we want to, and there's no real technological reason we can't have our cake and eat it, too (smooth loco in every PC VR game, regardless of designers' biases against it).
