### ISSUE TITLE
Issues with Hybrid setups (WMR/Quest with Index Controllers) and chaperone 

### ISSUE THREAD

**Issue by diamond482** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#557]
Just wanted to re-visit and issue that was close in April of last year and posted under the above topic by user ( spoonyspork opened this issue on Apr 22, 2020 · 3 comments )

It's not a complicated set up in todays VR enviroment with HP Reverb being an incomplete product. Many are resorting to using their old Vive Wands / Index controllers to fix the broken tracking HP offers, simply because everyone wants the clarity the HP offers atm.  Huge conflicts with 2 or 3 boundary settings and getting them to play nice.  Steam VR, WMR, Stop Sign VR, and OVR.  Stop Sign VR fixes the issue of grey screen in hybrid setups like the Vive wands and the HP HMD in "sitting" games like Moss.  I'm just a simple consumer user and not very experienced in these matters.  Just more patients and determination than your average plug and play person to try and figure it out.  It would be nice if OVR had the ability to establish it's own boundaries verses importing.  Mine is still a mess and trying to sort it out. Maybe someone can revisit this issue as its going to be a problem for a fair amount of people. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software (please complete the following information):**
 - OS: 
 - Advanced Settings Version: 

**Hardware (please complete the following information):**
 - CPU:
 - Graphics Card: 
 - HMD: 

**Additional context**

**Comment by ykeara** [comment]
Closing out issue, appears to be resolved already
