### ISSUE TITLE
Update compilers to use C++17

### ISSUE THREAD

**Issue by username223** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#56]
We are currently using the C++14 standard on all compilers.

Updating to C++17 would enable new features (most notably initializers in `if` and `switch` statements, and `if constexpr`) and disallow the introduction of currently deprecated features (`std::auto_ptr`, `std::random_shuffle`).

This should be done by updating the `AdvancedSettings.pro` file's `CONFIG   += c++14` line to `CONFIG   += c++1z`.

Qmake does not honor the `c++17` flag, but instead uses the `c++1z` flag. This has been reported as a bug [here](https://bugreports.qt.io/browse/QTBUG-67527), but it does not seem like the developers intend to change the behavior.

**Comment by JavaMatia** [comment]
I'll try to do this. (My first contribution :])

**Comment by username223** [comment]
@JavaMatia Nice, thanks. If you have any questions feel free to ask.

**Comment by username223** [comment]
@JavaMatia Are you still on this?

**Comment by username223** [comment]
Solved in #64.
