### ISSUE TITLE
OpenVR overlay not showing/transparent in SteamVR

### ISSUE THREAD

**Issue by gabe1233** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#565]
i have a problem with OpenVR Advanced Settings where when i try to open the menu in SteamVR it shows as transparent, please can someone help me with this?

i have a 64 bit PC 

Processor:  AMD Ryzen 3 3200G with Radeon Vega Graphics, 3600 Mhz, 4 Core(s), 4 Logical Processor(s)

**Comment by username223** [comment]
Do any of the [common issues](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#common-issues) fix this?

**Comment by gabe1233** [comment]
> Do any of the [common issues](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#common-issues) fix this?

when they say to set the grahpics card to the sane as the headset, since i have a quest 2 (virtual desktop) what do i do?

**Comment by username223** [comment]
@ykeara Says it's still just the Nvidia control panel.

**Comment by gabe1233** [comment]
> @ykeara Says it's still just the Nvidia control panel.

it still dosnt work, i have set steamVR and virtual desktop to the same graphics card,

**Comment by username223** [comment]
What about the Windows setting from the same page?

**Comment by ykeara** [comment]
as of 5.8.3 desktop mode is more fully featured, and a suggested work-around for this issue.
