### ISSUE TITLE
Offsetting / resetting play area

### ISSUE THREAD

**Issue by matejdro** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#566]
Does OVR Advanced Settings offer any way to change the "playing area"? I mean this light gray rectangle that shows up on the floor when there is no game loaded:

![20210606_081541_MixedReality](https://user-images.githubusercontent.com/507922/120919082-0d0a6800-c6b8-11eb-808b-6688ddf4142d.jpg)

No matter what I do, it seems to stay the same and it's not aligned to my walls which irks me. I'm using WMR, so there there is no SteamVR-specific chaperone set up.

**Comment by ykeara** [comment]
We do not
