### ISSUE TITLE
Oculus Link and OVR Advanced Settings Do NOT Get Along

### ISSUE THREAD

**Issue by Minibinaz** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#567]
I have found my VR lag to be caused by OpenVR advanced settings. Oculus link also sometimes crashes and boots to quest randomly, which has not happened in any non-Steam games as I play Oculus store titles. Sometimes link reconnects itself, sometimes not, and it says I must unplug and replug link to retry. I first tried a clean reinstall of both Oculus and OVR advanced settings.  I have seen this be an issue with Half Life: Alyx, H3VR, VRChat, and Blade & Sorcery. And I did try all of these games with every single program besides SteamVR, OpenVR advanced settings, Oculus app, and the game running.

It's pretty simple to recreate the issue. Just plug & go with an Oculus link, and run OpenVR advanced settings. Doesn't matter if it's on boot-up or mid-game. Doesn't need to have fullbody trackers on or detected to create an issue. Opening or boot-opening this software will instantly cripple performance in-game. I have tried tinkering with all relevant graphics settings, but they appear to not be the issue.

This program is expected to boot and run with any VR headset, and at a bare minimum the trackers should be the thing causing performance issues on a lower-end rig, but mine isn't a low end rig, and trackers make no difference.

OVR Advanced Settings: Steam edition and github version re-downloaded and tested in late May 2021. Both encounter issues.

VR: Quest 2, Oculus brand link cable.
System: Windows 10 Home 64x, RTX 2080 8Gb VRAM, Ryzen 9 3900X, 32Gb RAM, 1TB SSD.

I'd be happy to help however possible. Logs, videos, etc... I really liked using this program to run fullbody in Oculus, and I can't use it as the lag gets too extreme to move even when I test it with no trackers detected or turned on.

**Comment by Kung-vr** [comment]
Hi, thanks for the report!

As a first troubleshooting step, could you please try the checkbox "Disable App Vsync" in the settings tab? Once you tick the checkbox another option "Custom Tick Rate" will appear. Please try 500 as the value there. This will drastically limit OVRAS's internal update rate down to 2 times per second. Please report back on if/how this affects your issue.

**Comment by ykeara** [comment]
Closing out no  response, there are some issues but without further information no where to proceed.
