### ISSUE TITLE
Integrate openvr_fsr

### ISSUE THREAD

**Issue by wickles** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#570]
**Is your feature request related to a problem? Please describe.**
A new openvr hack was recently created to enable intelligent upscaling like DLSS but using AMD's new FSR. It does a solid job of improving performance without significantly impacting image quality. Currently it requires replacing the target title's openvr_api.dll and configuration via text file. It would be awesome if this could be integrated into OVRAS. 

https://github.com/fholger/openvr_fsr

**Describe the solution you'd like**
If feasible, integrate openvr_fsr into OVRAS with a nice UI so we could toggle and configure it at will instead of fiddling with files for each title.

**Comment by ykeara** [comment]
Unfortunately this is not something we can do currently.
