### ISSUE TITLE
Per-game controller rotation adjustment

### ISSUE THREAD

**Issue by Bluscream** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#572]
For example in the game Phasmophobia the devs have a really hard time placing items correctly in your hand so you can see them clearly without breaking your wrists. It would be nice if ovras would allow me to set a custom rotation to the controllers so i can hold my hands comfortably and still be able to see the item in my hand just fine.

**Comment by ykeara** [comment]
This is not possible with OVRAS, and will un-able to be done until something new is added to api closing out ticket.
