### ISSUE TITLE
Is there a way to bind 'rotate orientation (permanent)' to a button?

### ISSUE THREAD

**Issue by JBB888** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#573]
'look back' in War Thunder doesn't work in VR which makes the game unbearable, I used to use 'snap turn' button to do it but that no longer works either as I get a 'tracking universe: unknown' error. The only option that works is to rotate orientation but I need to be able to do it quickly. 

It would be incredibly useful to be able to bind this option to a button.
Thanks.

**Comment by ykeara** [comment]
I think I pulled out the playspace requirements (I know I did it for motion unsure on rotation based things) so hopefully  can use snap turn, if not feel free to re-open but in this case the correct answer is to get snap turn working.

**Comment by JBB888** [comment]
Hi, Just tried the latest version with War Thunder (which now uses OpenXR so not much works, however the snap-turn binding only works on my steamVR overlays, not the game itself. 
BUT... only when I use the slider in the Chaperone Menu (rotate orientation permanent) it works and roatates my game 180. its the only thing thats working atm, but useless in battle to look around quickly, so needs to be a keybind. Thanks for your work btw.
