### ISSUE TITLE
Cant see all of settings in video - can't scroll neither

### ISSUE THREAD

**Issue by guysoft** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#579]
**Describe the bug**

**To Reproduce**
1. Compile form current master branch
2. Click on video
3. Scroll down to '....'Scroll down to '....' .. you can't scroll

**Expected behavior**
Should be able to see all of options

**Screenshots**
![Screenshot_20211214_195049](https://user-images.githubusercontent.com/325670/146052856-26d42153-8f3b-48c1-ac1a-311aba5eab73.png)

**Software (please complete the following information):**
 - OS: 
 - Advanced Settings Version: 

**Hardware (please complete the following information):**
 - CPU: Ubuntu 21.10
 - Graphics Card: NVIDIA GeForce RTX 2060 with Max-Q Design/PCIe/SSE2
 - HMD: Original HTC Vive

**Additional context**
* I had to compile from source because the steam version segfaults.
* I had to use master branch and not a tagged version because qt complains about QTFlags being deprecated

I am trying to get night mode to work on the headset, it does not seem to work on the menu, so any workaround to get that to work would be appreciated. 
(I have also tried this: https://github.com/ValveSoftware/SteamVR-for-Linux/issues/462 , and this https://github.com/egemenertugrul/LuxVR/issues/1 )

**Comment by ykeara** [comment]
Going to close out this issue due to age, hopefully this has been corrected by now? but based on what I'm seeing I would just expect a dependency change caused the formatting change.
