### ISSUE TITLE
qt5-quickcontrols requirement

### ISSUE THREAD

**Issue by Xandaros** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#580]
When I attempted to use OVRAS, it would not run. It turns out that, in addition to the dependencies listed in the readme, a package called `qt5-quickcontrols` (at least on arch) is also required.

I have not tried the AUR package, but a cursory glance at its dependencies also suggests that it is missing there.
Building from source does not seem to require this package to be installed, but actually running OVRAS does.

**Comment by username223** [comment]
Thanks for this. I've added a PR that adds this to the docs. I'll add it to the AUR package when I get time.

**Comment by username223** [comment]
This has now also been fixed in version 5.4.0 on the AUR.
