### ISSUE TITLE
Unable to launch using Flatpak version of Steam

### ISSUE THREAD

**Issue by xeals** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#582]
**Describe the bug**
A [Flatpak distribution of Steam](https://flathub.org/apps/details/com.valvesoftware.Steam) exists as a simplified method of distributing Steam. The AppImage runtime requires `libfuse` to run, but the distribution does not include it.

**To Reproduce**
1. Install Flatpak distribution of Steam
2. Set up SteamVR and install OVR Advanced Settings
3. Attempt to launch

**Expected behavior**
OVR Advanced Settings to launch.

**Screenshots**

Console output log when attempting to launch the app:

```
GameAction [AppID 1009850, ActionID 3] : LaunchApp changed task to BPMHybridOverlay10ftShutdown with ""
GameAction [AppID 1009850, ActionID 3] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 1009850, ActionID 3] : LaunchApp changed task to SynchronizingControllerConfig with ""
GameAction [AppID 1009850, ActionID 3] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 1009850, ActionID 3] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 1009850, ActionID 3] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 1009850, ActionID 3] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0/home/xeal/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1009850 -- '/home/xeal/.local/share/Steam/steamapps/common/OVR_AdvancedSettings/run.sh'\0
Game process added : AppID 1009850 "/home/xeal/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1009850 -- '/home/xeal/.local/share/Steam/steamapps/common/OVR_AdvancedSettings/run.sh'", ProcID 2162, IP 0.0.0.0:0
chdir /home/xeal/.local/share/Steam/steamapps/common/OVR_AdvancedSettings
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run.
You might still be able to extract the contents of this AppImage
if you run it with the --appimage-extract option.
See https://github.com/AppImage/AppImageKit/wiki/FUSE
for more information
```

**Software (please complete the following information):**
 - OS: Linux NixOS 21.11 / Flatpak Steam runtime
 - Advanced Settings Version: 

**Hardware (please complete the following information):**
 - CPU: AMD Ryzen 7 5800X
 - Graphics Card: AMD Radeon RX6700XT
 - HMD: HTC Vive

**Additional context**
This is a known issue with Flatpak attempting running AppImage as setuid root is not available inside the sandbox. RetroArch has moved away from using AppImage to the Steam Soldier runtime, and the suggestion has been raised to [SuperTuxCart](https://www.gamingonlinux.com/2022/01/supertux-released-free-on-steam-an-open-source-classic/comment_id=217269) to do the same. A recent upstream issue https://github.com/flathub/com.valvesoftware.Steam/issues/770 might contain some useful information if this is something worth solving.

**Comment by ykeara** [comment]
Going to close out hopefully issue resolved if not please re-open.

**Comment by soredake** [comment]
@ykeara nothing has changed, flatpak'ed steam still don't support launching appimages.

**Comment by Atemu** [comment]
@ykeara This is not resolved unfortunately. Single-binary AppImages cannot be run in nested containerisation situtaions like Flatpak, Snap, NixOS' FHSEnv or even the Steam Linux runtime.

Is there a specific reason why OVRAS is distributed as a single AppImage file rather than in its extracted form on Steam?  
We don't need the single binary simplicity here because Steam handles the complexity of distributing multiple files for us.  

In NixOS, we have an appimage-run wrapper which unpacks the AppImage and then runs the extracted binary because we can't run AppImages directly. Prepending that in the run.sh script makes OVRAS work just fine.

**Comment by HugKitten** [comment]
There is a fix for anyone who still wants to get this to work. Don't use proton, and go to the files, and edit run.sh to this:
```#!/usr/bin/env bash
unset LD_LIBRARY_PATH
./OVRAS.AppImage --appimage-extract-and-run

export APPIMAGE_EXTRACT_AND_RUN=1
./my.AppImage [...]

export APPIMAGE_EXTRACT_AND_RUN=1
env NO_CLEANUP=1 ./my.AppImage```

**Comment by WhittlesJr** [comment]
Trying to run on NixOS, and hitting this issue. I tried to set run.sh to the following:

```
#!/usr/bin/env bash
unset LD_LIBRARY_PATH
appimage-run ./OVRAS.AppImage
```

And it gets farther, but then I get:

```
[ERROR] 2023-07-20 07:26:34: QML Error: file:///home/alexj/.cache/appimage-run/a6a77dc62675df9a45521a790f5ba3517aa4460198b05e856596094fdd8ef40c/usr/bin/res/qml/common/mainwidget.qml:1:1: plugin cannot be loaded for module "QtQuick": The plugin '/nix/store/dp264wcfcgbiks1ms65hc25i4klbjm6d-qtdeclarative-5.15.9-bin/lib/qt-5.15.9/qml/QtQuick.2/libqtquick2plugin.so' uses incompatible Qt library. (5.15.0) [release]
```

I suggest this issue should be reopened.
