### ISSUE TITLE
Ability to suspend/resume controller tracking

### ISSUE THREAD

**Issue by Bluscream** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#588]
**Is your feature request related to a problem? Please describe.**
Yes, for example in VRChat when you want your hands to stay in a certain position but lay your controllers down.

**Describe the solution you'd like**
A binding that i can assign to any controller button that will suspend/resume tracking of that controller.

**Describe alternatives you've considered**
A mod for every game that does the same thing

**Additional context**

**Comment by ykeara** [comment]
This is not possible in OVRAS how we are architected, as it requires hooking into the driver calls.
