### ISSUE TITLE
Make a version.txt file for OVRAS

### ISSUE THREAD

**Issue by TheJokingTeen** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#593]
**Is your feature request related to a problem? Please describe.**
It's difficult to know your OVRAS version when creating bug reports, would be nice to have a file that tells me in the main folder.

**Describe the solution you'd like**
put version.txt file in main and just put in 5.4.0 or whatever version it is in the text file.

**Describe alternatives you've considered**
Looking for version but lazy and idk how. (for release branch you could just verify on steam and check but it's not really an optimal solution)

**Additional context**
no

**Comment by username223** [comment]
There should be a log file in `%appdata%/AdvancedSettings-Team` (`C:\Users\<username>\AppData\Roaming\AdvancedSettings-Team`) that prints the version number on every start.

**Comment by ykeara** [comment]
Closing out issue version is displayed on main page and logs.
