### ISSUE TITLE
bug why again screen ghost menu OVR help! thank you

### ISSUE THREAD

**Issue by catpat13** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#597]
**Describe the bug**

**To Reproduce**
1. Go to 'i open OVR laucher steam'
2. Click on 'i cant read ovr settings menu ghost '
3. Scroll down to 'see screeshot '

**Expected behavior**

**Screenshots**

![sadsdaasdasd](https://user-images.githubusercontent.com/103331044/162586191-59fba1ba-faa3-40f1-8074-0d70865605b5.png)

**Software (please complete the following information):**
 - OS: windows 10
 - Advanced Settings Version: 

**Hardware (please complete the following information):**
 - CPU:ryzen 7 3600
 - Graphics Card: rtx 3060
 - HMD:vr quest 2

**Additional context**

**Comment by abh0r** [comment]
@catpat13 Did you disable your integrated graphics card? I solved the problem after re-enabling the integrated graphics card, maybe you can have a try.

**Comment by ykeara** [comment]
Issue: Upon clicking ADV-Settings icon no page shows up.

Cause: related to multiple GPU systems Displaying OpenGL on low power GPU first (IGPU's primarily) [some programs such as alvr may also cause this issue]
Solution for Nvidia GPU's: go to Nvidia Control Panel -> manage 3D settings -> Program Settings -> add Advanced Settings, and change OpenGL Rendering GPU to the GPU your VR is connected to.
Solution for Windows (1803+): go to Settings -> System -> Display -> Select Classic App and Browse for AdvancedSettings.exe -> Click Options -> Select High Performance
