### ISSUE TITLE
Missing dependencies for Arch Linux

### ISSUE THREAD

**Issue by CrispyPin** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#601]
It is not possible to compile the latest version of OVRAS on Arch without also installing `qt5-websockets`

After building, it won't run without also installing `qt5-quickcontrols` and `qt5-quickcontrols2`

These should be added to the build instructions.

The steam/AppImage version still segfaults after installing these, even though a self compiled binary runs. Help on debugging that would be appreciated.  
For now I have edited run.sh in the steam installation to launch my build instead.

OS: Arch Linux (latest)
OVRAS version: 5.5.0 (latest)

**Comment by ykeara** [comment]
Think this has been remedied, but confirmation would be appreciated

https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/commit/3be11339b96d867149c5ecfccd7be45d70e0eeaf#diff-66bbcb9a701cc38169eda88178c155548edef1164cec803ce3a11282d13288ec relevent commit
