### ISSUE TITLE
Space mover flickers rapidly and does not move

### ISSUE THREAD

**Issue by Endimyonn** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#602]
**Describe the bug**
When I try to use the space mover bind, it my camera flicks rapidly between an extreme offset and where I was, and it never actually moves.

**To Reproduce**
Fresh install of Windows 11, SteamVR, and OVRAS as of today. Index HMD & Controllers, no other trackers.

**Expected behavior**
To move

**Screenshots**
https://streamable.com/7v5gp0

**Software (please complete the following information):**
 - OS: Windows 11
 - Advanced Settings Version: 5.5.0

**Hardware (please complete the following information):**
 - CPU: Ryzen 9 3900x
 - Graphics Card: Nvidia RTX 3080 Ti
 - HMD: Index

**Additional context**
All SteamVR settings are at stock, aside from base station hibernation, HMD refresh rate, and HMD brightness.

**Comment by morerokk** [comment]
Same issue here after updating. Not entirely sure why.

**Comment by ykeara** [comment]
@morerokk honestly hop into discord https://discord.com/invite/vgvSkSk will need logs and such

as of 5.8.11 the only thing I'm aware of causing issues like described is With space calibrator and the checkbox for `Paste chaperone bounds automatically when geometry resets`

Trying to track down exact issue, but don't have enough reports/logs to find the cause yet.

**Comment by Endimyonn** [comment]
The bug has been fixed for a couple years. I think a restart fixed it at the time, at least temporarily. Closing this for posterity.
