### ISSUE TITLE
OVR Advance Settings appears but menu invisible when opened

### ISSUE THREAD

**Issue by Foorack** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#607]
**Describe the bug**
The "VRC AdvancedSettings" **button** does show up in SteamVR's menu, but once clicked it shows a completely invisible menu. There is nothing except the lower bar with the buttons to exit, OVR, Store, Desktop, etc..

**To Reproduce**
Steps to reproduce the behavior: Unknown, on-going issue for +1 week now.

**Expected behavior**
For VRC Advanced Settings's menu to show in SteamVR menu.

**Screenshots**
![](https://user-images.githubusercontent.com/5008081/173193371-090a1643-8747-4f8a-a94f-9eb8fbd2c592.png)

**Software (please complete the following information):**
 - OS: Windows 11 22H2 (22621.1)
 - Advanced Settings Version: 5.5.0

**Hardware (please complete the following information):**
 - CPU: AMD Ryzen 5 3600X
 - Graphics Card: SAPPHIRE Radeon Pulse RX5700 XT 8G OC
 - HMD: Valve Index

**Additional context**
Full SteamVR restart and PC reboots attempted many times. Tried purge and reinstall OVRAS. Tried deleting user-settings in Roaming.
Don't know if related, but log very often spams "Chaperone not calibrated?".

AdvancedSettings.log - https://gist.github.com/Foorack/1d1c3d8a5a5153c6dfe860bf43c4f55d
OVR Advanced Settings.ini - https://gist.github.com/Foorack/00c73584b25dfa6c0b0a12df0d0ac82f

**Comment by abh0r** [comment]
@Foorack Did you disable your integrated graphics card? I solved the problem after re-enabling the integrated graphics card, maybe you can have a try.

**Comment by ykeara** [comment]
Closing in favor of #565
