### ISSUE TITLE
Playspace mover limited to the seated position when im room scale

### ISSUE THREAD

**Issue by GodsTheGamer** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#610]
**Describe the bug**
So since this 5.5 ovr kit I have not been able to use it effectively, And I looked on reddit, and it describes my problem exactly, The only time i can use playspace mover is when im standing in the middle of my room, the problem is that i am roomscale not sitting, and the "fix" is to use the seated something override but there is no override in the settings, 

**To Reproduce**
1. Go to OVR 5.5 (Github version not steam)
2. Launch it
3. Be sure to be using room scale on SteamVR
4. Notice the error because you can't move without specific stuff  like you randomly grab it, but never be able to fix it because the override option got removed or I can't see it.

**Expected behavior**
Playspace mover doesn't work unless you grab one of the points specifically

**Screenshots**
n/a
**Software (please complete the following information):**
 - OS: Windows 10
 - Advanced Settings Version: 5.5

**Hardware (please complete the following information):**
 - Graphics Card:  GTX 3080ti 
Most isnt needed i just need the override option...

**Additional context**
I could just need to use the steam version but i hate the steam version so uh yeah.

**Comment by GodsTheGamer** [comment]
Remember it is only the override I need so if it is possible to get the option back that would be a great help.

**Comment by ykeara** [comment]
Going to close out this issue, Reverted a change that caused some issues, I should note that the setting IS NOT required and should just be on. If you are still having issues in motion tab there is an "ignore boundary state' option you can try now, this setting does not persist through restarts currently, if you still have issues feel free to re-open issue.
