### ISSUE TITLE
Rotate playspace vertically. 

### ISSUE THREAD

**Issue by The-Scout** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#615]
**Is your feature request related to a problem? Please describe.**
Yes, I am disabled, and sitting up, or standing for long periods of time is very uncomfortable.

**Describe the solution you'd like**
A slider to rotate the playspace vertically so I can lay down while playing.

**Describe alternatives you've considered**
I cannot find any looked everywhere online for this feature.

**Comment by ykeara** [comment]
not possible with our architecture
