### ISSUE TITLE
ovr advanced settings issues on steam

### ISSUE THREAD

**Issue by Jager2000** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#620]
Steamvr button shows but nothing in menu i tried all the steps so i guess my graphics card doesn't support it

**Software (please complete the following information):**
 - OS: windows 10 latest
 - Advanced Settings Version: latest on steam

**Hardware (please complete the following information):**
 - CPU: Intel i5 10400f
 - Graphics Card: intel arc a770

**Comment by ykeara** [comment]
Unfortunately I think this attributed to ark's  driver's primarily, and unless we extend support to  other graphics api's besides opengl this is unlikely to change for us, as it stands we just can't really support ark's gpu's
