### ISSUE TITLE
OVR Advanced Settings not starting

### ISSUE THREAD

**Issue by InfoBlock** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#623]
**Describe the bug**
As the title says.. I've tried the Standalone Version, even tried it via the Steam version but it doesn't start up at all! I'm trying to run it on Desktop Mode with the start option --desktop-mode

**Expected behavior**
OVR Advanced Settings starting in Desktop Mode

**Software (please complete the following information):**
 - OS: Windows 10 Home
 - Advanced Settings Version: 5.3.1

**Hardware (please complete the following information):**
 - CPU: AMD Ryzen 5 Six-Core Processor
 - Graphics Card: NVIDIA GeForce GTX 1650
 - HMD: None

**Comment by ykeara** [comment]
Going to close out this ticket as it should be resolved with 5.7.0

but a few things to note we REQUIRE steamvr to run,  before 5.7 we would error out if no hmd found (now we should run with just some logging behind the scenes) without and HMD but SteamVR is REQUIRED
