### ISSUE TITLE
Option to compensate for eye turn?

### ISSUE THREAD

**Issue by Mark-Renzi** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#633]
**Is your feature request related to a problem? Please describe.**
When I was younger I had strabismus.  This is an eye condition where one eye is turned too far in, making it difficult for the eyes to work together to see proper depth.  I had surgery to fix it and that was the end of it.  As an accessibility option it would be wonderful if it was possible to adjust for this so that I could see depth without needing to wear correcting glasses inside of VR.  I recently learned one of my friends also has strabismus and has never seen depth and has asked what it's like.

**Describe the solution you'd like**
If there was an accessibility option to turn the view of both eye renderers slightly inward to account for strabismus, or slightly outward for exotropia, that would allow affected users to enjoy more VR experiences.

**Describe alternatives you've considered**
Software exists to demonstrate this concept in demos and it is a genuinely pleasant experience to have something adjustable that helps make games feel more immersive.  Adding this to a plugin seems like the best solution to have it active everywhere.  

**Additional context**
My hope is that this is possible based on the similarity with the feature of the overlay's ability to scale the world around you, but I understand that this could very well not be possible.  It could cause discomfort in users who do not need it, so openvr or steam may have locked the possibility of this like this out.

**Comment by ykeara** [comment]
While I think this might actually be do-able with intercepting driver calls, it is unfortunately not feasible with OVRAS current design
