### ISSUE TITLE
scaling play space locomotion  for roomscale

### ISSUE THREAD

**Issue by dallytaur** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#636]
i have a small play space it and when hanging with frends they run around a lot and even if you run you cant keep up

It would be nice to be able to scale how far you move over working with your place space  such as 1m in real is 10m in vr.

I couldnt find any app that does this other then vive craft and that is per app

**Comment by ykeara** [comment]
Using space drag as a movement option is in general not a great idea, as we are completely ignorant of the game world and can cause issues (i.e. running into walls etc.) we also have other concerns as well. 

But in general probably won't implement this, it should be noted you can add multipliers to your drag so the drag does not represent 1->1 motion but 1->2 etc.
