### ISSUE TITLE
Nothing shown on a rig with intel ARC graphics card

### ISSUE THREAD

**Issue by camegone** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#647]
**Describe the bug**
Nothing displayed on steamVR dashboard. My PC is equipped with Intel ARC graphics card. I confirmed SteamVR and advanced Settings are set to use High performance GPU. I also tested with iGPU disabled, but the screen did not appear.

**Software (please complete the following information):**
 - OS: Windows11 Pro 22H2
 - Advanced Settings Version: 5.7.4

**Hardware (please complete the following information):**
 - CPU: 13th Gen Intel(R) Core(TM) i5-13600K   3.50 GHz
 - Graphics Card: intel ARC A770 limited edition
 - HMD: Meta Quest 3 (With Virtual Desktop)

**Comment by ykeara** [comment]
At this time we don't work with intel arc graphics.

ultimately we only use opengl for our rendering specifically offscreen, and arc's support is not great, so if they push updates check back or if we make an announcement about supporting directx or vulkan you should also check in.

**Comment by NeneNyann** [comment]
I made a temporary compatibility layer to make it work on Windows with Intel Arc graphics cards. The source code and releases are available here: https://github.com/NeneNyann/IntelOpenGLVRFix

**Comment by ykeara** [comment]
> I made a temporary compatibility layer to make it work on Windows with Intel Arc graphics cards. The source code and releases are available here: https://github.com/NeneNyann/IntelOpenGLVRFix

Actually really helpful, in the middle of transitioning away from opengl as default render, but this is super useful, I'll have to give it a look, but assuming a quick inspection turns out all good, I'll certainly direct people to the workaround, possibly make a build specifically for it.

**Comment by NeneNyann** [comment]
> > I made a temporary compatibility layer to make it work on Windows with Intel Arc graphics cards. The source code and releases are available here: https://github.com/NeneNyann/IntelOpenGLVRFix
> 
> Actually really helpful, in the middle of transitioning away from opengl as default render, but this is super useful, I'll have to give it a look, but assuming a quick inspection turns out all good, I'll certainly direct people to the workaround, possibly make a build specifically for it.

Thanks, glad this is useful. Since you're already transitioning away from OpenGL as the default renderer, this seems like a reasonable workaround until that transition is complete. I appreciate you taking the time to review it and considering a dedicated build for affected users.

**Comment by 1zyao** [comment]
Also affected on Intel Arc B580. Built a version that submits the overlay via D3D11 (`TextureType_DirectX`) instead of OpenGL, bypassing `WGL_NV_DX_interop`.

Source: https://github.com/1zyao/OpenVR-AdvancedSettings/tree/master
