### ISSUE TITLE
SteamVR lag

### ISSUE THREAD

**Issue by nikorue** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#648]
SteamVR dashboard lag, started happening before 2.0 update, still persists

open steamvr, start playing, after about an hour opening steamvr in-game will cause lag on gpu (ft 7ms to 60ms)

forcing ovras down usually stops this issue

Win 11
combined tracking and seperate tracking of:
Quest Pro via VD
Index

 - CPU: R7 5800X3D
 - Graphics Card: 3070Ti

i can't pin point the cause of this issue, help needed

**Comment by ykeara** [comment]
I'm pretty sure this is actually a VRAM/RAM issue. it could be on Valve's Side or ours, but unfortunately it's doubtful I address it until I change major things about our rendering loop.... which is not straightforward.
