### ISSUE TITLE
F13-F24 Keyboard Support for Custom Buttons

### ISSUE THREAD

**Issue by GabrielSerealia** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#649]
**Is your feature request related to a problem? Please describe.**
I use the F13-F24 for non intrusive keybinds for things like discord and OBS and would like to be able to use them with the OVR Advanced Settings custom and mic buttons.

**Describe the solution you'd like**
The ability to bind F13-F24 in the .ini config

**Describe alternatives you've considered**
Using AKH to rebind things like ^SCRLOCK, *SCRLOCK, >SCRLOCK to the F13-F24 keys

**Additional context**
[keyboardShortcuts]
keyboardOne=^SCRLOCK
keyboardTwo=*SCRLOCK
keyboardThree=>SCRLOCK
keyPressSystem=#SCRLOCK
keyPressmisc=F9

**Comment by ykeara** [comment]
next update I'll Extend to F19 via `G9`

I may Extend to `H4` for F24

||yes I know it's cursed but it's trivial to add to parser this way||

**Comment by GabrielSerealia** [comment]
Cursed code or not as long as it works haha
Thank you very much!

**Comment by ykeara** [comment]
Keys Extended to F19 vai `G9` as of 5.8.3 going to close as resolved.
