### ISSUE TITLE
OVR menu broken.

### ISSUE THREAD

**Issue by menabeshai** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#653]
**Describe the bug**
The menu overlay isn't showing at all.

**To Reproduce**
1. Go to 'SteamVR with OVR advance settings enabled as an add-on'
2. Enable developer mode via advanced settings.
3. Turn on start button brings menu.
4. press the start button on the left controller.
The menu system doesn't show up at all. library, OVR, desktop+, etc. however, space mover still works. but i can't access any of those settings anymore. only change key binds.

**Expected behavior**
The menu layout should show up.

**Screenshots**
I can show all my settings but it wouldn't help. my workaround atm is to go to SteamVR Home and launch from there. however, I enabled it and it doesn't take me there as default. which doesn't help.

**Software (please complete the following information):**
 - OS: Windows 10 22H2 (Build 19045.3693)
 - Advanced Settings Version: build ID. 12397380 (idk what build version so just did ID)

**Hardware (please complete the following information):**
 - CPU: 9900k
 - Graphics Card: 3090 ti 
 - HMD: usb c (sort of)

**Additional context**
I plug in the usb c to enable HMD but once connected I can disconnect and it's still active cause I use airlink.
also, i've attempted 5.3.1, 5.7.3, and beta. none of them fix the problem. I've attempted the same thing on SteamVR to give hope of compatibility between the 2. the newest update that steamVR and OVR had at the same time or close to each other. is the update that killed everything. everything was working beautifully fine. till about 5.7.2 or 5.7.4 came out. i've tried rolling back but beta options don't give me the option for the version I used. even if so would it even work since both aren't the latest versions?

I need 5.7.0 or 5.6.8 cause those worked. but those options aren't available.

BTW OCULUS quest 2. yes, i've restarted SteamVR, turning off all addons and then turning only OVR on. still nothing. and when I look at the controller in SteamVR i see the button going down. so it's registering. and did the test in the software and it does register. The menu overlay doesn't want to show up. I even messed with the nvidia control panel. which I got the latency lowered. but still, overlay doesn't work.

I've asked Reddit, but no help, steam got nothing, or isn't the same problem. here people have simular but not exact. so I figured to create a bug report in the main location.

**Comment by ykeara** [comment]
With 5.8.3 I would suggest using "desktop mode" launch option, and then in settings turn on always use desktop mode, while this is not a perfect solution, it does allow you to use 100% of the functionality from desktop rather than the menu and should resolve most of the issues.
