### ISSUE TITLE
Change the settings and log file paths

### ISSUE THREAD

**Issue by username223** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#66]
The log file is currently saved in `%APPDATA\matzman666\OpenVRAdvancedSettings`. `matzman666` should be replaced with something more descriptive, like `OVRAS-Team` or `AdvancedSettings-Team`.

The settings file is saved in `%APPDATA\matzman666` it should also be changed to be more descriptive.

Both `.ini` and `.log` files could also be placed in the executable directory. Although this wouldn't make settings globally available.

**Comment by ykeara** [comment]
Any Reason to not just save both in %APPDATA\OpenVRAdvancedSettings?

**Comment by username223** [comment]
@ykeara IIRC the settings file is saved in `COMPANY_NAME\APPLICATION_NAME` or something like that. I can't remember if it's hardcoded or just recommended. But if it's possible it would definitely make sense just to put it in `%APPDATA%\OpenVRAdvancedSettings`.
