### ISSUE TITLE
Create an overview of current thread usage and a plan for future use

### ISSUE THREAD

**Issue by username223** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#67]
It is currently unknown how many threads the application runs on.

Running the release build in Qt Creators debugger on Windows shows 4 threads; one main thread and 3 threads created by Qt.

All business logic appears to be done on the main thread, however there are several mutexes used in the code in functions that should not be callable at the same time (execution tied to GUI buttons). It is unknown why these are here.

Adding an additional thread for business logic might make it possible to run one or more pieces of functionality on a worker thread, increasing the effectiveness of the application on lower end systems.

**Comment by ykeara** [comment]
At least some threads are spawned off only one I have seen so far is for Haptics in Chaperone Tab, again with new input api doubt its necessary.
