### ISSUE TITLE
OVR Advanced settings gone from the German steam store

### ISSUE THREAD

**Issue by Donad678** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#679]
**To Reproduce**
1. Go to the steam store page of the app

**Expected behavior**
Application should be available.

**Screenshots**
![image](https://github.com/user-attachments/assets/c2e0dcfc-a45f-45a6-be8c-63728cb6cc6a)

**Additional context**
Germany now requires all games and apps available on steam to have a valid age rating, more context here, they only mention games but it also seems to affect tools like ovr
https://store.steampowered.com/news/group/4145017/view/4678768276768588863?l=english

**Comment by ykeara** [comment]
Thanks for this heads up, had another German person reported it missing, and then back, from my end on the backend I see it as all good, but if people are still getting the issue I'll go ahead and open a ticket with steam.

**Comment by ykeara** [comment]
K figured it out and think I got it resolved, my quick tests show it's back live but it might take a bit of time for it to be up everywhere because weird internet cacheing things, I'll check back tommorow and if it's good I'll close this.

**Comment by ykeara** [comment]
K should be fixed now, marking as closed if there are additional issues let me know
