### ISSUE TITLE
[Request] Reset combination for playspace on controllers.

### ISSUE THREAD

**Issue by zaCade** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#70]
I'd like to suggest/request the ability to reset playspace with a controller combination, similiar to how PlayspaceMover does it, or different if you guys know a better way. Simply because going into the menu to reset when you moved alot is quite the hassle, and takes quite a bit of time if you actively playing a game, simply hitting a controller key combination to reset, would be quite alot faster. This should probably be optional through. Maybe also make both move and reset buttons configurable somehow, so we could remap it to different buttons, instead of being forced to the menu buttons.

Main reason i'm requesting these things is because InputEmulator and PlayspaceMover are great tools, but are not fully functional anymore due to development being missing on these tools, i'm aware other users decided to branch off and make their fixes on these tools.

**Comment by username223** [comment]
We're currently converting the program to use the new Steam input system which allows for arbitrary user bindings.

@Kung-vr is working on some Playspace stuff right now, maybe he could slip it in?

**Comment by Kung-vr** [comment]
I have rebinding playspace move (and the new rotate feature) working. I'll add a bind for reset too. Good idea. Thanks!

**Comment by ykeara** [comment]
Solved BY PR #92 or #93
