### ISSUE TITLE
Movement Restricions

### ISSUE THREAD

**Issue by MaxAbillion12** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#90]
A game that I play quite often doesn't allow me to go further than 15ft(4.572m) from my playspace, and this can be quite frustrating with physics on, so  I was wondering if anyone knows how to restrict movement once you reach a certain x, y, or z value.

**Comment by ykeara** [comment]
more or less will be.

```if(offsetx >= 4.572){
offsetx = 4.572
}
```
(and for x and y)
More or less should be all you need to do in movecentertabcontroller.h, but that should more or less do what you described.

If you are referring to https://github.com/naelstrof/VRPlayspaceMover then that is not related to our "playspace mover" (we are changing some names around so its not quite as ambiguous for 3.0.0)

**Comment by MaxAbillion12** [comment]
Yes, https://github.com/naelstrof/VRPlayspaceMover is what I was referring to, sorry for asking you, but nobody there is active, so my question wasn’t answered and I thought, since you have playspace moving experience, that you could help... so do you know where in the playspace mover files I would put that code, or if I could do it in openvr.h, or something?

**Comment by ykeara** [comment]
I haven't really looked at naelstrof's version, but its possible it is a completely different implementation.

The provided code is not exactly what would be needed in our version let alone an entirely different application.

You cannot add it to openvr.h

If limiting max playspace move is a feature you would like to see in ADV settings then we can look into implementing it, but we need to know use-cases? what game is it? are other people bothered would want this feature? does it make sense in the scope of the project?

outside of that I would recommend making an issue on naelstrof's repo, or reaching out to various community outlets such as /r/steamvr

**Comment by MaxAbillion12** [comment]
I guess since there is no way to accidentally fly extremely far, in this case there would be no use for it. Thank you!
