### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by MaxAbillion12** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#94]
Exactly where is the x, y, and z position for the hmd output? Also, what is the format for setting the x, y, and z values, because I would like to put code right before that, so I can manually set my own position.

**Comment by ykeara** [comment]
Would suggest looking into here.
openvr api:
https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h

another project, should have the adjustment pose code in this.
https://github.com/sharkyh20/OpenVR-InputEmulator

To the best of my knowledge we don't modify pose's yet in our app, but links above should find example code, and api info below should get you started working with it.

relevant struct

```
struct TrackedDevicePose_t
{
	HmdMatrix34_t mDeviceToAbsoluteTracking;
	HmdVector3_t vVelocity;				// velocity in tracker space in m/s
	HmdVector3_t vAngularVelocity;		// angular velocity in radians/s (?)
	ETrackingResult eTrackingResult;
	bool bPoseIsValid;

	// This indicates that there is a device connected for this spot in the pose array.
	// It could go from true to false if the user unplugs the device.
	bool bDeviceIsConnected;
};
```
co-ord system used.

```
// right-handed system
// +y is up
// +x is to the right
// -z is forward
// Distance unit is  meters
```
**pretty sure**
its

position
velocity
rotational position
rotational velocity?

in the matrix's
its x, y, z values, in that order from what I'm looking at quick.

and its a float array.

**Comment by MaxAbillion12** [comment]
Okay, thank you so much

**Comment by ykeara** [comment]
Fixing a Mistake...

It appears the HMD 3x4 matrix IS NOT as I described...

I think more correctly...

[0,3][1,3][2,3] represent x, y, z displacement from origin (center room)

The remaining 3x3 matrix represents your orientation... sorry for the confusion.
